fix(mechanics): Don't pass through wormholes if fleet jumping until escorts are ready
endless-sky/endless-sky pull request #10114
Opened 2024-05-29 11:06 UTC by Koranir

**Bug fix**

This PR addresses the bug/feature described in issue #10065

## Summary
This adds the same kind of mechanism as existing fleet jumps were for jumping on going through wormholes.

2024-05-30 19:49 UTC, TomGoodIdea approved these changes
Code is ok, but I can't test it, because the bug doesn't trigger for me.

2024-05-30 20:21 UTC, RisingLeaf reviewed
Looks good

2024-05-30 20:21 UTC, RisingLeaf commented on source/AI.cpp
> +	bool EscortsReadyToLand(const Ship &ship)
```suggestion

	bool EscortsReadyToLand(const Ship &ship)
```

2024-05-31 06:37 UTC, RisingLeaf approved these changes

2024-06-02 11:44 UTC, tibetiroka requested changes

2024-06-02 11:44 UTC, tibetiroka commented on source/AI.cpp
> +			if(escort->IsDisabled() || escort->CanBeCarried())
Since fighters can land on wormholes, I don't think they should be excluded.
```suggestion
			if(escort->IsDisabled())
```

2024-06-03 05:55 UTC, tibetiroka approved these changes

2024-06-05 06:41 UTC, merged