fix(mechanics): Properly reset player flagship after death
endless-sky/endless-sky pull request #10128
Opened 2024-05-30 18:46 UTC by tibetiroka

**Bug fix**

This PR addresses the bug described in issue #10125 

## Summary
Resetting the player flagship seems to fix most issues, except:
 - the ammo counter is still visible (but cannot be interacted with)

## Testing Done
Tested with a mission that kills the player on a planet. Needs testing with mid-flight death.

2024-05-30 19:06 UTC, TomGoodIdea commented
You can't depart wihtout a flagship, but you still have access to some other options, like the trading panel
![Screenshot_20240530_210444](https://github.com/endless-sky/endless-sky/assets/108272452/8ab1c34e-79f6-480a-b146-c853adb97fc0)

2024-05-30 20:50 UTC, TomGoodIdea commented
> The other two may be done in a separate PR, maybe we just drop the planet panel on death

I think destroying the planet panel on death would fix this issue as well, because without a planet panel the player wouldn't be able to depart

2024-05-30 23:42 UTC, TomGoodIdea commented
Simple flagship reset isn't solving anything, here's a screenshot from the outfitter:
![1](https://github.com/endless-sky/endless-sky/assets/108272452/b0764213-ef10-4875-96c4-f447afa94735)
And here's your save from #10125, but moved the player to Luna:
[Matthew_WeaverGhost.txt](https://github.com/user-attachments/files/15506720/Matthew_WeaverGhost.txt)
There's a shipyard on Luna, so you can just go there, buy a new ship and depart, but you're still considered dead.

2024-05-31 15:16 UTC, tibetiroka commented
> You can't depart wihtout a flagship, but you still have access to some other options, like the trading panel

I can't reproduce that. When I die on a planet, I don't see the trading panel, neither in this PR on on master.

2024-05-31 15:24 UTC, tibetiroka commented
I think I got all the necessary UI fixes in as well. Do you have a save file for a mid-flight death for testing?

2024-05-31 15:42 UTC, RisingLeaf commented
I would still prefer if you popped the planet panel instead of blocking input

2024-05-31 15:48 UTC, tibetiroka commented
Looks like I need to do both.

2024-05-31 15:54 UTC, RisingLeaf requested changes

2024-05-31 15:54 UTC, RisingLeaf commented on source/PlanetPanel.cpp
> +		GetUI()->Pop(this);
This should be a popThrough and inside step

2024-05-31 15:54 UTC, RisingLeaf commented on source/MainPanel.cpp
> +		show = Command::NONE;
```suggestion
		show = Command::NONE;

```
And a comment pls

2024-05-31 15:54 UTC, RisingLeaf commented on source/MainPanel.cpp
> +		return true;
```suggestion
		return true;

```

2024-05-31 15:54 UTC, RisingLeaf commented on source/PlayerInfo.cpp
> +	flagship.reset();
```suggestion

	flagship.reset();
```

2024-05-31 16:15 UTC, RisingLeaf approved these changes
I am not able to test, but looks good

2024-06-01 12:31 UTC, tibetiroka commented
Tested and working with mid-flight death as well.

2024-06-01 12:34 UTC, tibetiroka commented on source/MainPanel.cpp
> +	if(player.IsDead())
```suggestion
	// If the player is dead, don't show anything.
	if(player.IsDead())
```

2024-06-01 12:34 UTC, tibetiroka commented on source/PlanetPanel.cpp
> +	if(player.IsDead())
```suggestion
	// If the player is dead, pop the planet panel.
	if(player.IsDead())
```

2024-06-01 16:44 UTC, TomGoodIdea approved these changes
Looks like it finally works

2024-06-02 19:16 UTC, Amazinite commented on source/AmmoDisplay.cpp
> +
```suggestion
```

2024-06-02 19:17 UTC, Amazinite commented on source/AmmoDisplay.cpp
```suggestion


```

2024-06-02 19:24 UTC, merged