feat(content): Non-bribable Pug planets
endless-sky/endless-sky pull request #10210
Opened 2024-06-15 14:19 UTC by TheGiraffe3

**Bug fix**

This PR addresses the bug/feature described in issue #10209.

## Summary
The Pug planets are no longer able to be bribed until after switching to Neutral. Otherwise, it is possible to completely destroy hundreds of Pug ships and then land on their planets. Although the Republic has the same problem, the Pug are definitely more proud and would like it a lot less. 

## Screenshots
No

## Usage examples
N/A

## Testing Done
None

## Save File
This save file can be used to test these changes:
None. You can start a Forge or Omnis save. 

## Artwork Checklist
N/A

## Wiki Update
N/A

## Performance Impact
N/A

## Alternative Approaches
Make the Pug planets unable to be bribed _only after_ the war with them starts.

2024-06-15 15:03 UTC, ziproot requested changes
If you want to fix #10209, you should make “Deneb” have bribe 0, not the Pug government, which already has bribe 0 by default.

2024-06-15 16:02 UTC, ziproot approved these changes
This now fixes #10209

2024-06-15 16:03 UTC, ziproot requested changes
Oops, my bad, this also needs to be done for “fwc pug defeated”

2024-06-15 16:07 UTC, ziproot requested changes

2024-06-15 16:07 UTC, ziproot commented on data/human/campaign events.txt
> +		"bribe" 0
```suggestion
		"bribe" 0.01
```

2024-06-15 16:07 UTC, ziproot commented on data/human/campaign events.txt
> +		"bribe" 0
```suggestion
		"bribe" 0.01
```

2024-06-15 16:12 UTC, ziproot approved these changes
There we go

2024-06-23 08:02 UTC, TheGiraffe3 commented
Come to think of it, should I add this to the planet in Pug Iyik as well?

2024-06-23 16:21 UTC, ziproot commented
> Come to think of it, should I add this to the planet in Pug Iyik as well?

Vera Pug already cannot be bribed.

2024-06-23 16:23 UTC, TheGiraffe3 commented
Oh…

2024-06-25 09:04 UTC, TheGiraffe3 commented
I think this is ready for review/merge.

2024-06-28 03:54 UTC, TheGiraffe3 commented
This is ready for review/merge.

2024-06-30 20:10 UTC, warp-core commented
I'm not sure pride is a reason for the Pug to not accept your bribe to land.
I'm not even sure proud is an appropriate description of them here. They know humans can defeat the ships they operate here: that's actually the point. The Pug as a whole are still far superior, regardless of what the player does here.

2024-06-30 20:11 UTC, Saugia commented
I agree; I don't think it's a correct assumption that the Pug are "prideful". If anything, it makes much more sense that they're the opposite of the Quarg - the Quarg would acknowledge you and your behavior as a human, especially when you attack innocents or especially their own ships. Meanwhile, it would make sense that the Pug would not care whatever you do as a human. They would brush you off; never see you as a threat. The galaxy is a playground to them - they probably wouldn't care if you broke even thousands of their toys.

2024-07-01 03:56 UTC, TheGiraffe3 commented
Okay, "proud" is the wrong word. But the Pug aren't wanting to get destroyed _before_ the war starts.
Also, the Vara Pug Pug don't let you bribe them.

2024-07-04 20:35 UTC, merged