fix(content): Various Gegno Corroboration Fixes + Other Tweaks
endless-sky/endless-sky pull request #10301
Opened 2024-07-07 04:54 UTC by Saugia

**Content (Artwork / Missions / Jobs)**

This PR addresses the a few unintended behaviors that came up on discord via gameplay with some minor tweaks on the side.

## Summary
With the merge of #8750, some players have found some oversights and bugs already. This PR addresses them.

Conversations now offer at proper times.
Missions no longer offer when the relevant ones have passed.
Etc..

Also threw in a few fleet tweaks.

2024-07-07 04:57 UTC, Saugia commented on data/gegno/gegno I corroboration.txt
> +		not "Gegno Apprehension: offered"
```suggestion
		not "Gegno Intervention: offered"
```

2024-07-07 04:59 UTC, TheGiraffe3 commented on data/gegno/gegno I corroboration.txt
> +	description "Present yourself to the Gegno on <destination> within the next 8 days, where you will find out if you have any future with them."
Also notice this is missing a name.
```suggestion
	name "Summons from the Gegno"
	description "Present yourself to the Gegno on <destination> within the next 8 days, where you will find out if you have any future with them."
```

2024-07-07 05:00 UTC, TheGiraffe3 commented on data/gegno/gegno I corroboration.txt
> +	description "Present yourself to the Gegno on <destination> within the next 8 days, where you will find out if you have any future with them."
```suggestion
	name "Summons from the Gegno"
	description "Present yourself to the Gegno on <destination> within the next 8 days, where you will find out if you have any future with them."
```

2024-07-07 05:00 UTC, TheGiraffe3 requested changes

2024-07-07 05:00 UTC, TheGiraffe3 commented on data/gegno/gegno fleets.txt
>  		"Tridymite"
```suggestion
		"Tridymite"

```

2024-07-07 07:18 UTC, TheGiraffe3 commented
The problem with this as opposed to #10302 is that this PR will take a long time to finish and merge.

2024-07-07 16:41 UTC, Saugia commented
Gonna leave this as a draft for another day or so in case anything else pops up.

2024-07-08 02:43 UTC, Saugia commented on data/gegno/gegno I corroboration.txt
> +		not "Gegno Apprehension: offered"
```suggestion
		not "Gegno Intervention: offered"
```

2024-07-08 02:52 UTC, TheGiraffe3 approved these changes

2024-07-10 23:51 UTC, merged