refactor: Extract magic numbers from Dialog
endless-sky/endless-sky pull request #10323
Opened 2024-07-16 08:11 UTC by tibetiroka

**Refactor**

This PR replaces Dialog's magic numbers with named (and explained) values.

## Summary
- Moves all padding and margin values to the header file as static constants.
- Replaces all width and height values with the actual sprites' width and height
- Fixes button hitboxes to match the buttons' visual size exactly
- Fixes an edge case when re-slimming wide dialogs (it previously ignored the padding, only counted the margin)

## Screenshots
If you can't tell what's before and what's after, it works.
![image](https://github.com/user-attachments/assets/9dca11bc-2593-4e13-9fa7-d0a1631ec2a1)
![image](https://github.com/user-attachments/assets/a79f3fd6-6235-4a84-b988-232020010388)

## Usage examples
Readable code? Dialog sprites we can actually edit now?

## Testing Done
See the screenshots.

2024-07-16 08:29 UTC, tibetiroka commented
Wrong :)

2024-07-16 11:42 UTC, warp-core commented
Why private, static, compile-time constant fields in the header file and not compile-time constants in the Dialog.cpp anonymous namespace?

2024-07-16 11:48 UTC, tibetiroka commented
> Why private, static, compile-time constant fields in the header file and not compile-time constants in the Dialog.cpp anonymous namespace?

Ideally, they would be defined in interfaces anway, especially since input fields use the same values in conversations... 

Sure, I could move them over to the C++ file. I thought they were properties of the dialog class itself, since most of these refer to the sprites' details (such as margins), and therefore aren't implementation details.

2024-07-16 15:47 UTC, RisingLeaf requested changes

2024-07-16 15:47 UTC, RisingLeaf commented on source/Dialog.cpp
> +	string okText = isMission ? "Accept" : "OK";
```suggestion
	const string okText = isMission ? "Accept" : "OK";
```

2024-07-16 15:47 UTC, RisingLeaf commented on source/Dialog.cpp
> +	Point pos(0., (top->Height() + extensionCount * middle->Height() + bottom->Height()) * -.5f);
```suggestion
	Point pos(0., (top->Height() + extensionCount * middle->Height() + bottom->Height()) * -.5);
```
point takes in double, no idea why it was float here before

2024-07-16 15:47 UTC, RisingLeaf commented on source/Dialog.cpp
> +	const int leftMargin = 20;
why did you move away from CAPS_LOCK?

2024-07-16 15:47 UTC, RisingLeaf commented on source/Dialog.cpp
> +	const int inputHeight = 20;
```suggestion
	// The width of the margin on the right/left sides of the dialog. This area is part of the sprite,
	// but shouldn't have any text or other graphics rendered over it. (It's mostly transparent.)
	const int leftMargin = 20;
	const int rightMargin = 20;
	const int horizontalMargin = leftMargin + rightMargin;
	// The margin on the right/left sides of the button sprite. The bottom segment also includes a button
	// that uses the same value.
	const int buttonLeftMargin = 10;
	const int buttonRightMargin = 10;
	const int buttonHorizontalMargin = buttonLeftMargin + buttonRightMargin;
	// The margin on the top/bottom sides of the button sprite. The bottom segment also includes a button
	// that uses the same value.
	const int buttonTopMargin = 10;
	const int buttonBottomMargin = 10;
	const int buttonVerticalMargin = buttonTopMargin + buttonBottomMargin;
	// The width of the padding used on the left/right sides of each segment, in pixels.
	const int leftPadding = 10;
	const int rightPadding = 10;
	const int horizontalPadding = rightPadding + leftPadding;
	// The height of the padding used by the top/bottom segment, in pixels.
	const int topPadding = 10;
	const int bottomPadding = 10;
	const int verticalPadding = topPadding + bottomPadding;
	// The width of the padding at the beginning/end of an input field.
	const int inputLeftPadding = 5;
	const int inputRightPadding = 5;
	const int inputHorizontalPadding = inputLeftPadding + inputRightPadding;
	// The height of the padding at the top/bottom of an input field.
	const int inputTopPadding = 2;
	const int inputBottomPadding = 2;
	const int inputVerticalPadding = inputTopPadding + inputBottomPadding;
	// The height of an input field in pixels.
	const int inputHeight = 20;
```
there is such a thing as too many comments where the readabillity decreases, I do expect the people who read the code have at least some capacity to  read variable names XD.

2024-08-05 07:38 UTC, tibetiroka commented
I don't want to use constexpr since we might want to define these values via interfaces in the future. I could change them to double, though.

2024-08-05 07:42 UTC, tibetiroka commented
Using interfaces would be another refactor, since some of these constants are shared with conversations, for instance. (But they are only magic numbers for now.)

2024-12-03 00:09 UTC, petervdmeer approved these changes

2024-12-03 00:09 UTC, merged