feat(ui): Make long planet/spaceport descriptions scrollable
endless-sky/endless-sky pull request #10371
Opened 2024-08-01 21:11 UTC by TomGoodIdea

**Feature**

This PR resolves #5522.

## Summary
Replaced WrappedTexts handling planet/spaceport descriptions on planet, spaceport, and spaceports map panels with TextAreas that add scrolling capabilities when needed (when the text is higher than the background).

## Screenshots
If a description text fits in the box, it should remain unchanged. Here are some screenshots for descriptions higher than the area where they are supposed to be.

<details>
<summary>Spaceport</summary>

Before:
![before1](https://github.com/user-attachments/assets/a8ec3f33-6ea2-4f7e-914d-d8b0a4a23cc3)

After:
![after1](https://github.com/user-attachments/assets/06adf469-d75d-45bf-b316-7d92e20974db)

</details>
<details>
<summary>Map</summary>

Before:
![before2](https://github.com/user-attachments/assets/3f87a200-88e5-424f-9224-e7a5af3c6fad)

After:
![after2](https://github.com/user-attachments/assets/b3dc4e70-980f-498d-a7f3-e6e3d92d23f1)

</details>

## Testing Done
Descriptions are shown and hidden correctly on panels that have them. Scrolling works.

## Wiki Update
N/A

## Performance Impact
minimal if any

2024-08-19 01:05 UTC, Koranir requested changes

2024-08-19 09:48 UTC, TomGoodIdea commented on source/MapPanel.cpp
> +		GetUI()->PopThrough(this);
> The destructor should already remove all child elements.

It doesn't.

2024-08-19 09:58 UTC, Koranir commented on source/MapDetailPanel.cpp
> +		}
Yep

2024-08-22 00:48 UTC, Koranir approved these changes

2024-08-22 07:36 UTC, tibetiroka reviewed
The code looks good, but the scroll indicator overlaps the text slightly.
![image](https://github.com/user-attachments/assets/4527d28e-278a-40ce-85fe-269bf87f2127)

I expect this to be a bigger issue if we get scroll bars.

2024-08-22 09:08 UTC, TomGoodIdea commented on source/MapPanel.cpp
> +		GetUI()->PopThrough(this);
oh, so Pop does work as well (but this makes me wonder why PopThrough was used in the original implementation of TextArea in Dialogs)

2024-08-22 09:14 UTC, TomGoodIdea commented
> the scroll indicator overlaps the text slightly.

This deserves its own bugfix PR as it affects all TextAreas.

2024-10-09 23:26 UTC, Koranir commented
Could you update to the latest master and see how this works with the new scrollbars? They should apply automatically to all `TextArea`s.

2024-10-10 08:48 UTC, TomGoodIdea commented
This is how it looks with a scrollbar:
![scroll](https://github.com/user-attachments/assets/28b76f8a-1242-4469-b218-fa18ab5e0677)

2024-10-10 12:26 UTC, tibetiroka commented
I think the padding should be adjusted a bit to make it centered between the left side and the scroll bar (if it's there).

2024-10-10 13:13 UTC, TomGoodIdea commented
wouldn't that require changes to all TextAreas?

2024-10-10 13:20 UTC, tibetiroka commented
If memory servers, this TextArea isn't the entire panel; it's offset to the right by a couple pixels for padding. If that's the case, we could just redistribute that padding to make it look more even.

2024-10-10 13:21 UTC, tibetiroka commented
(And if it's a change to all text areas, it should literally just be changing the offset of the text by a couple pixels, nothing too difficult.)

2025-02-06 09:12 UTC, Hurleveur reviewed
just a quick look, I didn't test this in game yet

2025-02-06 09:12 UTC, Hurleveur commented on source/MapPanel.cpp
> +	};
maybe explain what the "children" correspond to

2025-04-07 19:43 UTC, TomGoodIdea commented
Why is this waiting on OP?

2025-04-08 04:09 UTC, tibetiroka commented
I don't think my above comments have been addressed?

2025-04-08 04:55 UTC, TomGoodIdea commented
ok. waiting on #10612 then

2025-04-20 04:08 UTC, Amazinite commented
It sure do scroll now.

2025-04-20 04:13 UTC, Amazinite commented
For the record, I don't want this to be used as an excuse to make super long planet descriptions. This should really just be seen as something to give us a little extra space if for some reason we have a lot to say and it's just barely larger than the normal amount of space.

2025-04-20 04:15 UTC, merged