feat(mechanics): Mission "requires" allows standard Player Conditions
endless-sky/endless-sky pull request #10467
Opened 2024-09-16 18:00 UTC by SomeTroglodyte

**Feature**
(With minor **Content** tweaks requiring the code)

## Summary
Today while playing Hai Reveal I ran into the irksome ["Sayari won't accept Nanachi's pendant" message](https://github.com/endless-sky/endless-sky/blob/ab9a3dd4fc0e1e27f74f085af35a984dc0ac00f0/data/hai/hai%20reveal%204%20middle.txt#L1844), and subsequently fixed it.

Notes
* A comment in that mission indicates the mission author intended to allow other keystones but couldn't.
* The proposed mission change allows _any_ keystone including plugin ones, the alternative to allow only the ones "Hai Pilgrimage" recognizes has some merit too - doable using an `or` condition.
* Related to [#10191](https://github.com/endless-sky/endless-sky/issues/10191) and other issues I can't find at the moment - on one side the capability to check attributes in "to ..." branches already exists but is underused in content, on the other side this PR extends the capabilities of "on ..." branches.
* `mission "Remnant: Expanded Horizons Astral 2"` should perhaps check `"hyperjumps to system: <name>"` instead, in the unlikely case a plugin has jump drive with a *shorter* jump range that's not sufficient to reach SagA - but since that one states it's not wormhole-capable I refrained from testing that.

## Usage examples
Now
```
	on complete
		require
			has "outfit (flagship installed): Quantum Keystone"
```
is a valid alternative to
```
	on complete
		require "Quantum Keystone"
```
... But being full player conditions this now allows complex tests.

## Testing Done
Most of these changes have been in my codebase and thus been playtested extensively for months, additionally I tested this specific mission explicitly, checking that it now allows any key stone to succeed while still failing when I uninstall all pendant, skeleton and normal variants.

## Save File
Faked with the mighty xed, but enough to depart, land, get the mission (so it's copied from data and not included in my save), and play it - the Pendant is installed, the others are in storage:
[Sayari Meep~3013-11-16.txt.zip](https://github.com/user-attachments/files/17020173/Sayari.Meep.3013-11-16.txt.zip)

## Wiki Update
Yes, TBD - if the idea pleases. As I'm expecting objections I'll postpone the effort.

## Performance Impact
N/A

2024-09-16 18:43 UTC, TomGoodIdea commented on source/MissionAction.cpp
> +	}
You can merge this with the above `if`:
```
...
else if(key == "require")
{
	if(hasValue)
		require outfits...
	else if(child.HasChildren())
		require conditions...
}
```

2024-09-16 20:34 UTC, TomGoodIdea commented on source/MissionAction.cpp
> +	}
I still don't like it, but I guess it's acceptable then

2024-09-17 00:58 UTC, Amazinite requested changes
This seems unnecessary to me. Unless there's some mechanic that this provides us that can't be achieved currently (and I'm not able to think of any such thing), we should be replacing existing uses of the `require` node with autoconditions, not enhancing the node to do more than it does now.

2024-09-17 00:58 UTC, Amazinite commented on data/coalition/coalition missions.txt
> +			not "flagship attribute: jump drive"
I believe these are older missions that predate this "flagship attribute" autocondition. The `require` node has been effectively replaced with the ability to use autoconditions that check your outfits in the `to *` node. What mechanically do we actually gain by turning the `require` node into effectively another condition set check?

2024-09-17 02:10 UTC, Amazinite commented on data/coalition/coalition missions.txt
> +			not "flagship attribute: jump drive"
Yes. We have `to complete`, `to offer`, `to fail`, and `to accept`.

2024-09-17 23:04 UTC, closed without merging