fix(content): Lunarium/Heliarch jump tests
endless-sky/endless-sky pull request #10787
Opened 2024-11-13 20:21 UTC by SomeTroglodyte

## Summary

Changed a few Lunarium/Heliarch missions requiring a Jump Drive so they can be started with any plugin-provided outfit that provides jump capability.

## Testing Done
* Lunarium chain can be finished with no outfit named "Jump Drive" but jump capability from other source (which in master is blocked at mission "Lunarium: Questions")

Edit: Post rewritten to clarify the second commit has been reverted.

<details><summary>Original obsolete post</summary>
**Minor consistency update**

## Summary
The stats of the "Small Recovery Module" make no sense IMHO. They sound more like a simple mistake than intent.
* Since the "shield generation" to "hull repair rate" ratio of the outfit is exactly the same as from a Large Shield Module to a Large Repair Module, I projected the _efficiency_ ratio of the shield attributes to hull repair. 

While at it, it makes no sense the minimum license requirement **all other** coalition outfits have are missing from the Lunarium specific ones.

## Testing Done
* Stats of the "Small Recovery Module" look good in the outfitter (no exaggerated fractional digits)
* Lunarium chain can be finished with no outfit named "Jump Drive" but jump capability from other source (which in master is blocked at mission "Lunarium: Questions")
</details>

2024-11-13 22:32 UTC, Quantumshark commented
Yes, the ratio is indeed about the same. My point isn't about the ratio of shield gen to hull repair, nor is that what you're fixing here.

The other Coalition repairs use 1 energy per shield generated or per hull repaired. If this outfit did the same, it would have 0.97 shield energy and 0.43 hull energy. However, it instead has the reverse of that. So, clearly that would be the thing to fix - swapping those back - rather than adjusting only the hull energy based on the anomalous shield energy number.

2024-11-14 11:47 UTC, Arachi-Lover requested changes
The Lunarium is an outlaw organization, and the Coalition License is a Heliarch document at the end of the day. It doesn't make sense for their outfits to require Heliarch-approval to purchase.

As for the Small Recovery Module's stats, it was intentional that the shield and hull energy values were swapped, I just thought it'd be a gimmicky thing to make it a bit different from the other regen outfits of the Coalition.
If that's not desireable then I agree with Quantumshark in that just undoing the swap would be the better fix.

2024-11-14 11:47 UTC, Arachi-Lover commented on data/coalition/coalition outfits.txt
> +		Coalition
```suggestion
```

2024-11-14 11:47 UTC, Arachi-Lover commented on data/coalition/coalition outfits.txt
> +		Coalition
```suggestion
```

2024-11-14 11:47 UTC, Arachi-Lover commented on data/coalition/coalition outfits.txt
> +		Coalition
```suggestion
```

2024-11-14 11:47 UTC, Arachi-Lover commented on data/coalition/coalition outfits.txt
> +		Coalition
```suggestion
```

2024-11-14 11:59 UTC, Quantumshark commented
If it was intentional then that's alright, I don't think it makes the outfit unbalanced or anything.

2024-11-14 18:56 UTC, Quantumshark commented
>the Lunarium path rewards are less attractive than the Heliarch ones by such a ginormous margin, I think that needs some counterweight. 

Interesting, I've mostly heard people say the reverse. The general consensus seems to be that the Heliarch outfits that unlock so far are quite underwhelming, since all their good outfits are kept for future unlocks and are not yet available, while the Lunarium's refuelling modules and anti-materiel rifles are both considered to be very powerful outfits and worthwhile rewards.

2024-11-17 20:54 UTC, warp-core commented
I'm very confused by the title, description, and diff.
The descriptions appears to be about something entirely different to the changes in this PR, and it doesn't appear to contain much reference to what this PR actually does. The only part I see about it is the final line, which I cannot make sense on.
I gather from the conversation that the changes in the description have since been removed, but this doesn't explain why the remaining changes are almost never mentioned.

2024-11-22 06:07 UTC, mOctave reviewed
This seems like a good change for forwards-compatibility, but I wouldn't necessarily call it a bugfix since I don't think anything's broken right now by it (at least not in vanilla). You should probably update the description to match, too.

The `Remnant: Lost in Ember Waste` missions should also probably be changed if we do this.

2024-11-22 20:56 UTC, ziproot commented
This appears to be a regression, because if you have a ship that has a jump drive that is not your primary ship, you will now no longer be able to get the mission, even if you could switch to that ship before takeoff.

2024-11-24 20:24 UTC, ziproot commented
Lunarium Evacuation 5 needs a Jump Drive in order to reach the destination by the deadline.

As for Lunarium Questions, the Jump Drive is really needed for the subsequent mission, so the requirement should probably be moved there. This is especially important as you may wait to join the Lunarium, at which point you may have transferred your Jump Drive.

2025-02-20 22:36 UTC, Saugia commented
This will require testing before it is mergeable. If we can get a save a mission or two prior to these jump missions that would be great. 

Also, going to ping @Arachi-Lover on this - currently the missions check for the JD outfit on *any* ship in your fleet. This PR specifically changes it to flagship only. Does it make sense that you could possibly have a JD on an escort, but the mission only offers/the Coalition only talk about the mission if a JD is present on your flagship.

2025-03-08 05:20 UTC, TheGiraffe3 commented
@SomeTroglodyte could you resolve conflicts?

2025-03-15 05:41 UTC, TheGiraffe3 commented
@Arachi-Lover I believe this is waiting on you?

2025-03-17 23:34 UTC, Arachi-Lover commented
If I'm reading this right, now the missions would explicitly check only your *flagship* for a JD?

I think it'd still make sense for them to offer if any of your local escorts have a JD, as that could be easily verified by scanning. Currently I believe it offers if any of your ships that aren't parked have a JD, regardless of where they are?

Ideally would have it check if any of the player's ships within Coalition space have a JD, but pretty sure that sort of check is not yet possible in a clean way. Is it possible to have the missions check all ships within the system?

2025-03-30 04:15 UTC, Amazinite commented
We don't currently have an auto-condition for checking the attributes of ships aside from your flagship.

2025-04-16 18:51 UTC, Amazinite commented
Please make use of the newly merged conditions for this.

2025-04-19 16:46 UTC, Amazinite commented on data/coalition/heliarch intro.txt
> +		has "flagship attribute: jump drive"
```suggestion
		has "ship attribute: jump drive"
```

2025-04-19 16:46 UTC, Amazinite commented on data/coalition/lunarium intro.txt
> +		has "flagship attribute: jump drive"
```suggestion
		has "ship attribute: jump drive"
```

2025-04-19 16:46 UTC, Amazinite commented on data/coalition/lunarium intro.txt
> +		has "flagship attribute: jump drive"
```suggestion
		has "ship attribute: jump drive"
```

2025-04-19 16:46 UTC, Amazinite commented on data/coalition/lunarium intro.txt
> +		has "flagship attribute: jump drive"
```suggestion
		has "ship attribute: jump drive"
```

2025-04-20 03:34 UTC, merged