New implementation of the orders refactor
endless-sky/endless-sky pull request #10843
Opened 2024-12-07 19:32 UTC by TomGoodIdea

**Refactor**

This PR implements #10334 in a different (hopefully better) way.

## Summary
I'd leave re-adding the hold fire command for a separate PR, but here's some groundwork: the Great Orders Refactor.
Unlike in #10334, the `Orders` class is split into three separate classes: `OrderSingle` representing a single order (essentially the same as `AI::Orders` on master), `OrderSet` containing a combination of orders (currently it's not really needed, but is a requirement for hold fire), and `Orders` handling things common for both classes (ship/asteroid/location targets).
`OrderSet` is generally based on #10334, but the core mechanisms are different. Also I've decided to go with a single setter and getter for the bitset instead of having to write a separate pair for every order type.

## Testing Done
I've done some basic testing, but the more people test this, the better.

## Performance Impact
Minimal if any.

2024-12-07 19:56 UTC, TomGoodIdea commented
The style checker error in AI.cpp is a false positive.

2024-12-09 10:05 UTC, TomGoodIdea commented
AFAIK there's no official entry in the style guide for this ~~because the guide is outdated, and I'm waiting for the migration to be complete before suggesting any changes~~, but the de-facto rule is no space before braced variable constructors, and all current code follows it.

2024-12-13 08:42 UTC, tibetiroka commented
You could probably invert the condition of that ternary to get the error to go away.

2024-12-13 13:23 UTC, TomGoodIdea commented on source/AI.cpp
> +		: target->IsDisabled() ? Orders::FINISH_OFF : Orders::ATTACK};
```suggestion
	OrderSingle newOrder{isEnemy ?
		target->IsDisabled() ? Orders::FINISH_OFF : Orders::ATTACK
		: Orders::KEEP_STATION};
```

2025-01-18 20:06 UTC, tibetiroka commented
I played with this PR for a bit, and something about the gather order seems off. If I have ships in another system (with the HOLD order), then I GATHER them to my current system, they will jump in, but won't gather around my flagship like in continuous.

2025-01-19 21:11 UTC, TomGoodIdea commented
should work now

2025-04-14 05:55 UTC, Koranir requested changes

2025-04-14 05:55 UTC, Koranir commented on source/engine/Orders.h
> +	enum Types {
```suggestion
	enum class Types : int {
```
This should be an `enum class` so it doesn't pollute any namespaces.

2025-04-14 06:20 UTC, TomGoodIdea commented on source/engine/Orders.h
> +	enum Types {
Doesn't it already require to use the Orders namespace outside the order classes?

2025-04-14 06:45 UTC, Koranir commented on source/engine/Orders.h
> +	enum Types {
Yes, but the style guide is to use enum classes by default.

2025-04-14 06:58 UTC, TomGoodIdea commented on source/engine/Orders.h
> +	enum Types {
In general, yes (and it should probably be added to the written version of the guide after the migration). In this case, the enum is a core part of the class, and I wouldn't call it pollution, but code simplification ~~and you're the one who uses auto for everything smh~~.
That said, I'm fine with changing it if you still think it would be better.

2025-04-14 08:36 UTC, Koranir commented on source/engine/Orders.h
> +	enum Types {
Hmm
I think I managed to confuse myself with how many similar names were flying around in this diff, you're right.

2025-04-29 13:25 UTC, petervdmeer commented
I hope that we can have active escorts controlled by [state-machines](https://github.com/endless-sky/endless-sky/issues/10042) at some point in the future. Something along the lines of:

**Movement control**
```mermaid
stateDiagram-v2
  [*] --> MOVE_TO_GATHER
  MOVE_TO_GATHER --> HOLD_GATHER: near_target
  HOLD_GATHER --> MOVE_TO_GATHER: !near_target

  HOLD_GATHER --> MOVE_TO_POSITION: hold_position_order
  MOVE_TO_GATHER --> MOVE_TO_POSITION: hold_position_order 
  
  MOVE_TO_POSITION --> HOLD_POSITION: in_position 
  HOLD_POSITION --> MOVE_TO_POSITION: !in_position
  
  MOVE_TO_POSITION --> MOVE_TO_GATHER: gather_order 
  HOLD_POSITION --> MOVE_TO_GATHER: gather_order

  MOVE_TO_TARGET --> MOVE_TO_GATHER: target_lost
  HOLD_GATHER --> MOVE_TO_TARGET: attack_order
  MOVE_TO_GATHER --> MOVE_TO_TARGET: attack_order
  MOVE_TO_POSITION --> MOVE_TO_TARGET: attack_order
  HOLD_POSITION --> MOVE_TO_TARGET: attack_order
```


**Fire controls**
```mermaid
stateDiagram-v2
  [*] --> DEFENSIVE_FIRE
  DEFENSIVE_FIRE --> HOLD_FIRE: hold_fire_order
  HOLD_FIRE --> DEFENSIVE_FIRE: cancel_fire_orders/target_lost
  HOLD_FIRE --> ATTACK_TO_DISABLE: attack_order
  DEFENSIVE_FIRE --> ATTACK_TO_DISABLE: attack_order
  ATTACK_TO_DISABLE --> ATTACK_FINISH_OFF: attack_order
  ATTACK_TO_DISABLE --> DEFENSIVE_FIRE: cancel_fire_orders/target_lost
  ATTACK_FINISH_OFF --> DEFENSIVE_FIRE: cancel_fire_orders/target_lost
  ATTACK_TO_DISABLE --> HOLD_FIRE: hold_fire_order
  ATTACK_FINISH_OFF --> HOLD_FIRE: hold_fire_order
```

I don't mind to have a PR today that improves on the Order states, but if we go in the direction of statemachines, then I expect Orders not to be stored as part of "state", but I expect them to be "state transitions" in the statemachines.

2025-04-29 13:30 UTC, TomGoodIdea commented
This PR is needed for hold fire, so I'd rather not add more refactors than necessary for now.

2025-04-29 18:21 UTC, petervdmeer commented
> This PR is needed for hold fire, so I'd rather not add more refactors than necessary for now.

I understand, and as I said: "I don't mind to have a PR today that improves on the Order states."

The reason I brought this up is that this PR is 529 lines of code, and it does some cool magic with bitsets and avoidance of simultaneous orders. Reviewing this PR will also take some effort, and effort spend on this PR is effort not spent elsewhere.

If this PR solves a problem now (and doesn't produce any problems on it's own), then it makes sense to proceed with it, so don't let my remarks discourage you from proceeding with this PR.

2025-07-27 07:25 UTC, tibetiroka commented on source/engine/Orders.h
> +	enum Types {
The main difference is that enum classes don't have implicit conversions from/to their underlying type. This is really helpful, because otherwise any int (or bool, or anything numeric) could be used to call a function accepting a Types instance. It's good practice to use enum classes so we get compiler errors when such accidents happen.

2025-07-27 07:28 UTC, tibetiroka commented on source/engine/OrderSet.cpp
> +	constexpr array<bitset<Orders::TYPES_COUNT>, Orders::TYPES_COUNT> SIMULTANEOUS{{
What's wrong with the default constructor? Also, this never stores any data?

2025-07-27 07:30 UTC, tibetiroka commented on source/engine/OrderSet.cpp
> +	types &= SIMULTANEOUS[type];
Right now, not needed. This should be in the hold fire code.

2025-07-27 07:42 UTC, tibetiroka commented on source/engine/OrderSet.cpp
> +		targetAsteroidInvalid = false;
```suggestion
	bool targetShipInvalid = false;
	bool targetAsteroidInvalid = false;
```

2025-07-27 07:47 UTC, tibetiroka commented on source/engine/OrderSet.cpp
> +		Set(HOLD_POSITION);
Why is this code located here? Based on the comment, it should be checking either the new order, or the state of this set at the end. Otherwise, this just relies on multiple orders being given to maintain consistency.

2025-07-27 07:52 UTC, tibetiroka commented on source/AI.cpp
> +		orders[ship].Set(Orders::GATHER);
Could this use Add() instead of Set()?

2025-07-27 07:59 UTC, tibetiroka commented on source/engine/OrderSet.h
> +	void Set(Types type) noexcept;
This is only used once in AI.cpp, and I don't think that use is necessary. If so, you could move this out of the public interface. (I think that would be better, as Set() bypasses the checks in Add(), so we could break orders by calling Set() instead of Add() with certain orders.)

2025-08-16 19:35 UTC, merged