Content: Creating Person for BeccaBunny
endless-sky/endless-sky pull request #5306
Opened 2020-09-09 16:35 UTC by Zitchas

**Content (Artwork / Missions / Jobs)**

## Summary
This PR creates the person "Prototype B3-CC4", flying a "Shooting Star" ship reminiscent of EVN's Krypt Pod.

## PR Checklist
 - [X] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [X] I uploaded the necessary image, blend, and texture assets here: [google drive zip file](https://drive.google.com/file/d/1h_77m1kj0taUPi9C2kLako64OzRa4BS8/view?usp=sharing)
 - [ ] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: {{insert PR link}}

2020-09-09 17:23 UTC, beccabunny commented on data/remnant/remnant persons.txt
> +	description "This ship appears to be a hollowed-out asteroid filled with strange equipment. It is unclear what is creating the rays of light, but they clearly have something to do with how it moves
```suggestion
	description "This ship appears to be a hollowed-out asteroid filled with strange equipment. It is unclear what is creating the rays of light, but they must have something to do with how it moves without obvious engines."
```
a derivation of "clear" was used twice very closely

2020-09-09 19:37 UTC, beccabunny approved these changes
It is worth noting that this person also uses 4 new outfits, which are also necessary given that the game weapons have hardpoints which wouldn't work here. It looks good to me, so I'm approving

2020-09-15 01:00 UTC, Amazinite requested changes
Why a separate file? This should just be in the existing person ships file.

2020-09-15 01:00 UTC, Amazinite commented on data/remnant/remnant persons.txt
> +			"Even for a floating gathering of debris"
This line doesn't really make sense to me with the potential follow-ups.
"Even for a floating gathering of debris you shouldn't buy anything the Syndicate sells."
Both these first two lines could use something a little extra to make them work out, really.
```suggestion
			"I may be just a piece of rock, but I know that"
			"Even for a floating gathering of debris I know that"
```

2020-09-15 01:29 UTC, Zitchas commented on data/remnant/remnant persons.txt
> +	sprite "ship/shooting star/shootingstar"
OK. Will do when I'm on desktop again.

2020-09-15 14:17 UTC, Zitchas commented on data/remnant/remnant persons.txt
> +	sprite "ship/shooting star/shootingstar"
Changed the sprite names.

2020-09-15 14:18 UTC, Zitchas commented on data/remnant/remnant persons.txt
> +	description "The beam projector of the Shooting Star, without it the flares would appear in the ship outline."
Descriptions removed.

2020-09-15 14:41 UTC, Zitchas commented
Have B3-CC4 by themselves here doesn't make a ton of sense, admittedly. Next content (as in non-fix) PR is hopefully going to be my person, which, given previously discussed plans, makes more sense to have separate since it'll be a bit more variable. So I thought if I'm already considering having it separate for ease of dealing with it, it kind of makes sense to keep B3-CC4 in the same place, since B3-CC4 is also restricted to the Ember Waste.

The restriction is due to the fact that I've actually got some story planned with B3-CC4, which BeccaBunny liked the sounds of. 

The very bare-bones version is:
 - Remove the person ship from active use.
- Have the player find a disabled human ship in the Ember Waste. 
- Board it, and find a delusional Italian with a funny conversation. (Becca and I have worked out one or two elements of this)
- Bring the delusional Italian back to the Remnant, they take care of said person.
- Later find out that the person has recovered, and would much prefer to stay with the Remnant.
- Becomes an apprentice designer with Taely and use an event to add this person ship into active appearance.

Until the missions are actually added, though (probably a 0.9.15 thing), just having the person exist like this, which is what the end-state would be after the missions are done.

2020-09-15 14:44 UTC, Amazinite commented
> Until the missions are actually added, though (probably a 0.9.15 thing), just having the person exist like this, which is what the end-state would be after the missions are done.

Problem with that is that I'm pretty sure you can't generate person ships through events. And as far as your person ship goes, I'd still want the person definition to be in the person file (regardless if where person ships might fit into any story anywhere), and you can put the ship definitions in the Remnant ships file since that's where they'd ultimately end up otherwise.

2020-09-15 14:52 UTC, Zitchas commented
Re: Person in events: OK, well, maybe won't be able to do that part, then. Still planning/hoping to do the missions, though. Can events change the frequency or anything else to do with persons? Just changing the frequency from some massive number down to something reasonable could work too. Although that might influence the probabilities for everyone else, so might not do anything at all.

And the content has been moved into the persons.txt file.

2020-09-16 03:13 UTC, Amazinite approved these changes
The 2x PR needs updated.

2020-09-16 03:43 UTC, Zitchas commented
It was just the name change from shootingstar to shooting star (and associated copyright file update), right? If so, that's done now.

2020-09-16 14:59 UTC, Zitchas commented
Fixed the 2x ship and flare images, and uploaded a new (_v2) zip file on the google drive, so there's a new file link in the first post.

2020-09-16 15:01 UTC, merged