feat(mechanics): Save collections in order by element name
endless-sky/endless-sky pull request #5333
Opened 2020-09-13 19:04 UTC by tehhowch

**Feature:** This PR implements the feature request detailed and discussed in issue #5171 
closes #5324 

## Feature Details
Where parts of the player's save were not deterministically ordered, they now are. A template method, and a specialization for uses of std::map for a pointer type key, are used to create a vector of pointers to the collection elements, which is then sorted and iterated.

To avoid future code from manipulating DataWriters incorrectly, deletes the copy & move constructors / operators for it.

## UI Screenshots
n/a''

## Usage Examples
n/a

## Testing Done
Saved & loaded & saved again a couple times

## Performance Impact
n/a

2020-09-13 20:25 UTC, petervdmeer approved these changes
Wow, this looks quite generic indeed. Good change!
(I have 2 minor remarks, but they are not blocking for merging this.)

2020-09-13 20:25 UTC, petervdmeer commented on source/Ship.cpp
> +				[&out](const pair<const Outfit *, int> &it){
Is it possible to use OutfitElement here as well instead of the pair(Outfit, int>?

2020-09-13 20:25 UTC, petervdmeer commented on source/Ship.cpp
> +		{
The code `if(it.first && it.second)` on line 809/807 suggests that `it.first` might be a null-pointer, but it looks like the check on `it.first` on line 809/807 itself is not actually needed).

2020-09-13 22:53 UTC, Amazinite requested changes
Still trying to wrap my head around this. I vaguely understand what is going on (we have a generic WriteSorted function that takes in a container of some type as well as two functions that define how to sort the container then write the sorted container, then each point where we need to write something sorted we create the functions that correspond to how we want to sort and write), but I still want to nail down my understanding on the syntax used. (I know these... things... have popped up in the past, so it seems like something worth learning about when basically this entire PR is built around using lambda expressions.) I'm sure everything works as is, though. The only comments I can really give right now are on formatting.

2020-09-13 22:53 UTC, Amazinite commented on source/GameData.cpp
> +			using Purchase = pair<const System * const, map<string, int>>;
Other places where you've done this don't have the space here.
```suggestion
			using Purchase = pair<const System *const, map<string, int>>;
```

2020-09-13 22:53 UTC, Amazinite commented on source/GameData.cpp
> +				[](const Purchase *lhs, const Purchase *rhs) { return lhs->first->Name() < rhs->first->Name();},
```suggestion
				[](const Purchase *lhs, const Purchase *rhs) { return lhs->first->Name() < rhs->first->Name(); },
```

2020-09-13 22:53 UTC, Amazinite commented on source/Depreciation.cpp
> +			[](const ShipElement *lhs, const ShipElement *rhs) { return lhs->first->ModelName() < rhs->first->ModelName(); },
Should we spread these functions out on multiple lines for readability? It's not as if we only have so many lines to go around.
```suggestion
			[](const ShipElement *lhs, const ShipElement *rhs)
			{
				return lhs->first->ModelName() < rhs->first->ModelName(); 
			},
```

2020-09-16 13:29 UTC, Amazinite approved these changes
Thank you cd_macos_x86_64, very cool.

2020-09-16 13:35 UTC, merged