Fix: Conversation branch condition in "Remnant: Face to Maw 2"
endless-sky/endless-sky pull request #5390
Opened 2020-09-30 20:08 UTC by Ornok

Changed branch condition `"remnant met taely" > 1` to `"remnant met taely" >= 1` so that Taely doesn't introduce herself again in "Face to Maw 2" if the player met her once before (e.g. by accepting "Tech Retrieval" without completing it).

2020-09-30 22:47 UTC, Amazinite commented
Really, any branches like these should be using `has "remnant met taely"`. And also `has "remnant chilia"` for lines 2323, 2905

2020-09-30 23:45 UTC, Amazinite requested changes
Use `has <condition>` instead of `<condition> >= 1` and fix the other similar errors in this file.

2020-10-01 07:41 UTC, Ornok commented
Such conditions are also used in intro log missions ("Remnant: taely intro log" line 1362 and "Remnant: Chilia Intro Log" line 1374). Should we do the same with those?

2020-10-01 22:55 UTC, Amazinite commented
Those ones are fine since there are multiple log missions, and the use of `>= x` makes it explicit that "this one requires X encounters, this one requires X+1 encounters" and so on.

2020-10-01 22:55 UTC, merged