Fix: Improved reverse thruster behavior for landing
endless-sky/endless-sky pull request #5564
Opened 2020-12-18 21:31 UTC by Terin

**Bugfix:** This PR addresses issue #5520.

## Fix Details
Thanks to the work of Vitalchip, whose work I'm uploading at this PR at their request. For the original issue:

> What seems to be happening is that on a normal approach the ship reaches the calculated stopping point, cuts thrust and passes the point. This makes the ship turn to face the point and then it decelerates using main engines. When there are reverse thrusters they fire, and instead of smoothly passing the stopping point it gets recalculated due to a decrease in velocity, putting it out in front again. The ship moves forward again to intercept and depending on the magnitude of the reverse thrust they may or may not fire again. This behaviour can also happen right before landing causing the ship to 'slide' sideways under reverse thrust, because its (say) pointing left to intercept the stopping point but firing reverse thrusters will cause it to slow but move right.

For the fix:

> Reverse landings can be improved a bit with a quick code change but they're still slower than a regular landing under most circumstances as the only way I've been able to keep the landing reliable is where forward and reverse thrusters alternate. Anything else I tried just ended up off target at the end and 'circling the drain' to land.

And the final implementation:

> This is the change I made, it just points the ship at its own velocity when reversing, countering drift and stopping the turn around.

## Testing Done
Attempted landing on various objects (planets, wormholes, disabled ships) with the patch, with ships that had a variety of reverse thrusters (Penguin, Arfecta, Emerald Sword), and noticed much smoother landing sequences. For a large ship like the Emerald Sword, it may exhibit a "ratcheting" behavior if coming at the target from an angle, but is still faster than the old behavior. Also appropriately works if the ship has weak reverse thrusters, as it will prioritize the quicker turning and forward thrust.

## Performance Impact
No significant change in CPU utilization when attempting to travel with 500 Penguins through a wormhole.

2020-12-18 21:59 UTC, Amazinite commented
How does this affect boarding, jumping, the hold position escort command, the shift+down hold command for the flagship?

2020-12-19 16:54 UTC, Terin commented
Jumping, holding position, and shift+down appear to behave identically. However, boarding/move commands to close-range targets with slow ships may be a regression, as the ratcheting behavior I described gets exacerbated trying to hit that smaller target. I'm going to temporarily close this PR to do some video testing of each, so we can see side-by-side.

2020-12-28 06:24 UTC, Terin commented
Vitalchip increased the angle for MoveTo() from 80% to 95%, which greatly improves the worst-case scenario from before, while providing no significant regressions. While it may be marginally slower in a few cases, the noticeable speed increase over the current implementation in the worst case, plus the much better landing movement makes it ready to merge, in my opinion.

2020-12-29 05:07 UTC, Amazinite commented on source/AI.cpp
>  	if(!isClose || !isFacing)
When the `if(should reverse...)` bit was added above, this line was changed from `if(!isClose || (!isFacing && !shouldReverse))` to what it is now. Should this line be changed back to what it was?

2021-01-01 01:32 UTC, Amazinite requested changes

2021-01-01 01:32 UTC, Amazinite commented on source/AI.cpp
>  	if(!isClose || !isFacing)
Yeah, I think this needs readded, as otherwise you could do a command.SetTurn here and down on line 1776.

2021-01-02 03:12 UTC, Amazinite approved these changes

2021-01-02 03:13 UTC, merged