Experimental web build CD GitHub action
endless-sky/endless-sky pull request #5593
Opened 2021-01-01 00:31 UTC by thomasballinger

## Summary
Adds an a GitHub workflow for a web build. This is accomplished by merging some changes from https://github.com/thomasballinger/endless-sky/tree/es-wasm-reformatted then building with Emscripten.

I'd like to automatically deploy this somewhere, but being able to download a web build is a start.

Relying on cleanly merging code not stored in the repo isn't great for a CI workflow: it allows someone else (me in this case) to modify the executable arbitrarily. Since this only produces a webpage, which runs in the browser sandboxed environment, maybe it's ok.

To run, download the `endless-sky-web-continuous` artifact, unzip, untar, then run `python3 -m server.http` from the unpacked directory and visit localhost:8000 in a web browser.

## Testing Done
It worked once!

## Performance Impact
This workflow takes ~10 minutes. It doesn't block the `cd_upload_artifacts_to_release` workflow so this shouldn't slow anything down, but if increases the GitHub Actions minutes used per PR update.

2021-01-01 00:58 UTC, thomasballinger commented
![image](https://user-images.githubusercontent.com/458879/103431701-50046480-4b89-11eb-94e6-1353c8be1c02.png)

2021-01-01 11:05 UTC, MCOfficer requested changes
Oof. While i love your project, this PR crosses the line imo.

a) It puts the weight of maintaining this workflow on the main project.

b) It distributes an *unofficial* patch on the *official* release page.

Even if this was properly documented on the release page, that would be a no-go for me.

2021-01-01 14:02 UTC, thomasballinger commented
Both points absolutely make sense. I'd like to work toward a tool that gives devs a url of a PR build and it felt convenient to try out using a GitHub Actions workflow for it; but I can see how pulling in unofficial code is a dealbreaker.

I was thinking about a web hook maybe, how would you feel about adding a workflow that hits a web hook on push that would cause a build to be created somewhere else?

Re maintenance, thanks for your and @tehhowch's feedback on the PRs that will make these patches lighter; I was excited to see that this works, and if enough of those changes get upstreamed then someday the project will want to take that maintenance on; I'll bring it up again next Christmas break (:

2021-01-01 14:52 UTC, MCOfficer commented
> I was thinking about a web hook maybe, how would you feel about adding a workflow that hits a web hook on push that would cause a build to be created somewhere else?

I'd be fine with it, pending the opinion of actual maintainers of course. Also i'm not 100% sure if builds can actually triggered by webhooks.

2021-01-01 15:01 UTC, thomasballinger commented
> Also i'm not 100% sure if builds can actually triggered by webhooks.

Yeah, I was imagining I wouldn't be able to do it on GitHub infrastructure without the CI job being in this repo, so maybe a webhook that hits Netfify or some other service that would actually do the build, which might comment on the PR with a link (or however GitHub actions add notes to PRs that don't email everyone).

2021-01-12 14:23 UTC, tehhowch commented
Closing this, since it won't be merged

2021-01-12 14:23 UTC, closed without merging