Add some more spaceport messages.
endless-sky/endless-sky pull request #5675
Opened 2021-01-29 19:13 UTC by petervdmeer

**Content (New human spaceport messages)**

## Summary
Added some more new human spaceport news messages. I already PRed #5674, so sending in a new PR with some more messages that I came up with. (If both PRs stay in review for a long time, then I will probably combine them.)

## Save File
N/A

## PR Checklist
N/A

2021-01-29 20:22 UTC, Terin requested changes

2021-01-29 20:22 UTC, Terin commented on data/human/news.txt
> +			"Hey, you are so beautifull, do you want to marry me? Haha, just kidding, I'm rehearsing for my new role."
```suggestion
			"Hey, you are so beautiful, do you want to marry me? Haha, just kidding, I'm rehearsing for my new role."
```

2021-01-29 20:22 UTC, Terin commented on data/human/news.txt
> +			"I would love to tell you about my job, but just telling you I work for the Syndicate probably already violates the non-disclosure agremeement I signed."
```suggestion
			"I would love to tell you about my job, but just telling you I work for the Syndicate probably already violates the non-disclosure agreement I signed."
```

2021-01-29 20:22 UTC, Terin commented on data/human/news.txt
> +			"Don't count on the navy to save you if me or any of my friends attack you. Those Navy goons only hang around near the rich planets."
```suggestion
			"Don't count on the Navy to save you if me or any of my friends attack you. Those Navy goons only hang around near the rich planets."
```

2021-01-30 03:40 UTC, Amazinite requested changes
Stuff like this is small enough that you should just bundle it into an existing PR on the same topic.

2021-01-30 03:40 UTC, Amazinite commented on data/human/news.txt
> +			"Hey, you are so beautiful, do you want to marry me? Haha, just kidding, I'm rehearsing for my new role."
👉 👈 
Unless...

2021-01-30 03:40 UTC, Amazinite commented on data/human/news.txt
> +			"Your credits or your life!! Oh you don't have either? Never mind then."
```suggestion
			"Your credits or your life! Oh you don't have either? Never mind then."
```

2021-01-30 13:32 UTC, petervdmeer commented
Will merge the content with #5674

2021-01-30 13:32 UTC, closed without merging