Cargo / passengers are no longer transported to player on save load
endless-sky/endless-sky pull request #5723
Opened 2021-02-15 18:36 UTC by tatami4

**Bugfix:** This PR addresses issue #1624.
This is a simplified and corrected version of #5070.

## Fix Details
This fix generates UUIDs for missions and ships and then uses it to store in which ships mission cargo / passengers currently are.

## Testing Done
Same as in #5070.

## Save File
[John Brown.txt](https://github.com/endless-sky/endless-sky/files/5983468/John.Brown.txt)

Steps to verify:
1. load the game
2. the passenger mission does not complete until you depart, wait for escorts to arrive and land again (without this patch the mission will complete as soon as the save is loaded)

2021-07-29 13:48 UTC, tehhowch commented
@tatami4 please redo this PR using the game's UUID implementation

2021-07-30 10:28 UTC, tatami4 commented
> @tatami4 please redo this PR using the game's UUID implementation

Done, it should work the same as before.

2021-07-30 12:15 UTC, tehhowch requested changes
An alternate approach to the one taken currently would be to save the mission's cargo distribution information in the mission itself, or perhaps in the player object. It's possible these approaches would improve things, but also possible that they are worse in some ways, too. Would you like to investigate alternative approaches? Separate branches would be fine.

One additional issue with the proposed solution is that it assumes mission cargo can only be on player ships. The game at one point allowed random ships to plunder passengers, and I'm sure someone would love to be able to create a mission where the player has to plunder an NPC and actually take an item. I think that may only be possible if we store the cargo mapping in each mission (and promote any random NPCs which steal mission cargo into mission-associated ships), but I could be wrong. (I'm definitely not asking for all of that to be added in this PR.)

2021-07-30 14:15 UTC, tatami4 commented on source/PlayerInfo.cpp
> +				cargo.AddMissionCargo(&missions.back());
Yes, this isn't good, but I can't think of a way to store cargo and passenger distribution in a way that would be compatible with current saves. There is no way to infer cargo and passenger distribution from current save format.

2022-10-18 21:16 UTC, warp-core commented
Was the possibility of recording the distribution of mission cargo/passengers by system or ship UUID in the mission considered?
That seems like it'd be better than this.

2022-11-13 21:30 UTC, Amazinite commented
Closing in favor of #7505.

2022-11-13 21:30 UTC, closed without merging