Added new sounds for asteroid explosions
endless-sky/endless-sky pull request #5905
Opened 2021-04-27 20:43 UTC by Floppa-Priest

## Summary

I added three new sounds for small, medium and large asteroid explosions.

harvesting.txt, effects.txt and copyright have all been updated as well.
## PR Checklist
 - [ ] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [ ] I uploaded the necessary image, blend, and texture assets here: {{insert link to assets}}
 - [ ] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: {{insert PR link}}

2021-04-27 20:46 UTC, Floppa-Priest commented
Before this gets approved, can someone check to make sure I got my copyright additions correct?

2021-04-27 21:01 UTC, Amazinite requested changes
The copyright looks good to me.

2021-04-27 21:01 UTC, Amazinite commented on data/effects.txt
> +	sound "asteroid crunch large"
```suggestion
	sound "asteroid crunch large"
	
```

2021-04-27 21:05 UTC, Floppa-Priest commented on data/effects.txt
> +	sound "asteroid crunch large"
Good catch

2021-04-27 21:52 UTC, Amazinite approved these changes

2021-04-28 04:59 UTC, Amazinite commented
Sounds good to me.

2021-04-28 05:01 UTC, merged