Update hai missions.txt
endless-sky/endless-sky pull request #5911
Opened 2021-04-28 21:18 UTC by jarekchr

typos

NOTICE: Delete the sections that do not apply to your PR, and fill out the section that does.
(You can open a PR to add or improve a section, if you find them lacking!) 

----------------------
**Content (Artwork / Missions / Jobs)**

## Summary
{{summarize your content! Include links to related issues, in-game screenshots, etc.}}

## Save File
This save file can be used to play through the new mission content:
{{attach a save file that allows people to easily test your added mission content or see your new in-game art}}

## PR Checklist
 - [ ] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [ ] I uploaded the necessary image, blend, and texture assets here: {{insert link to assets}}
 - [ ] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: {{insert PR link}}
  
  
-----------------------
**Bugfix:** This PR addresses issue #{{insert number}}

## Fix Details
{{add details}}

## Testing Done
{{describe how you tested that the fix doesn't introduce other issues}}

## Save File
This save file can be used to verify the bugfix. The bug will occur when using {{insert commit hash / version}}, and will not occur when using this branch's build.
{{attach a save file that can be used to verify your bugfix. It MUST have no plugin requirements}}

-----------------------
**Feature:** This PR implements the feature request detailed and discussed in issue #{{insert number}}

## Feature Details
{{add details about the feature you implemented}}

## UI Screenshots
{{attach before + after screenshots of any changes to UI, or replace this line with "N/A"}}

## Usage Examples
{{if this feature is used in the data files, provide examples!}}

## Testing Done
{{describe how you tested the new feature}}

## Performance Impact
{{describe any performance impact (positive or negative). "N/A" if no performance-critical code is changed. }}

2021-05-01 19:19 UTC, roadrunner56 requested changes

2021-05-01 19:19 UTC, roadrunner56 commented on data/hai/hai missions.txt
> +			`You need not have worried about the reception the Unfettered youth would receive here on Hai-home. Scarcely minutes after you hesitantly contact the Hai government, a happy crowd has gathered aro
The apostrophe is not necessary here, as the word is not possessive.
```suggestion
			`You need not have worried about the reception the Unfettered youth would receive here on Hai-home. Scarcely minutes after you hesitantly contact the Hai government, a happy crowd has gathered around your ship. When he steps out of the hatchway, he looks stunned at being welcomed so warmly. One of the Hai governors thanks you for transporting him, and pays you <payment>.`
```

2021-05-05 13:47 UTC, Zitchas reviewed
The spelling mistake corrections definitely look like good fixes to me. Good catch!

Someone else better versed in punctuation rules will need to check the various comma additions & deletions, though.

2021-05-05 14:35 UTC, roadrunner56 approved these changes

2021-05-05 16:45 UTC, Amazinite commented
The two typo fixes look fine, but most if not all the changes to commas seem unnecessary. Relevant: https://github.com/endless-sky/endless-sky/pull/1190#issuecomment-223756706

2021-05-05 21:22 UTC, jarekchr commented
You may be correct on my changes to commas as it seems the rule is to put it for example before "but" if there're 2 different clauses.
"You should put a comma before but only when but is connecting two independent clauses."

Reading again if the subject of the sentence is added to the 2nd clause (it's missing there) then my changes are incorrect.

2021-05-06 12:36 UTC, EjoThims commented
Comma changes are indeed all correct, but some of them are pretty awkward sentences that might best be reworked entirely.

For several of them, this awkwardness is likely the origin of the bad comma placement in the first place.

2021-05-07 20:07 UTC, jarekchr commented
I (or you) can remove all comma changes that I've made. Looking more deeply into other files and dialogues I think that there can be many such changes - perhaps you should consider this as some future item.

2021-05-07 22:11 UTC, closed without merging

2021-05-07 22:12 UTC, Amazinite commented
Well I was in the Hai file fixing something else so I decided to just pull in the typo changes from here instead of stripping out the comma changes.
If you think there are oddly worded sentences then you should suggest changes to them.