More brig/wanderer jobs
endless-sky/endless-sky pull request #6044
Opened 2021-06-06 06:48 UTC by unjown

**Content (Artwork / Missions / Jobs)**
Transport captured unfettered spies

## Summary
I added a brig / wanderer job, since there are lack of  jobs that require brig

## PR Checklist
 - [X] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [ ] I uploaded the necessary image, blend, and texture assets here: {{insert link to assets}}
 - [ ] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: {{insert PR link}}

2021-06-06 14:59 UTC, EjoThims commented
May be best to just go with "prisoners" outright. Wanderers seem like the type to rescue prisoners from ships when they can, but Unfettered don't really seem like the spying type, and they wouldn't be especially needed in this particular conflict either. Especially in the bulk enough to generate repeating jobs.

2021-06-07 15:08 UTC, roadrunner56 requested changes
I really like this PR, we need more variety in Wanderer space.

2021-06-07 15:08 UTC, roadrunner56 commented on data/wanderer/wanderer jobs.txt
> +		dialog "You wish the Wanderers the best of luck on <planet> and collect your payment of <payment>."
You're not carrying Wanderers, so this line makes no sense.
```suggestion
		dialog "Once you land on <planet>, you watch as some Wanderers in uniform carry the Unfettered prisoners off of your ship. You collect your payment of <payment>."
```

2021-06-08 15:00 UTC, roadrunner56 approved these changes

2021-06-11 15:17 UTC, roadrunner56 requested changes
I overlooked what I believe to be syntax errors in your code, that result in some github tests not passing. I'm admittedly not super experienced with ES mission syntax, so if someone else could double-check what I'm doing, that would be great.

2021-06-11 15:17 UTC, roadrunner56 commented on data/wanderer/wanderer jobs.txt
> +		government "Wanderer"
```suggestion
	source
		government "Wanderer"
```

2021-06-11 15:17 UTC, roadrunner56 commented on data/wanderer/wanderer jobs.txt
> +	description "Transport <bunks> captured Unfettered soldiers to <planet>, payment is <payment>"
```suggestion
	description "Transport <bunks> captured Unfettered soldiers to <planet>, payment is <payment>"
	to offer
		has "language: Wanderer"
		random < 20
```

2021-06-15 00:19 UTC, roadrunner56 approved these changes

2021-06-23 10:36 UTC, Galaucus commented
This PR appears to be redundant with #6083.

2021-06-24 07:46 UTC, closed without merging