WIP: Medical facility
endless-sky/endless-sky pull request #6079
Opened 2021-06-17 08:56 UTC by unjown

**Content (Artwork / Missions / Jobs)**

Medical facility missions (will be adding more)
Medical facility outfit 

## Summary
I have added a new outfit medical facility mainly used for missions

## PR Checklist
 - [X] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [ ] I uploaded the necessary image, blend, and texture assets here: {{insert link to assets}}
 - [ ] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: {{insert PR link}}
  
  
-----------------------
**Feature:** This PR implements the feature request detailed and discussed in issue #{{6066}}

## Feature Details
I have added a new outfit the medical facility mainly for missions for now

## Testing Done
N/A yet

PS: help needed in making the outfit image thx

2021-07-12 23:27 UTC, Pointedstick requested changes
Consider adding a maximum distance and other relevant filters.

2021-07-12 23:27 UTC, Pointedstick commented on data/human/near earth jobs.txt
> +		dialog `Your passenger's personal nurse thanks you for transporting him`
```suggestion
		dialog `Your passenger's nurse thanks you for transporting them and hands you your payment of <payment>.`
```

2021-07-12 23:27 UTC, Pointedstick commented on data/human/near earth jobs.txt
> +	description `Transfer a patient with his personal nurse to <destination> for better medical care. Payment is <payment>`
```suggestion
	description `Transfer a patient with their personal nurse to <destination> for better medical care. Payment is <payment>`
```

2021-07-12 23:27 UTC, Pointedstick commented on data/human/outfits.txt
> +	description ""
Needs a description, obvs :)

2021-07-14 01:39 UTC, MasterOfGrey commented
Have you considered the possibility of a Major Medical Facility that could give you missions to respond to humanitarian crises'?

2021-09-12 14:31 UTC, Pointedstick commented
No response to requested changes and PR is in an early alpha state; closing for now to un-clutter the open PR list. @unjown, we can re-open this if you would like to resume work on it.

2021-09-12 14:31 UTC, closed without merging