feat: Add ability to fire all secondary weapons
endless-sky/endless-sky pull request #6085
Opened 2021-06-24 18:11 UTC by petervdmeer

**Feature:** This PR implements a feature related to this [comment](https://github.com/endless-sky/endless-sky/issues/1724#issuecomment-254778984)

## Feature Details
This PR replaces the "no secondary weapon selected" option by an "all secondary weapons selected" option. I feel that the option to select all secondary weapons and the ability to fire them all at once will be considered valuable, while I don't really see much use for having no secondary weapon selected.

## UI Screenshots
Screenshot of all weapons selected:
![all_weapons_selected](https://user-images.githubusercontent.com/35403542/123311474-84008700-d527-11eb-8e6c-22031c701341.png)

## Usage Examples
Just cycle through the list of available secondary weapons and notice that they get selected one-by-one and that all get selected at the end of the list.

## Testing Done
Tested with firing all secondary weapons (on a ship with 3 separate secondary weapons installed).
Tested with firing individual secondary weapons (on a ship with 3 separate secondary weapons installed).

## Performance Impact
I don't expect any performance impact (the player keys are checked once per frame only).

2021-06-24 23:35 UTC, tehhowch commented
I'd still like that option present.

Default to none, then individual, then all.

Similarly, the user should be able to do Shift / Ctrl clicks with the selected secondaries, to e.g. select the first and third, or deselect one, etc.

2021-06-25 09:39 UTC, petervdmeer commented
> I'd still like that option present.
>
> Default to none, then individual, then all.

Ok, I added the original option back, and the order is like this again.

> Similarly, the user should be able to do Shift / Ctrl clicks with the selected secondaries, to e.g. select the first and third, or deselect one, etc.

Yes, that is a good next step, but I would not mind if we keep that for a next PR and just merge the "keyboard select all option" from this PR first.

2021-07-11 15:09 UTC, Amazinite requested changes

2021-07-11 15:09 UTC, Amazinite commented on source/PlayerInfo.cpp
> +	return;
No need to have a return at the end of a void function.
```suggestion
```

2021-07-11 15:40 UTC, petervdmeer commented on source/AI.cpp
>  					command.SetFire(index);
Done

2021-07-12 12:52 UTC, Amazinite approved these changes

2021-07-12 12:53 UTC, merged