Change Default MinimumHull Formula
endless-sky/endless-sky pull request #6092
Opened 2021-06-27 23:22 UTC by Ferociousfeind

**Feature:** This PR implements the feature request detailed and discussed in issue #4851, #3448.

## Feature Details
Changes the calculation of a ship's default minimum hull from a mix of 15%, 45%, and 10/sqrt(hull amount), to a continuous curve moving from 75% to 10% roughly over the spectrum of human ship values. A table to give a rough feel for the change (it is not a very large change in actuality)
100 hull = 69.1 minimum
200 hull = 128.3 minimum
300 hull = 180 minimum
400 hull = 225.7 minimum
500 hull = 266.7 minimum
625 hull = 312.5 minimum (the 50% mark)
1000 hull = 425 minimum
1500 hull = 540 minimum
2000 hull = 633.3 minimum
3000 hull = 787.5 minimum
3333.3 hull = 833.3 minimum (the 25% mark)
4000 hull = 920 minimum
5000 hull = 1041.7 minimum
10000 hull = 1590.1 minimum
25000 hull = 3125 minimum (the 12.5% mark)

## UI Screenshots
![image](https://user-images.githubusercontent.com/35383563/123562353-4cd6e380-d77c-11eb-9d6f-d693095ed280.png)
The Wardragon has enough hull to breach the 15% line (its minimum hull is at 11.27%)
![image](https://user-images.githubusercontent.com/35383563/123562415-b656f200-d77c-11eb-8413-d777e1835689.png)
The Gull has 2500 hull, which equates to 714.3 hull, or 28.57%

## Usage Examples
N/A

## Testing Done
Purchased various ships and checked their displayed max hull and the size of the "disable" ring in-flight against the chart. For a moment I was concerned because I was checking shield values and they weren't matching up, but indeed the formula is working as intended.

## Performance Impact
Depending on how intensive a series of min()s and max()s are... MinimumHull() isn't called that often either way.

2021-06-27 23:32 UTC, MasterOfGrey commented
Can confirm this satisfactorily addresses #4851

2021-06-28 20:15 UTC, Ferociousfeind commented
oops, renamed a bunch of my branches and apparently that broke the connection between the branch and the PR

2021-07-14 09:26 UTC, Amazinite requested changes
I like the form of the equation as a replacement for the existing one, but I'm not as on board with the exact constants used.

2021-07-14 09:26 UTC, Amazinite commented on source/Ship.cpp
> +	double minimumHull = maximumHull * (thresholdPercent > 0. ? min(thresholdPercent, 1.) : 0.05 * (1. - transition) + 0.75 * transition);
I like these numbers better.
```suggestion
	double transition = 1 / (1 + 0.0005 * maximumHull);
	double minimumHull = maximumHull * (thresholdPercent > 0. ? min(thresholdPercent, 1.) : 0.1 * (1. - transition) + 0.5 * transition);
```
A similar impact on ships in the middle with less of an impact for ships on the high end compared to the previous numbers and almost no impact compared to the current equation for ships on the lowest end.

Ships from 0 to 600 hull get disabled at near the same point as the current equation.
Ships from 600 to 14000 hull get disabled sooner. (The peak change is that ships around 4500 hull have a disabled threshold about 50% higher.)
Ships above 14000 hull get disabled later.

2021-07-14 10:17 UTC, Amazinite commented
We'll also need to change the hull tooltip along side this.
```
tip "hull:"
	`Total hull strength. Small ships are disabled when their hull strength drops below 45%; larger ships are disabled at 15%.`
```
Instead of giving exact numbers, perhaps just mention that smaller ships are more easily disabled (as a fraction of their total hull) than larger ships.

2021-07-14 22:03 UTC, Ferociousfeind commented
Oh, I see. Running these numbers through desmos, that formula seems much less drastic than my change. I'll take it! I'll also adjust the tooltip for hull. At low hull, the minimum hull is around 50%, and the lowest minimum hull is 15% based on the numbers

2021-07-16 01:20 UTC, MasterOfGrey commented
Ah yes, nice edits.

2021-07-17 02:08 UTC, Ferociousfeind commented
Heeeeey wait, did that not push the changes through? I thought that "commit suggestion" would, you know, commit the suggestion to the PR. It seems it actually did not do this. Let me go manually do it...

2021-07-19 18:47 UTC, merged