Remnant - Adding the Ember Tear
endless-sky/endless-sky pull request #6310
Opened 2021-10-29 03:41 UTC by Zitchas

**Content (Artwork / Missions / Jobs)**

## Summary
This adds the long planned "Ember Tear." This is the biggest and deadliest weapon the Remnant have ever made, and it is so difficult to make that they've only made one, which is mounted on the Heron. This is basically a story weapon that the player will get to use in the Remnant end-game, but will never be purchasable. 

https://www.youtube.com/watch?v=qAn0VL7LGXc

Thanks to X-27 who made all the graphics for the Ember Tear. Most are their original graphics, a few are derivatives of MZ's work.
![Ember Tear in use](https://user-images.githubusercontent.com/32169904/139371897-1209ef98-90e2-4064-b556-21c5b073cbe1.PNG)

## Save File
This save file can be used to play through the new mission content:
[Jayne Kaely - Test.txt](https://github.com/endless-sky/endless-sky/files/7438706/Jayne.Kaely.-.Test.txt)

## PR Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [X] I uploaded the necessary image, blend, and texture assets here:[ link to a zip file on google drive.](https://drive.google.com/file/d/1glOfBsdSXYhqXgLkUqQu_ZlViL4V7Jlp/view?usp=sharing)
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/202

2021-10-29 18:23 UTC, Terin commented
> Should we just scale up the AMC with every new "one-of-a-kind weapon" that pops up?

Yes. The Drak are meant to be on the top of the pile, and there's nothing inherently holy about the AMC fragments doing 5610 damage. We can change that to maintain their whole in the narrative of the game.

Or rather, keep the AMC as the sort of flyswatter weapon like Zitchas mentioned, and Derpy's issue about secondary weapon priorities could make be used to create some sort of fleet buster weapon for when they *really* get pissed. Or not even that. It's implied that the Archons could have blown up the stars in Korath space, that's well beyond numbers we see in game.

This weapon is meant to be a cool setpiece which is balanced around the Heron. You won't be able to put together a Dreadnought in Omnis designed to maximize efficiency of it. It can't even fully get through a Worldship's shields before burning out like was said, and the Korath will probably have much more powerful things at that point. It's not a normal weapon that makes Zitchas's Remnant Power Level higher than your Coalition Power Level, and you really have to step back from that corrosive mindset.

2021-10-29 18:40 UTC, Arachi-Lover commented
>The Drak are meant to be on the top of the pile, and there's nothing inherently holy about the AMC fragments doing 5610 damage. We can change that to maintain their whole in the narrative of the game.
The point is not that the AMC should be kept at it's current damage, I agree that it should be buffed, I would be fine with it having 6x the damage it currently has. 

My problem is with the reasoning, someone created a ludicrously powerful weapon, much more powerful than anything in the game so far, and it's for a faction that's not one of the three big bullies (Drak, Pug, Quarg). This means that the buff to the AMC would need to happen just to accomodate for this incredibly strong new weapon, rather than the weapon respecting the power differences and not being so blatantly overpowered in the first place.

>Or rather, keep the AMC as the sort of flyswatter weapon like Zitchas mentioned, and Derpy's issue about secondary weapon priorities could make be used to create some sort of fleet buster weapon for when they really get pissed.

That's just creating a Drak "one-of-a-kind superweapon" to accomodate for the unbalanced outfit being proposed. That's just delegating AMC buffs to another weapon, the poor reasoning behind it remains.

>This weapon is meant to be a cool setpiece which is balanced around the Heron.

Yes, it's for looks, but its effectiveness is much higher than would be reasonable. At a third of its current DPS it would still be tremendously powerful, and have such awe-inducing effects for the desired mission or scenario, but also much more reasonable.

>You won't be able to put together a Dreadnought in Omnis designed to maximize efficiency of it. It can't even fully get through a Worldship's shields before burning out like was said, and the Korath will probably have much more powerful things at that point.

That's irrelevant, obtainable or not, usable for a build or not, both the ship and the outfit need to be within the reasonable range for stats the Remnant could attain, we can't just claim that something can be as strong as we want just because you can't get it without cheats.

>It's not a normal weapon that makes Zitchas's Remnant Power Level higher than your Coalition Power Level, and you really have to step back from that corrosive mindset.

What mindset? That was never my point, if I was just wanting to have the Coalition or Heliarchs be stronger I wouldn't have denied Amazinite's suggestion for having the Overcharged Shield Module and Overclocked Repair Module be much stronger than they originally were released as, or even his statement in the latest PR for buffing them that they could be made lots stronger still. I don't care that the Coalition is stronger than the Remnant, that's not what made me want to work on them, if I had that mentality I would've just skipped to the Quarg, the Pug or the Drak altogether. What I'm doing is trying to keep things within reason, and this weapon is ridiculously unreasonable.

2021-10-29 23:00 UTC, Amazinite commented
While I understand the sentiment, I feel like you're exaggerating the weapon's power in its current state.
The Dragonflame at 156 tons (of weapon space) deals 8,333 shield DPS and 5,000 hull DPS, for a DPS/ton of 85.5.
The Drak AMC at 96 tons deals 5,400 shield and hull DPS, for a DPS/ton of 112.5.
The Ember Tear here at 200 tons deals 12,000 shield and hull DPS, for a DPS/ton of 120 (only ~7% higher than the AMC).

The difference between the Drak AMC and the other two weapons is that the Drak AMC requires no extra resources to fire, while the Dragonflame and Ember Tear both have rather significant firing fuel costs, alongside their significant firing energy and heat costs that far surpass that of the AMC; the AMC's energy and heat firing fuel costs are 1,800/s and 600/s respectively, while the Dragonflame's are 5,333/s and 13,333/s, and the Ember Tear's are 14,400/s and 6,300/s. Those firing costs are immense, so even if you make use of ramscoops to overcome the fuel cost, you're still not going to be firing the other two superweapons continuously for extended periods of time, while Archons can continue to fire their AMCs without issue. This is where we get into the distinction between burst DPS and sustained DPS that I mentioned earlier; while the on-paper DPS values of the Dragonflame and Ember Tear are higher than the AMC, those are their burst DPS values, but their sustained DPS values are in practice much lower than that, resulting in the AMC still being the superior weapon.

Could the Ember Tear be pulled back a bit in its DPS? Probably, but not as far as a third of what it is now. I for one would at least like the Drak AMC's DPS/ton to be the highest in the game, which wouldn't require much of a nerf on the Ember Tear's part. But does it blow the Drak AMC out of the water? Perhaps at the start of a fight, but in extended combat the Ember Tear will suffer, particularly as a result of its energy cost if the fuel cost can somehow be mitigated by using a high number of ramscoops and being in a particularly high solar wind system, as the 240 energy *per frame* requirement on the Ember Tear simply can not be maintained.

The Antimatter Core, the highest energy/frame power generation in the game, only produces 80 energy per frame. So a single Antimatter Core can only sustain a third of the Ember Tear's energy requirement, meaning that after you've burned through your energy stores and should you still have fuel remaining, your DPS is already cut to a third of what it was. Should you have access to them, two Antimatter Cores likely isn't unreasonable for a heavy warship, but that's still cutting a third of your DPS after your energy stores are out. The next best power generators provide anywhere from a fourth to half the energy per frame as an Antimatter Core at significantly higher masses, so the Ember Tear is simply unsustainable for extended combat.

Should you make use of a single Blue Sun Reactor (which is my power generation of choice on my late game heavy warships), you can only produce enough energy to sustain 3140 shield and hull DPS combined, which ends up coming out to less DPS/ton than an energy blaster of all things. And that's assuming you're putting *all* your energy toward this one weapon by not using your engines, not having any HP regen, and not having any other systems that draw energy.

2021-10-31 16:05 UTC, Zitchas commented
> What I'm doing is trying to keep things within reason, and this weapon is ridiculously unreasonable.

War is not reasonable. Scientific breakthroughs are also not reasonable. Inspiration is rarely reasonable either. Reasonable is basically synonomous for "what is eminently predictable as a result of the slow and measured continuation of the average."

The core of the problem here is philosophical: Namely, the philosophy of how factions (species/races/distinct groups) evolve and progress technologically over time. To distill discussions that have taken place elsewhere into succint points, it basically boils down to this:
1. Is technological progress linear, or not?
2. The Coalition has had X tens of thousands of years of access to large amounts of Quarg tech. Therefore it is impossible that the Remnant could learn something from it that the Coalition hasn't already discovered.
3. The Coalition has X times more population than the Remnant, therefore it is impossible that the Remnant could innovate/invent/discover/progress faster than the Coalition does.
4. The Coalition has so many more people, thus it is impossible that the Remnant could have a viewpoint, perspective, insight, or inspiration that the Coalition hasn't already had, because sheer numbers mean that the Coalition has had every one of those already.

To expand on that a bit:

**Technological Linearity**
Basically, the gist of our previous discussions is that, to the best of my understanding, Arachi has argued that technological progress is linear. Everyone must discover all technology in roughly the same order, every time. Of course some allowances for things that are in different streams, but, to use an [example from Civilization V,](https://civilization.fandom.com/wiki/List_of_technologies_in_Civ5) a civilization *must* discover archery before discovering the wheel, and *must* have both the wheel and trapping in order to discover horseback riding. There is no caveats, no "if"s or "but"s: If a civilization has not discovered "The Wheel" and "Trapping," then "Horseback riding" will forever remain an impossibility for them. 

I argue that there are few-to-no absolutes in technological progression. For instance, popular culture currently portrays electric cars as the successor to internal combustion engine, the "next generation of vehicles." This despite the fact that the first electric cars were developed *at the same time as* the internal combustion engine. Neither one can be said to really pre-date the other. We, as a society, simply made the choice that we preferred the one over the other. But we could have just as easily chosen the other way, and would have a *vastly* different present-day environment if we had done so. What would the world look like if we didn't have gas stations. Or if oil & gas weren't the mega-industries they were (and still are) for the better part of a century? So many ripple effects.

**Linearity of Ship Types**
This linearity of technological progression also has a strong parallel in ship development. Basically everyone in the ES universe (except for the Quarg and the Drak) basically had identical fleet structures that just varied in relative strength based on tier (which is the rough level of military tech). There has been strong reluctance to "allow" any faction to break with this patterning, although that has improved in recent years. Size is the simplest comparator here: If all factions' ships are roughly the same size, then their relative power scales very evenly based on their tier. The problem is that there is absolutely zero reason that everyone should build a given ship to the same size. What is a heavy warship to the Republic need not be the same size as a heavy warship for the Hai, or the Korath, or the Heliarchs. We actually have a great example of this in the Sheragi, who are *below* human tier, but who built their heavy warship to a much larger size, and thus it happens to be very effective, militarily speaking.

Realistically (and in terms of game interest/fun too), there is no reason why every species should have the same concept of what is a good ship size, strategy, or concept. To use another game as a example. Right now it feels like we're in Starcraft, where we start as the Terrans, then we gain access to more advanced Terrans, and we fight against several other variant Terran factions using different variations of strategies but still basically Terran equipment. I'd like to see more Zerg and Protoss out there - factions that aren't just **not terran**, they aren't using the same tactics, values, strategies, or (most importantly) models of development.

**Universality of Insight**
This strikes me as being like artwork: Everyone gets their own thing out of a piece of artwork. Even if 999999999 out of 1000000000 get basically the exact same thing out of it, there is no guarantee if you get 999999999999999999 people to look at it, that they've gotten *everything* there is to get in it. No matter how many trillions of people you add to that figure, there is *still* no guarantee that someone else can't come along and see something that *no one else* sees. Because at the most fundamental level, it isn't about the artwork, it is about the person looking at it. 

Yes, the Coalition has had X tens of thousands of years of access to Jump Drives, and still don't understand them. That has absolutely zero bearing on a Remnant scientist looking at one and going "Hey, the way it folds into itself like this gave me the idea to see if I can do this other thing." It's basically the exact same thing as having a piece of artwork that is a single black pixel on a uniformly white page. Just because it's a single black pixel on a white page doesn't mean that someone couldn't come along and say. "Hey, this piece of artwork gives me the idea that if I round of the corners and chop it in half, part of it could become a wing and the other part could be chopped up into smaller bits to turn into propellers to make a flying machine." Did the dot on the white sheet of paper teach the person how to make a flying machine? Of course not. But it was the visual stimuli that triggered them to think about something differently, and led them to a new idea. The fact that they had said idea when looking at the black pixel doesn't say a thing about the other trillion people that looked at it, either.

Which is the crux of the discussion: The argument that the Coalition, due to its vast population, has the numbers to basically ensure that, somewhere in the Coalition, someone has had every possible idea that the Remnant could ever have when staring at the same inspirational object.

This presupposes that there are a finite number of ideas in the universe, as well as the accompanying assumption that every conscious entity is capable of having every possible idea. I disagree on both counts, and posit that there is an infinite number of ideas in the universe, and that most consciousnesses are incapable of even perceiving the existence of vast swaths of those ideas. Furthermore, I hold to the idea that consciousnesses are shaped by a combination of their genetics, their environment, their culture, and a myriad of other factors. This is one of the reasons that many of our biggest scientific leaps are attributed to people who were loners, eccentrics, hermits, heretics, or in other ways were noted for the fact that they did not fit the norms of society. Which is to say, that their patterns of thought did not fit the expectations and standards of their society.

This also gets into the uniqueness of the individual. Are individuals actually unique? Or is there a finite number of individuals in the universe, so if you get a big enough population, you'll have good odds of having an instance of every individual that might be found in a much smaller group?

**Cultural Values (and the matter of technological stagnation)**

First off, let's get this out of the way: Stagnation is not, inherently, a [...]

2021-10-31 16:25 UTC, Arachi-Lover commented
> War is not reasonable. Scientific breakthroughs are also not reasonable. Inspiration is rarely reasonable either. Reasonable is basically synonomous for "what is eminently predictable as a result of the slow and measured continuation of the average."

This is the "harsh/warlike situations drastically increase rate at which breakthroughs happen, as it's a matter of necessity" argument I believe. How did that work out for the natives of South America when the Spanish arrived?

> Arachi has argued that technological progress is linear

I haven't.

> Too many paragraphs adressing things that I didn't even bring up in this PR.

You see your Remnant as the main character of the ES anime, so of course in your eyes they'll be able to do what nobody else could or that they're super talented and can just get things in a much shorter time period than much larger groups that've been at it for much longer, then you'll justify it by "the Remnant are all about survival." If you really believed in that rather than just using it as an excuse/get-out-of-jail-free card, you wouldn't have made the Korath be idiots that throw away lives for giggles, trying to hunt Void Sprites even though they're aware Archons guard them. The Korath Exiles have it much worse than the Remnant, why aren't they having three breakthroughs a week?
In the end, those excuses don't make ridiculous propositions any less senseless.

2021-10-31 18:10 UTC, Zitchas commented
The Korath didn't do it for giggles, they're much smarter than that. They are, however, also desperate. That being said, the Korath are the main antagonists for the Remnant, and I fully expect them to push the Remnant to the brink of extinction over the course of the Remnant storyline. Over the edge to actual extinction, depending on player choices. I wasn't joking about the Remnant losing at least one and probably more worlds.

Unlike the Coalition, the Korath are not only higher tech than the Remnant, but also subject to the same crucible of pressures driving them onwards. They took a hard hit from their civil war and subsequent exile, and that's taken a long time to recover from. But they are on an upwards trajectory alongside the Remnant, and probably at a faster pace (albeit different directions). 

And no, the Archon in Nenia isn't going to intervene to protect the Remnant. They're not going to chase down the Korath, either.

> I've also never said this, I specifically argued against groups with less resources and less experience than the Coalition managing to reverse-engineer JDs or Quarg tech.

You say you haven't said this, and then you turn around and say it. Even if you don't use names, the Coalition is the biggest concentration of resources and people in the galaxy outside of the Quarg, so any such arguments basically translate to "If the Coalition can't understand it, no-one can."

It's moot point, though, because as I said, the Remnant aren't reverse engineering Quarg tech. They are developing their own stuff that is inspired in part by their research into Quarg tech. Note the whole thing about inspiration **not** being about the thing at all, but rather one's own internal thoughts and ideas that just happened to be brought to the forefront by contemplation of the item. 

Again, though, there's this conceit that because the Coalition have had longer access, they must be the benchmark by which all other species are gauged in terms of understanding the Quarg. You don't seem to understand the idea that different people (especially different species) will have fundamentally different ways of understanding the world around them. If the Coalition don't understand the Quarg (and they have demonstrated that they do not understand the Quarg on a cultural, societal, or technological level), then there's decent odds that they *never* will. The fact that the Coalition doesn't understand the Quarg has absolutely zero bearing on any other species understanding the Quarg. It's not a slight on the Coalition, it's just the way conciousness works. There really ought to be more misunderstandings in the ES universe, but I chalk that up to Pug meddling.

2021-10-31 18:28 UTC, Arachi-Lover commented
> You say you haven't said this, and then you turn around and say it. Even if you don't use names, the Coalition is the biggest concentration of resources and people in the galaxy outside of the Quarg, so any such arguments basically translate to "If the Coalition can't understand it, no-one can."

No, I've only ever said this specifically in relation to the Remnant, the group I was referring to in that. The Coalition species have only been around longer than humanity, in the timeline they're newbies to everyone else. If the Korath had managed to do it before they almost killed themselves entirely, assuming a scenario where they had longer time with Quarg tech or JDs, I wouldn't have minded if they did manage to reverse engineer it, they'd have had the time for that and much more people for that, it'd be reasonable. I don't mind the Korath having figured out JDs. My argument is specifically reverse-engineering.
It's true that it's not impossible that an incredibly small group, with less knowledge and less resources would be able of reverse engineering technology that a much larger, more advanced, and more prosperous group hasn't been able to reverse engineer in spite of having it under great study for 6000 years. It's also true that it's not impossible for a monkey to type out the entirety of the bible by just pressing keys at random. Both those things, however, are so astronomically unlikely that none would believe you if you told them it happened. If you don't care about that just because it's technically possible, you're either being dishonest or willfully blind to the odds.

> It's moot point, though, because as I said, the Remnant aren't reverse engineering Quarg tech

I was just responding quickly to what I saw you bring up. I don't see how any of this has anything to do with this PR or my points on this weapon. I didn't even bring up the Coalition in my original points, I've only talked of that in responding to you or Terin who act like I'm pissy at this because it deals more damage than Heliarch guns.

>You don't seem to understand the idea that different people (especially different species) will have fundamentally different ways of understanding the world around them.

You don't seem to understand sample sizes.

> Countless people do multiple playthroughs of the game without ever finding the Remnant.

Would say that's a minority given what I've seen talked about in the Steam forums or Discord.

> Nope, the point of stories is to entertain and to teach. Coherence helps with that

Snow White and the Seven Dwarves but halfway through a song it cuts to Luke Skywalker vs Darth Vader in Cloud City. Seems to me coeherence is essential so that you can even take a story seriously.

> As far as I can tell, my stories make a lot of sense to quite a few people; so the fact that they don't make sense to a single person doesn't strike me as a reason to delete the whole thing. After all, I do not insist that absolutely everyone must do my missions and understand them; nor does one person's lack of understanding amount to a failure on my part.

Never made the point.

2021-10-31 18:35 UTC, Zitchas commented
*shrug*

2021-10-31 18:54 UTC, Arachi-Lover commented
> I'm not going to artificially limit a story because non-existent statistics show that it is improbable

So instead you'll artificially inflate capabilities of a group because of something equivalent to "the power of friendship" cliche from various anime.

> As a case in point, I seem to recall there are a number of movies kicking around these days about a single person (or very small teams) who manages to achieve things that large numbers of people with more resources don't manage to do.

An extension of plot-armor or main-character syndrome, yes.

> Strangely enough, these movies make a lot of sense to the general population, and even get them to throw buckets of movie at making more of them.

Measuring quality of writing by success in the box office, not a good practice.

> Seems to me that the general population likes these sorts of situations and events, so I suspect that they probably make sense to them on some level.

Thinking that makes sense would get you killed on battlefields, no you can't take on those thousand soldiers with the same equipment as you just because you're really good. Thinking that makes sense would get you behind in research, three Einsteins aren't beating the rest of the planet's scientists. Escapism is a thing, it's nice to put you and your pals in the places of the heroes on screen, and think you could take on the world. Notice the word though, escapism.

2021-10-31 19:11 UTC, Zitchas commented
Just to jump to Real Life for a minute, how about the fact that SpaceX is actively doing what Boeing and various other aerospace companies deemed to be either impossible or a distant long-term possibility, right now?

Small group of people outperforming major established industry players with access to vast experience, facilities, and institutional knowledge. Real Life example.

And yes, there are plenty of other similar small groups trying and failing. Being small is no guarantee of success. But one of the key advantages of small organization is fast knowledge transfer. Big organizations tend to do very badly at sharing lessons learned effectively, and change speed/directions very poorly.

2021-10-31 19:29 UTC, Arachi-Lover commented
> Just to jump to Real Life for a minute, how about the fact that SpaceX is actively doing what Boeing and various other aerospace companies deemed to be either impossible or a distant long-term possibility, right now?

Google gives me 9500 employees for SpaceX, and some 141000 for Boeing. That's some 7% the total employees of Boeing, quite a significant fraction, and it's a lot easier for one company on Earth to get ahead of another given information here is easier to access, in comparison to stealing information from an enemy planet or an unknown species. There's also the fact that companies claiming something impossible often times means "it won't be lucrative enough for us to try and do it."

> But one of the key advantages of small organization is fast knowledge transfer.

And one of the big disadvantages is the smaller sample size, which cannot be countered, whereas big organizations, especially those that are more technologically advanced, can mitigate the transfer of knowledge issue with their technology.

> For all we know, they've been spending the last 20k year trying to figure out how to make teleportation devices and have been totally ignoring jump drives and everything else they got from the Quarg. Maybe if they'd spent all that on researching Quarg tech, they'd be mass producing Wardragons right now.

It's flat out said in the description of their main research facility, Ring of Wisdom, that most of the efforts are devoted to trying to understand and reverse-engineer Quarg technology.

Can you stop assuming groups other than the Remnant are composed by idiots?

> But all that is irrelevant here, because the Coalition aren't involved with this.

Quite, so stop bringing them up and I'll stop needing to correct what you get wrong.

2021-10-31 19:37 UTC, Amazinite commented
For what it's worth, we know that the Korath developed weapons seemingly capable of splitting the crusts of planets during their civil war and dealing other major damage to the surface of planets. So the Korath were definitely capable of creating superweapons beyond what we've seen in game on ships so far, well beyond what the Ember Tear is capable of. So I don't see a reason why a ship vs ship superweapon like the Ember Tear couldn't be created by the Remnant. Just because we haven't seen the Drak or any other faction field superweapons of greater power doesn't mean that the Remnant can't have a superweapon of the power we see here, or that other factions couldn't create superweapons of greater power.

2021-10-31 19:46 UTC, AriDross commented
So, this sequence of discussion has been pretty silly from the beginning, because Arachi based it on a false premise that Zitchas doesn't seem to have bothered to challenge outside the specific context of the Drak AMC: The Remnant _aren't_ bloated, and they aren't _mary-sues_.

If the Remnant have more mission content than any of the other regions of the game (and, honestly, they might have more content than the Wanderers once Cognizance 2 gets merged, but they're still unlikely to have more content than the Free Worlds campaign), that doesn't make them narratively "bloated" by comparison, it makes them a labor of love that the people creating content for other factions should, frankly, aspire to live up to.

If the Remnant are bloated in terms of the technology, that would mean they have more outfits than the other factions in the game, wouldn't it? The fact of the matter is that they don't, even if you count their salvaged Korath outfits. The number of outfits they make available to the player are, obviously, less than humanity, and roughly on-par with the Wanderers, although the Wanderers almost certainly exceed the Remnant over the course of their campaign.

As for mary-sues, are the Remnant narratively mary sues? Flatly, no. Being a "Mary Sue" means that a character always wins, never struggles in the pursuit of victory, is loved by everyone around them, and generally faces no challenges throughout the course of a story. The commonly watered-down definition of a Mary Sue is simply that a Sue is better than everyone else around them, and beloved for it, but is that the case of the Remnant? Flatly, no. The Remnant have three worlds to their name, live in constant war with an older and more powerful culture, and are flatly on the back foot in that war, to the point that Zitchas has spoiled outright that they will _need_ the Heron ark-ships they've been holding in reserve, sooner than later, because that conflict will lead to the total loss of some of their current holdings. The only way I could see the Remnant being a mary-sue is that they're universally beloved by the playerbase... and even if that were true, that's not within the context of the narrative, and it speaks to the compelling groundwork MZ laid for this faction, and the compelling work Zitchas has done to progress them.

Finally, are the Remnant technologically mary-sues? Are their ships and outfits superior to the rest of the game? The answer is an obvious "No", although it's really a bit more nuanced. The Remnant's standard technology isn't beating anyone at any game. Integrated reverse thrusters are neat, but they still don't quite match the raw power of larger Korath engines. Their weapons? Thrasher turrets are actually pretty good, as is the Point Defense Turret, but those outfits were original MZ creations, so they don't speak to any intent on Zitchas' part. Their inhibitor guns are more practical to use than the Korath Detainer, sure, but not inherently better for that. None of their other technology is stand-out, save for the lack of repair outfits, because the Remnant's ships (smooth segue) have inbuilt regeneration. This sets them apart from everyone else in the game but the Pug, for certain, but Remnant ships have reduced total outfit space to compensate, so their current ship lineup is overall roughly equivalent to the Hai. The Hai are, decidedly, not mary-sues.

The question remains, however: Do the Heron and the Ember Tear, which the player can't even obtain normally (and thus do not break the normal balance of the game, which precludes the Remnant being technological mary-sues), make the Remnant narrative mary-sues? Is there a problem with the Remnant having access to technology that sits so far outside the realm of what we otherwise see from them? No, and no. The Heron and Ember Tear are, in terms Arachi will understand well, the equivalent of the Heliarchs having a stockpile of old Quarg tech that they can outfit their Punishers with if necessary, and maybe some bigger ships in reserve that they would only start piloting if a new war broke out. The Heron is too big an expensive to mass-produce, so for this and other reasons (like their massive populations) they would never break the narrative balance of power by entering open warfare. The Ember Tear, on the other hand, is a new innovation and will likely have its own issues that preclude mass-production.

For all the interesting points made so far, this entire argument has been a farce because Arachi began it from a false premise, and I hope that pointing this out can nudge things in a more constructive direction.

2021-10-31 19:56 UTC, Arachi-Lover commented
You didn't understand what I meant in calling them bloated and Mary Sues.

> The Heron and Ember Tear are, in terms Arachi will understand well

I don't need you to explain to me what they are.

> the equivalent of the Heliarchs having a stockpile of old Quarg tech that they can outfit their Punishers with if necessary

Not at all, one is the strongest weapon in the game, the other is a limited stash of weaponry that they can't reproduce and that individually aren't as impressive as the strongest weapon in the game.

> For all the interesting points made so far, this entire argument has been a farce because Arachi began it from a false premise

The idea that I started this with a false premise comes from you not understanding my points, an issue that seems common in this discussion, what with people bringing up the Coalition when I never mentioned them.

2021-10-31 20:21 UTC, gunqqer commented
To add another voice to the discussion: I see no issue with this. Tech can progress in leaps and bounds. See: 1945 and atomic weapons. Of all the factions that could create such a weapon, the Remnant is one of the best to do so. Humanity doesn't really like WMDs or the use of them and haven't been at total war for a while. The Wanderers would similarly abhore such a weapon and wouldn't even start researching such a thing. As stated before, the Coalition don't have the pressure of war to be sinking R&D into something like this. (Side note: I am ignoring Quarg, Pug, and Archons for obvious reasons) The Remnant and the Korath Exiles are in a unique position in the galaxy where they both are fighting tooth and nail for survival every single day. It makes sense that one of these factions would create such a terrifying weapon. 
On the topic of balance, I feel this is fine. The player doesn't get to keep this weapon. Having technology progress is sort of how a good sci-fi story should progress. Any argument involving Archons isn't really valid as I doubt any Archon is even showing a fraction of their faction's power. 
And no, the Remanant are not mary sues. In no way are they. Nor are they bloated. I see nothing that could corrobrate these assertions.

2021-10-31 20:33 UTC, Arachi-Lover commented
Of course you don't, you got banned from the server where discussions that'd provide context for my statements happened. You then pose and act civil here. Weak.

2021-10-31 20:35 UTC, gunqqer commented
Please act in a civil manner on github. And if you have additional context it should be provided here. I am deeply saddened that our community contains this level of toxicity.

2021-11-01 00:48 UTC, MasterOfGrey commented
I think one non-trivial point that's being overlooked here is that _it's not even going to be implemented yet_. It's a **story weapon** that isn't planned for use until the as yet **unwritten** Remnant **end-game**.

Functionally at the moment it's some pretty graphics with background numbers attached. That's all.

It has no actual in-game application until the story gets to that point, and the story ain't near to getting there yet, so there's months, if not years, left to debate the specific narrative justifications for it, and its numerical balancing isn't even going to be significantly relevant until the in-play scenario for its main use actually starts coming into view.

2021-11-05 07:19 UTC, Luuiscool4567 commented
I don't see any reason to not merge it now or at least close this PR. We do have ships and outfits not even in use like a certain Wanderer ship.

2021-11-05 13:12 UTC, Zitchas commented
> 
> 
> I don't see any reason to not merge it now or at least close this PR. We do have ships and outfits not even in use like a certain Wanderer ship.

As currently implemented in this PR, the Ember Tear *is* used in-game, however in the purely decorative form being a weapon on my person ship. So people might occasionally see it in use. It just isn't actually usable by the player or current missions.

2021-11-05 14:19 UTC, Luuiscool4567 commented
> > 
> > 
> > I don't see any reason to not merge it now or at least close this PR. We do have ships and outfits not even in use like a certain Wanderer ship.
> 
> As currently implemented in this PR, the Ember Tear *is* used in-game, however in the purely decorative form being a weapon on my person ship. So people might occasionally see it in use. It just isn't actually usable by the player or current missions.

Alright. It doesn't feel like it would be a problem if we added it in. We have other unique outfits that are only used by Authors and as such of the opinion to put it in anyways.

2022-01-24 18:17 UTC, Amazinite requested changes
Needs a high DPI PR and a link to the assets.

2022-01-24 18:17 UTC, Amazinite commented on copyright
> + images/effect/ember tear/ember?tear?vortex*
```suggestion
 images/effect/ember?tear/ember?tear?fire*
 images/effect/ember?tear/ember?tear?impact*
 images/effect/ember?tear/ember?tear?vortex*
```

2022-01-24 18:17 UTC, Amazinite commented on copyright
> + images/effect/ember tear/ember?tear?spark*
```suggestion
 images/effect/ember?tear/ember?tear?spark*
```

2022-01-25 17:54 UTC, Amazinite commented
Looks like we still need an assets link.

2022-01-25 18:26 UTC, Zitchas commented
Yep, it is coming, I have the files, just need the time to put it together. I have been a bit short on it the last few days.

2022-01-25 18:28 UTC, Amazinite commented
Take your time. Just making sure it wasn't forgotten.

2022-01-25 18:30 UTC, Zitchas commented
Thanks! I appreciate you following up on stuff like this.

2022-01-26 13:47 UTC, Zitchas commented
Assets: https://drive.google.com/file/d/1glOfBsdSXYhqXgLkUqQu_ZlViL4V7Jlp/view?usp=sharing
(blend file for the outfit, along with normal, x2, and high-res images.)

![Ember_Tear_very_high_res](https://user-images.githubusercontent.com/32169904/151174253-134d2d35-405c-4df8-b805-f8690beda68a.png)

I don't know if x-27 did any post-processing on this outfit image. If I get a .xcf, I will add it to the file.

2022-01-26 19:41 UTC, Zitchas commented
Update: there is no .xcf file. Tehat is all done in blender.

2022-01-26 19:44 UTC, merged

2022-01-26 19:45 UTC, Amazinite commented
We can iron out stats later when this actually comes into play in the story.

2022-01-27 01:50 UTC, quyykk commented
I'm getting a lot of

```
libpng warning: iCCP: known incorrect sRGB profile
```

logs when starting the game. Relevant: #3474. Seems like this is caused by some unnecessary png data in the files, but I have no idea actually.

2022-01-27 01:52 UTC, Zitchas commented
That's weird. Is this in your errors.txt? I'm not seeing anything generate in mine.

2022-01-27 01:55 UTC, quyykk commented
No not in errors.txt, but in the output when running the game from the command line. Might even be platform specific (I'm on Linux).