Displayed ship info refinements from @stechio.
endless-sky/endless-sky pull request #6326
Opened 2021-11-07 18:53 UTC by quyykk

**Feature:** This PR is a continuation from #4484 from @stechio.

## Feature Details
This PR improves the attribute list for ships by changing how they are displayed. See the screenshots for comparisons. All credit goes to @stechio.

## UI Screenshots

sorry for the bad quality, I don't know why the text is so blurry for some screenshots. The only difference are the text entries themselves and the formatting, not the color or font size.

![pr-shipyard](https://user-images.githubusercontent.com/85879619/140657489-d18adb40-d810-4ee1-9875-3e365a49419e.png)

![pr-outfitter](https://user-images.githubusercontent.com/85879619/140657698-b9eebcf3-bf45-4c96-89ac-89e6d22423fd.png)

![pr-info-new](https://user-images.githubusercontent.com/85879619/140657910-f687817c-5872-4521-92df-721312cdd0c5.png)

2021-11-07 19:41 UTC, Zitchas commented
All in all, this looks good.

The one detail that I'm not fond of is the change from "Required Crew/Bunks" to "Crew (min-max)".

I know many people are capture focused, but to many of us (and, arguably, to the lore) bunks aren't "places to put crew that might happen to be empty so you can put a passenger there", but rather "places to put passengers that you can put a soldier if you want."

The difference is slight, but given that there is no mechanical benefit to having additional crew (aside from capturing), I think it is more accurate to say that bunks are things that hold people that you just happen to be able to fill with crew.

Basically, I prefer the look of having it list "Here's how many required crew" and "here's the max bunks". It makes more sense to me.

2021-11-07 20:03 UTC, tehhowch requested changes
Please ensure the commit is properly attributed with a co-author trailer. One way to do that would be to squash the original work into a single commit and then commit the merge & additional feedback resolution

2021-11-07 23:31 UTC, quyykk commented
Shoot I pushed the wrong branch. Anyways, I squashed their commits into one and then merged into master. Now it says for that commit "stechio authored and quyykk committed". Is that okay?

2021-11-07 23:37 UTC, Amazinite commented
I'd just do what you had just before you squashed it: maintain the commit history of the old PR. That's what I did for #5971 when picking up #3502.

2021-11-07 23:43 UTC, quyykk commented
There you go :)

2021-11-15 08:48 UTC, quyykk commented
> The one detail that I'm not fond of is the change from "Required Crew/Bunks" to "Crew (min-max)".

I agree. How about `crew (required - total)`? `crew (required - free)`? `crew (required - max)`? I like the first one.

2021-11-15 13:00 UTC, Zitchas commented
> > The one detail that I'm not fond of is the change from "Required Crew/Bunks" to "Crew (min-max)".
> 
> I agree. How about `crew (required - total)` or `crew (required - max)`?

I don't see either of those as really being changes. It's not so much the format that I'm concerned about, but rather the "Bunks" reference. We have outfits that talk about bunks, we have missions and jobs that talk about needing x bunks, we have `<bunks>` as a replacement text. I think as a matter of consistency and clarity to the player we should continue to refer to the maximum number of people onboard as bunks.

2021-11-15 13:09 UTC, quyykk commented
Well, what would you suggest? To keep with the new formatting `bunks (required - total)`?

2021-11-15 13:20 UTC, Zitchas commented
Just looking at the pictures, and it strikes me that the most appropriate format could well be that of the other space related things:

`bunks free    31/75`

After all, the number of required crew is irrelevant, right? What players are really concerned about is generally one of two values:

1. How many free bunks to put passengers in, or
2. What is the total number of bunks to attack an enemy ship with.

2022-01-17 17:42 UTC, quyykk commented
It now looks like this, as proposed by Zitchas. The relevant change is the "bunks free" line. It takes some getting used to, but I think it's an improvement.

![stechio bunks free](https://user-images.githubusercontent.com/85879619/149816235-7c2ed261-4e52-4943-b23e-685b0e4bec4d.png)

2022-03-15 03:54 UTC, Amazinite requested changes

2022-03-15 03:54 UTC, Amazinite commented on data/tooltips.txt
> +tip "bunks free:"
Not too keen on this change. While it does flip the order to display the number of bunks free, which is more useful for running jobs than the number of required crew, this now doesn't communicate why some bunks are taken up. I think we should just leave this line how it was, displaying the number of required crew and the total number of bunks.

2022-03-15 13:37 UTC, merged