QuickFeat: absolute velocity and angle options for effects
endless-sky/endless-sky pull request #6358
Opened 2021-11-23 06:59 UTC by Hurleveur

**Feature:** This PR implements the feature request made by X-27 on the discord (it's a quick one)

## Feature Details
Pretty simple : if you add "absolute angle" to an effect, it's angle will not depend on the previous angle of the projectile, just on what you put in it's txt. In the same way, "absolute velocity" means the velocity will not be inherited from the parent.

## UI Screenshots
N/A

## Usage Examples
If you want a grid fire effect, it can now be a real grid. I don't really know what other things this will achieve but it was asked and it's some really simple coding.

## Testing Done
Used a gun with a grid effect with no random angle or velocity to shoot at targets, the grid was perfectly aligned with my screen all the time.

## Performance Impact
N/A

2022-04-16 20:36 UTC, petervdmeer commented
The feature looks useful, but if we have absolute velocities and absolute angles, then I would still like to be able to set the actual absolute velocity and absolute angle (and not just the boolean that tells us those are absolute).

This could be relevant for a weapon that has an effect that needs to show both horizontally and vertically; instead of creating the effect twice (once for each direction) we would be able to specify the effect twice, with two different angles.

2022-05-16 05:23 UTC, Hurleveur commented
> The feature looks useful, but if we have absolute velocities and absolute angles, then I would still like to be able to set the actual absolute velocity and absolute angle (and not just the boolean that tells us those are absolute).
> 
> This could be relevant for a weapon that has an effect that needs to show both horizontally and vertically; instead of creating the effect twice (once for each direction) we would be able to specify the effect twice, with two different angles.

Sorry for only reacting now, but it's done
Damn I wish github would show new comments since last time PR was seen in the online interface

2022-05-24 06:41 UTC, quyykk commented on source/Effect.cpp
> +			absoluteVelocity = new Point(child.Value(1), child.Value(2));
Don't use `new`! That's a memory leak waiting to happen. You can create a new data member, `hasAbsoluteVelocity` to check whether an absolute velocity was specified.

2022-07-13 23:02 UTC, Amazinite requested changes

2022-07-13 23:02 UTC, Amazinite commented on source/Effect.h
> +	// Absolute means it does not depend from the angle of the projectile before, and can be specified.
```suggestion
	// Absolute values are independent of the parent Body if specified.
```

2022-07-14 20:43 UTC, Amazinite approved these changes

2022-07-14 20:52 UTC, Amazinite commented
The creating effects wiki has been updated with these new effect attributes.

2022-07-14 20:53 UTC, merged