(codestyle) Alphabetize ship names
endless-sky/endless-sky pull request #6403
Opened 2021-12-11 12:49 UTC by a-random-lemurian

This is primarily a "codestyle" pull request. This PR sorts names of the following phrases in A-Z order.

```yaml
- "republic capital"
- "free worlds capital"
- "syndicate capital"
- "militia"
- "republic small"
- "free worlds small"
```

This PR does not alter the C++ source code.

2021-12-11 18:52 UTC, tehhowch commented
I'm not really interested in this change as-is, because it removes the existing local contexts (such as "mountain names") and replaces them with nothing.

If you really strongly want to modify these phrases, make sure the local context is kept. (One way would be to create new phrases that yield an item from that context.)

2021-12-12 02:48 UTC, a-random-lemurian commented
> I'm not really interested in this change as-is, because it removes the existing local contexts (such as "mountain names") and replaces them with nothing.
> 
> If you really strongly want to modify these phrases, make sure the local context is kept. (One way would be to create new phrases that yield an item from that context.)

Could you explain how I would be able to do that? As in, would I add more names? Or would I add more phrases, as in, put the mountain names in phrases?

2021-12-12 17:17 UTC, Amazinite commented
Something like this:
```
phrase "republic capital"
	word
		"R.N.S. "
	phrase
		"mountains"
		"rivers"
		<whatever else republic capital ships are named after>

phrase "mountains"
	<alphabetized list of mountains>

phrase "rivers"
	<alphabetized list of rivers>
```

2021-12-12 18:01 UTC, a-random-lemurian commented
> Something like this:
> 
> ```
> phrase "republic capital"
> 	word
> 		"R.N.S. "
> 	phrase
> 		"mountains"
> 		"rivers"
> 		<whatever else republic capital ships are named after>
> 
> phrase "mountains"
> 	<alphabetized list of mountains>
> 
> phrase "rivers"
> 	<alphabetized list of rivers>
> ```

By the way, my knowledge of mountains and rivers suck. Are the river and mountain names mixed or are they separated, just with no comments that separate them?

2022-01-27 23:54 UTC, Amazinite commented
Any progress being made here?

2022-02-05 17:21 UTC, LepRyot requested changes
It doesn't look like they're mixed; each one of the ship name lists references a unique set of nouns

2022-02-05 17:21 UTC, LepRyot commented on data/human/names.txt
>  	word
```suggestion
	phrase
		"mountains"

phrase "mountains"
```

2022-02-05 17:21 UTC, LepRyot commented on data/human/names.txt
>  	word
```suggestion
	phrase
		"trees"

phrase "trees"
```

2022-02-05 17:21 UTC, LepRyot commented on data/human/names.txt
>  	word
```suggestion
	phrase "trees"
```

2022-02-05 17:21 UTC, LepRyot commented on data/human/names.txt
>  	word
```suggestion
	phrase
		"roman emperor"
phrase "roman emperor"
```

2022-02-05 17:21 UTC, LepRyot commented on data/human/names.txt
> +	word
```suggestion
	phrase
		"river"
phrase "river"
```

2022-02-05 17:21 UTC, LepRyot commented on data/human/names.txt
>  	word
```suggestion
	phrase
		"flower"
phrase "flower"
```

2022-02-05 17:21 UTC, LepRyot commented on data/human/names.txt
>  		"Cedar"
Duplicate list here
```suggestion
```

2022-02-05 17:21 UTC, LepRyot commented on data/human/names.txt
>  		"Elm"
```suggestion
```

2022-02-05 17:21 UTC, LepRyot commented on data/human/names.txt
>  		"Ginko"
```suggestion
```

2022-02-05 17:21 UTC, LepRyot commented on data/human/names.txt
>  		"Hawthorn"
```suggestion
```

2022-02-05 17:21 UTC, LepRyot commented on data/human/names.txt
>  		"Heath"
```suggestion
```

2022-02-05 17:21 UTC, LepRyot commented on data/human/names.txt
>  		"Myrtle"
```suggestion
```

2022-02-05 17:21 UTC, LepRyot commented on data/human/names.txt
>  		"Persimmon"
```suggestion
```

2022-02-05 17:21 UTC, LepRyot commented on data/human/names.txt
>  		"Primrose"
```suggestion
```

2022-02-05 17:21 UTC, LepRyot commented on data/human/names.txt
> +		"Yucca"
```suggestion
```

2022-02-05 17:21 UTC, LepRyot commented on data/human/names.txt
>  		"Spruce"
```suggestion
```

2022-02-05 17:21 UTC, LepRyot commented on data/human/names.txt
>  		"Quince"
```suggestion
```

2022-02-05 17:21 UTC, LepRyot commented on data/human/names.txt
>  		"Privet"
```suggestion
```

2022-02-07 07:56 UTC, a-random-lemurian commented
@LepRyot LGTM, let me commit and clean up all those junk commits that might be created

2022-02-07 08:09 UTC, a-random-lemurian commented
@Amazinite Should be good now, yes?

2022-02-08 06:46 UTC, merged