Change Spaceport descriptions in response to Remembrance Day
endless-sky/endless-sky pull request #6516
Opened 2022-01-29 12:05 UTC by Anarchist2

## Summary
This PR adds a new set of events that change spaceport descriptions in the Dirt Belt during the lead up to Remembrance Day, before reverting them to normal. Also modified are the spaceport descriptions of Allhome and Valhalla, while Tundra is left unaltered due to being affected by other events. New Washington also has a permanent change to its spaceport description.

2022-01-29 12:20 UTC, EjoThims approved these changes
Couple little things and questions, but this kind of thing is perfect for inclusion, imo. Nice little adjustments to make the world around you feel more alive :D

Amazinite makes a great point about the save bloat that I hadn't considered. I still really like the idea, but that definitely needs to be sorted.

2022-01-29 12:20 UTC, EjoThims commented on data/human/events.txt
> +		add spaceport `	The inn has been repurposed for hosting Remembrance Day celebrations. A canvas just above its entrance reads, "For those who have fallen, and those who will fall." The canvas is alr
"The canvas is already dappled."

The context of this is unclear to me.

2022-01-29 12:20 UTC, EjoThims commented on data/human/events.txt
> +		add spaceport `	In celebration of the upcoming Remembrance Day, the night sky above the port is densely occupied by choreographed drone formations, starship stunt flying and firework showcases.`
```suggestion
		add spaceport `	In celebration of the upcoming Remembrance Day, the night sky above the port is densely occupied by choreographed drone formations, starship stunt flying, and firework showcases.`
```

Oxford comma is a hill I will die on. :P

2022-01-29 12:20 UTC, EjoThims commented on data/human/events.txt
> +		add spaceport `	New Greenland was one of the worlds that was occupied during the Alpha Wars. Despite this, the celebrations on New Greenland are quite humble, most of the locals simply going about
```suggestion
		add spaceport `	New Greenland was one of the worlds that was occupied during the Alpha Wars. Despite this, the Remembrance Day celebrations on New Greenland are quite humble, most of the locals simply going about business as usual.`
```

2022-01-29 12:20 UTC, EjoThims commented on data/human/events.txt
> +		add spaceport `	It appears that the spaceport has not been embellished for the upcoming Remembrance Day. You assume that the main preparations are taking place in the planet's towns proper.`
```suggestion
		add spaceport `	It appears that the spaceport has not been embellished for the upcoming Remembrance Day. You assume that the main preparations are taking place in the planet's individual towns.`
```

2022-01-29 12:20 UTC, EjoThims commented on data/human/events.txt
> +		add spaceport `	The living quarters have been modestly decorated for Remembrance Day, with ceremonial flags being set up inside the dining halls, and a showcase of medals being set up on a wall, ea
```suggestion
		add spaceport `	The living quarters have been modestly decorated for Remembrance Day, with ceremonial flags being set up inside the dining halls and a showcase of medals being set up on a wall, each one belonging to the ancestors of those who live here now.`
```

2022-01-29 12:20 UTC, EjoThims commented on data/human/events.txt
> +event "remembrance day ends"
All of these are just the current defaults again, yes?

2022-01-29 17:39 UTC, Amazinite requested changes
This seems like an inappropriate use of events to me. Given that these events will trigger every year, that means that for each year that a player plays their save file will get bigger and bigger because of these events, as events are added to the `changes` section of the save file in sequential order of when they were triggered. And given that the changes only last for two weeks, the player might not even notice the changed descriptions, so we'd basically be bloating their save file for nothing.

If the intention is to add extra flavor to the spaceport around Remembrance Day then I'd say that's exactly what spaceport news is for. It should be very easy to create a bunch of spaceport news that only offers during the lead up to Remembrance Day, and making use of spaceport news wouldn't pollute the save file with changes every year.

2022-01-29 20:47 UTC, McloughlinGuy commented
I agree with amazinite, mainly because my computer seems to find ways to run out of storage space no matter what I do.

2022-02-08 02:16 UTC, MasterOfGrey commented
I'm also in favour of using news instead of save file bloat, but while we're here...

@Amazinite since we have conditional text either PR'd or merged now, how difficult do you think it would be to add conditional planet descriptions?

2022-02-08 05:30 UTC, Amazinite commented
It'd take a bit of work but wouldn't be too far out there.
Closing this since it won't be merged. If you go the news route then you can open a new PR. If we get planet descriptions that can change based on the player's conditions then we can revisit these exact descriptions without the need of events.

2022-02-08 05:30 UTC, closed without merging