Remove many instances where you are forced to fight friendly governments
endless-sky/endless-sky pull request #6543
Opened 2022-02-13 19:56 UTC by PeacefulPotato

**Content (Artwork / Missions / Jobs)**

## Summary
I updated a lot of missions so that you aren't forced to fight friendly governments, and added a few pirate jobs where you have to fight bounty hunters.

## Save File
[Test Pilot.txt](https://github.com/endless-sky/endless-sky/files/8056931/Test.Pilot.txt)

## PR Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I uploaded the necessary image, blend, and texture assets here: {{insert link to assets}}
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: {{insert PR link}}

2022-02-13 22:57 UTC, PeacefulPotato commented
Fair enough. I removed the separate faction.

2022-02-14 14:40 UTC, EjoThims commented
This makes a lot more sense now imo.

2022-02-17 02:12 UTC, PeacefulPotato commented on data/human/boarding missions.txt
> +		government "Pirate (Rival)"
Oops, I may have replaced the wrong part.

2022-02-17 02:14 UTC, PeacefulPotato commented on data/human/pirate jobs.txt
> +		random < 25
What do you mean?

2022-02-17 02:15 UTC, PeacefulPotato commented on data/governments.txt
> +	"player reputation" -10
I thought I put one in. My bad.

2022-02-17 02:17 UTC, PeacefulPotato commented on data/human/boarding missions.txt
> +mission "Assisting Friendly Ship (Small)"
All right. I added a comment instead explaining that it says merchant for compatibility purposes.

2022-03-08 13:58 UTC, Amazinite requested changes
The Pirate and Pirate (Rival) governments should not be enemies with one another, as then you could just let the naturally spawning pirates finish the mission for you. I think that the Pirate (Rival) government should also have a bribe of 0, although I wouldn't consider that change necessary.

The original purpose behind having the job to attack rival pirates was to have them start out friendly and then require the player to attack them; it's not as if they know that you're coming for them. So I think that we should set the rival government to the main government's reputation when the mission is accepted.
```
"reputation: Pirate (Rival)" = "reputation: Pirate"
```

Please remove the changes to the boarding missions file. I don't see pirates giving the player credits for assisting them at the same rate as merchants, and the purpose of the boarding pirate mission was like finding treasure on a pirate ship, so it would seem weird to me for this mission to spawn on merchants.

I also think we could go without the changes to the FW file; in both cases you are fighting pirates, so I don't see why we'd change the governments up. At most I'd keep the changes from pirate to Alpha, but the pirate to bounty change should definitely be reverted.

I'd also say remove the addition of the new jobs as that's a separate issue from what this PR's main intent is dealing with governments that the player fights.

2022-03-13 22:14 UTC, PeacefulPotato commented
I will change the rival government so that it is more like the disguised merchants.
The boarding missions file was because it felt weird that merchants would "thank you" for pillaging them, or that you would "raid" a pirate ship you repaired. I didn't realize there was a credit difference, so I could split up the missions based on whether or not the pirates/merchants are friendly. As for the FW missions, I will keep the Alphas but I'm fine with changing the Ryk Bartlett missions back to pirates, since now that I think about it this isn't exactly a bounty. The problem is as you said other friendly ships could do the mission for you. I will also move the new jobs away and possibly add it later as another pull request if I feel up to it.

2022-03-13 22:37 UTC, PeacefulPotato commented on data/human/pirate jobs.txt
> +		random < 25
OK, doesn't matter since I reverted the changes.

2022-03-14 03:03 UTC, Amazinite approved these changes

2022-03-14 03:04 UTC, merged