Add missions to remind the player to check spaceports
endless-sky/endless-sky pull request #6595
Opened 2022-03-10 10:01 UTC by Anarchist2

## Summary
Adds a new set of missions for players who ignore the spaceport. One is a spaceport mission that gets offered whenever the player checks the spaceport and has no other valid jobs available, and which updates a record of the last time that job was offered. The second is a mission that triggers when the game date is a set number of months after the recorded date. I decided to use the system implemented in this PR over checking to see if the player has checked the spaceport only once runs afoul of the current issue with spaceport visibility, where the player checks it once, then never does it again.

2022-03-10 13:17 UTC, Zitchas commented
That's an amusing little encounter. I like it.

2022-03-10 14:52 UTC, LepRyot requested changes

2022-03-10 14:52 UTC, LepRyot commented on data/human/human missions.txt
> +			`	He raises her hand and holds it open on his chest. "I know that it's only my word against yours, but I promise that you won't regret checking the spaceport every time you're in town."`
```suggestion
			`	He raises his hand and holds it open on his chest. "I know that it's only my word against yours, but I promise that you won't regret checking the spaceport every time you're in town."`
```
Little thing here, good mission

2022-03-10 15:17 UTC, Amazinite requested changes

2022-03-10 15:17 UTC, Amazinite commented on data/human/human missions.txt
> +			`	He pleasantly smiles and nods. "Well, I wish you the best in your travels." He walks away, leaving you free to explore the rest of <planet>'s facilities.`
Both replacements yield the same results in this case, but it's more proper to use `<origin>` when referring to the offering planet (plus you already used `<origin>` in the first line).
```suggestion
			`	He pleasantly smiles and nods. "Well, I wish you the best in your travels." He walks away, leaving you free to explore the rest of <origin>'s facilities.`
```

2022-03-11 00:23 UTC, MasterOfGrey commented
Is it possible to have this turn into a long reminder afterwards?
Like, if you've already had this interaction, keep resetting the timer occasionally and if you don't visit a spaceport for say, twice as long as the gap for this encounter, you get an `on landing` "As you ignore the spaceport for the umpteenth time a little voice in your head says, 'you won't regret checking the spaceport every time you're in town...'"
And then just have this repeat infinitely every time you go that long without checking?

2022-03-11 00:25 UTC, Amazinite commented
Possible? Yeah. Should we do it? I'd rather not.

2022-03-11 23:14 UTC, merged