Mugger
endless-sky/endless-sky pull request #6650
Opened 2022-03-27 03:19 UTC by Anarchist2

## Summary
Adds a new mission where the player gets held up and extorted for a free ride by someone whose preparedness is wanting.

This PR also makes some changes to "Transport Workers B".

## Save File
This save file can be used to play through the new mission content:
[I II II I-.txt](https://github.com/endless-sky/endless-sky/files/8356754/I.II.II.I-.txt)

2022-03-27 08:13 UTC, Anarchist2 commented
Marking as a draft since I want to rewrite some stuff.

2022-03-27 12:20 UTC, Zitchas commented
I'm slightly dubious about that backflip actually working, but it certainly is entertaining. Nice little story.

2022-03-29 11:41 UTC, Anarchist2 commented
While the death options might work in a vacuum (or a semi-vacuum, considering FW Katya), when in the context of the rest of the mission, it ends up raising some issues that can't really be solved without writing beyond the intent of the mission (Most prominently being, "Why is she telling me her entire life story when she was about to kill me?" Even the current explanation of "She doesn't really have the guts to kill another person," feels borderline to me.).

2022-04-17 18:39 UTC, Pointedstick commented on data/human/human missions.txt
> +			`	You push down as hard as you can with your legs while leaning backwards, rising to the lofty height of two feet above the ground. As you begin to fall back-first uncontrollably, you feel metal d
```suggestion
			`	You push down as hard as you can with your legs while leaning backwards, rising to the lofty height of two feet above the ground. As you begin to fall back-first uncontrollably, you feel metal dig into your spine as a gasp escapes from behind you, before landing on a soft body. You pick yourself up as fast as possible, and you end up face-to-face with your attacker. In the darkness, you pick out that she's wearing a black hoodie with a bandanna over her mouth, her back hunched over and feet placed apart. As you look down, you spot a sawed-off break-action shotgun held single-handed, the end of which is pointed at your abdomen. "Hands up now, Captain."`
```

(there's no such thing as a "breach-action shotgun")

2022-04-17 18:39 UTC, Pointedstick commented on data/human/human missions.txt
> +			`	You raise your arms and turn to face the woman. In the darkness, you pick out that she's wearing a black hoodie with a bandanna over her mouth, her back hunched over and feet placed apart. As yo
```suggestion
			`	You raise your arms and turn to face the woman. In the darkness, you pick out that she's wearing a black hoodie with a bandanna over her mouth, her back hunched over and feet placed apart. As you look down, you spot a sawed-off break-action shotgun held single-handed, the end of which is pointed at your abdomen.`
```

2022-04-17 18:39 UTC, Pointedstick commented on data/human/human missions.txt
> +				`	(Backwards somersault over your attacker and disarm her.)`
I might rewrite this in a slightly more plausible way. :) Like this:

```suggestion
				`	(Try a fancy acrobatic move and disarm your attacker.)`
```

2022-05-16 23:06 UTC, W1zrad requested changes
Looking solid to me. Seems like there's a follow-up planned for this?

2022-05-16 23:06 UTC, W1zrad commented on data/human/human missions.txt
> +			`	You push down as hard as you can with your legs while leaning backwards, rising to the lofty height of two feet above the ground. As you begin to fall back-first uncontrollably, you feel metal d
```suggestion
			`	You push down as hard as you can with your legs while leaning backwards, rising to the lofty height of two feet above the ground. As you begin to fall back-first uncontrollably, cold metal digs into your spine. A gasp escapes from behind as you land on a soft body. You pick yourself up as fast as possible, and you end up face-to-face with your attacker. In the darkness, you pick out that she's wearing a black hoodie with a bandanna over her mouth, her back hunched over and feet placed apart. As you look down, you spot a sawed-off break-action shotgun held single-handed, the end of which is pointed at your abdomen. "Hands up now, Captain."`
```
That `two feet` bit made me chuckle :)
I feel like that middle sentence could use some work - feels very long and messy as-is. If you've got any alternative ideas than the ones I'm suggesting, be my guest!

2022-05-16 23:06 UTC, W1zrad commented on data/human/human missions.txt
> +			`	You hand darts for your gun, and you manage to aim and fire before the woman does. She collapses on the ground while a cry escapes from her body. As you walk away, her body fades into the darkne
```suggestion
			`	You hand darts for your gun, and you somehow manage to aim and fire before the woman does. She collapses on the ground while a cry escapes from her body. As you walk away, her body fades into the darkness, blending with the garbage bags around it.`
```

2022-05-16 23:06 UTC, W1zrad commented on data/human/human missions.txt
> +			`	She seizes up for a few moments, before throwing her shotgun away and raising her hands. "I'm, um, sorry about threatening you. Would you mind if the both of us just walked this off?"`
```suggestion
			`	She seizes up for a few moments, then she throws her shotgun away and raises her hands. "I'm, um, sorry about threatening you. Would you mind if the both of us just walked this off?"`
```

2022-05-28 20:43 UTC, Amazinite requested changes
Bruh moment.

2022-05-28 20:43 UTC, Amazinite commented on data/human/human missions.txt
> +				decline
Don't need an endpoint at the end of a conversation that isn't in an on offer.
```suggestion
```

2022-05-28 20:43 UTC, Amazinite commented on data/human/human missions.txt
> +			`	She nods in response. "I'll try my best."`
```suggestion
			`	She nods in response. "I'll try my best," she says solemnly as she prepares to depart your ship.`
```

2022-05-28 20:44 UTC, Amazinite commented
Might be worth setting a condition for the scenarios where you shoot.

2022-05-29 06:55 UTC, Amazinite requested changes

2022-05-29 06:55 UTC, Amazinite commented on data/human/human missions.txt
> +			`	You push down as hard as you can with your legs while leaning backwards, rising to the lofty height of one foot above the ground. As you begin to fall back-first uncontrollably, cold metal digs
I feel like there's something more comedic about two feet than one foot, so I'd flip it back.

2022-05-29 06:55 UTC, Amazinite commented on data/human/human missions.txt
> +			`	You hand darts for your gun, and you somehow manage to aim and fire before the woman does. She collapses on the ground while a cry escapes from her body. As you walk away, her body fades into th
```suggestion
			action
				set "fumbling mugger shot"
			`	You hand darts for your gun, and you somehow manage to aim and fire before the woman does. She collapses on the ground while a cry escapes from her body. As you walk away, her body fades into the darkness, blending with the garbage bags around it.`
```

2022-05-29 06:55 UTC, Amazinite commented on data/human/human missions.txt
> +			`	You turn around as swiftly as you can as your hand grasps for your pistol. Due to surprise, or perhaps nervousness, the woman threatening you fails to fire the shotgun she's holding in the secon
```suggestion
			action
				set "fumbling mugger shot"
			`	You turn around as swiftly as you can as your hand grasps for your pistol. Due to surprise, or perhaps nervousness, the woman threatening you fails to fire the shotgun she's holding in the second you spend turning. You manage to land a shot, and your quarry falls while a cry escapes from her body. As you walk away, her body fades into the darkness, blending with the garbage bags around it.`
```

2022-05-31 00:21 UTC, Amazinite approved these changes

2022-05-31 23:37 UTC, W1zrad approved these changes

2022-05-31 23:38 UTC, merged