Heatsink
endless-sky/endless-sky pull request #6682
Opened 2022-04-05 19:20 UTC by Ferociousfeind

**Feature:** This PR implements a heat-sink attribute.

## Feature Details
`MaximumHeat()` is used throughout the game, for all sorts of calculations. This makes adjusting it extremely easy. If an outfit has `"heatsink" 1`, then the ship it is installed on will have +100 maximum heat capacity (mass does the same thing, while also slowing down thrusters)

## UI Screenshots
N/A

## Usage Examples
```
outfit "Large Heat Shunt"
	category "Systems"
	cost 790000
	thumbnail "outfit/large heat shunt"
	"mass" 24
	"outfit space" -24
	"cooling" 54
	"heatsink" 36
	description "Without these powerful cooling systems, most Korath warships would overheat within seconds as soon as they began to fire their weapons."
```

## Testing Done
Putting a large amount of "heatsink" onto the cooling ducts outfit, and then putting a large number of those onto a ship. This vastly increases the ship's thermal capacity, and firing weapons with huge firing heat causes a much smaller jump on the right-hand-side heat bar than if there were no cooling ducts on the ship. The attribute works as intended.

## Performance Impact
I do not know if accessing attributes is expensive (it is probably not), most likely this does not impact performance.

2022-04-05 19:58 UTC, petervdmeer commented
I don't think `"heatsink"` is a proper name for this attribute, because a heatsink is a device that transfers heat away from some fixed location to a flowing medium.
This attribute acts more like `"heat storage capacity"` (or `"additional heat storage capacity"`). The best name I can come up with is `"heat capacity"`, but that might be a bit confusing as well, since capacity is quite a common word. Please think of a better name for this attribute.

And what is the rationale behind adding a factor 100 difference between the value and the effect?

2022-04-05 20:14 UTC, Amazinite commented
> And what is the rationale behind adding a factor 100 difference between the value and the effect?

Because that's what mass does. For each additional ton of mass that a ship has, the ship's maximum heat goes up by 100. This new attribute allows you to alter a ship's maximum heat the same way that mass does without needing to also effect everything else that mass effects. How the player will see this affect them is via the heat capacity row/column on their ship's energy/heat table, so I think that `"heat capacity"` is a fine attribute name. This also makes it easily analogous to `"energy capacity"`.
![image](https://user-images.githubusercontent.com/17688683/161841127-551a4313-244a-4a89-b0d7-97a0d5a2ce0e.png)

2022-04-05 20:23 UTC, Amazinite requested changes

2022-04-05 20:23 UTC, Amazinite commented on data/tooltips.txt
> +	`Materials with high specific heat can make for powerful heatsinks. One "heatsink" is equal to one ton of mass, for holding heat.`
The mass tooltip should probably also mention mass' influence on heat capacity.
```suggestion
tip "heat capacity:"
	`Increases the maximum heat that this ship is able to withstand before becoming overheated. A value of one has the same influence on a ship's maximum heat as one ton of mass, without the effects that mass has on movement.`
```

2022-04-05 20:23 UTC, Amazinite commented on source/Ship.cpp
> +	return MAXIMUM_TEMPERATURE * (cargo.Used() + attributes.Mass() + attributes.Get("heatsink"));
```suggestion
	return MAXIMUM_TEMPERATURE * (cargo.Used() + attributes.Mass() + attributes.Get("heat capacity"));
```

2022-04-06 01:07 UTC, Ferociousfeind commented
If it's called "heat capacity", I would push a bit more for it to appear more analogous to energy capacity. If we compare energy capacity to energy generation, and then heat capacity to heat generation, and the effects they have on each other, then in-game "heat capacity" should appear 100x the raw value. There's a list of special displays for outfit attributes (60x, 60x60x, 60x100x, 100x + "%"...) is there are bare 100x variant?

2022-04-06 01:10 UTC, Amazinite commented
`{"heat capacity", 4},`
Remember though that the ship's heat dissipation also affects the max heat a ship can withstand, so an outfit with a heat capacity of 1 (showing in game as 100) wouldn't actually increase your ship's max heat by 100.
The tooltip saying that a value of one heat capacity = one mass' worth of max heat would also need changed if we had heat capacity display as 100x.

2022-04-06 01:27 UTC, Amazinite commented
Adding 1 ton to a Sparrow is +4.8 max heat. Adding 1 ton to a Bactrian is +2.4. So multiplying the displayed heat capacity be 100 would appear even less directly analogous.

2022-04-06 03:49 UTC, Ferociousfeind commented
Okay. I'll refrain from that. Just your suggested changes should work, then.

2022-04-06 06:05 UTC, Amazinite approved these changes

2022-04-06 06:13 UTC, merged