Rebalance the engine sandbox
endless-sky/endless-sky pull request #6686
Opened 2022-04-06 23:10 UTC by Amazinite

**Content (Artwork / Missions / Jobs)**

## Summary
This PR is meant as a stepping stone toward resolving #5271 and is a polished piece of #5779. It also resolves #6624.

The general gist of this PR is to shorten the range of speeds that ships are capable of while also increasing speeds at the low end of the spectrum. Shortening the range of possible speeds means that we won't as often have ships which, when using a reasonable engine loadout, go from normal to way too fast just be changing up the engines. This is mainly done by raising the speed floor rather than lowering the ceiling, which will most benefit default fittings and smaller ships.

The changes:
* **+1 Heavy Shuttle weapon space**: This resolves #6624, and takes the +1 weapon space suggestion from that issue instead of the -1 outfit space from #6625, as +1 weapon space is the minimum necessary change to resolve that issue.
* **-66% Ionic Afterburner heat**: The Ionic Afterburner is a weaker afterburner that uses less fuel at the cost of having firing energy, which the normal afterburner does not. Given that, it didn't make much sense to me for the Ionic Afterburner to have more heat than the normal afterburner, so I've significantly reduced the Ionic Afterburner's heat.
* **+50% Afterburner and Ionic Afterburner thrust**: These afterburners are generally underutilized, so a 50% thrust buff should hopefully make them more appealing.
* **Shrunk the Tyrant thruster and steering**: This engine pair was the most absurd thing in the game, clocking in at much larger than any other set of engines in the game, so much so that not a single ship in the game could equip both at once. I've shrunk the sizes of these engines from 167/125 to 136/106 and reduced other stats accordingly. I imagine you'll still be hard pressed to equip both at once, but each individually are now much more viable options than they were before.
* **+20% Ion and Plasma thrust and turn**: Human Ion and Plasma engines have been the worst engines in the game to have and are often replaced with something better almost immediately. This wasn't helped by the fact that the gap between these two engines and the next best thing was so large. This change, while keeping Ion and Plasma engines on the bottom, greatly reduces the gap between them and the next best engines, dragging the speed floor up with them.
* **+5% Radiant thrust and turn**: Wanderer Radiant engines are became fairly similar to human Plasma engines after the above change, so I've buffed Radiant engines slightly to compensate.
* **+2.5% Atomic turn, -5% Hai Atomic thrust, -2.5% Hai Atomic turn, and -5% Hai Atomic thrust energy and heat**: Currently, Hai Atomics are essentially a direct upgrade to human atomics, being smaller while also providing more thrust/ton and at a better energy and heat efficiency. These changes make it so that Hai Atomics are now more of a sidegrade to human Atomics instead of a direct upgrade, giving Hai Atomics comparable thrust/ton to human Atomics but at a slightly better energy and heat efficiency while keeping the smaller sizes.
* **-5%/0%/+5% Remnant thrust and -7.5%/-5%/-2.5% Remnant turn**: Remnant engines currently have a very flat improvement curve as you go up in size. These changes tilt Remnant engines to have a greater improvement as you go up in size, while also bringing Remnant steering down somewhat as it is currently an extremely good pick. This reduces the buff that was given to the steering by #5580, but does not fully revert it. 
* **+15% Pug turn**: Similarly to the buff to Radiant engines, the buff to Ion and Plasma engines started to encroach on Pug steering, so I've buffed them by 15% turn.
* **+5% Large Steering Module turn**: This change is as a result of the fact that the LSM shares a size with the A255 Atomic Steering. In buffing the A255, it only made sense to me to buff the LSM as well as to not have them be too close to one another in terms of turn/ton.
* **Removed the Graviton engines from Archons**: This is just a visual thing to remove the engine flares to give Archons more of an ethereal feel as opposed to just looking like organic ships with flares coming out their rears. Archons will still move at the same speed as before.

Instead of me posting a bunch of screenshots, here's the links to the Desmos graphs I used to eyeball these. Dots are original values, Xs are changed values. I have an extension that increases the number of colors you can use in Desmos so I have no idea how these will display if you don't have them. Note that I didn't look at Ka'het engines because they're too weird, and I didn't look at Quarg engines because they're placeholders and will be looked at anyway whenever the Quarg get redone.
* Thrusters: https://www.desmos.com/calculator/1aij9avyoq
* Steering: https://www.desmos.com/calculator/jt437mhhql

## Save File
N/A

## Artwork Checklist
N/A

2022-04-07 04:12 UTC, Zitchas commented
Well, overall I like the looks of this. Looking forward to trying it out.

That being said, being an *engine* PR, I'd prefer to see the  X1700 & X1100 size reduced by 1, rather than the shuttle being boosted. Having smaller tiniest engines feeds better towards the future enhancement of fighters & small ships into being their own unique thing.

Other than that rather minor detail, I'd be happy to have this merged into continuous as-is so we can try things out as a community.

2022-04-07 21:11 UTC, Amazinite commented
The only non-fighter with less weapon space than the Heavy Shuttle is the Shuttle at a weapon space of 10. That is, no ship aside from the Heavy Shuttle would be able to use reverse ion thrusters when it hadn't before if they were reduced in size by 1. The only other obvious consequence of that would be that some ships with 20 weapon space would be able to equip a reverse thruster and *one* energy blaster, but that's such a pitiful loadout that any potential boost in maneuverability wouldn't outweight the significant loss in firepower.

2022-04-07 22:41 UTC, Zitchas approved these changes
Well, merge away. This is all just one step toward the real meat: Ship masses. If no outfits are shrinking, and this is the extent of the engine changes, I'm really curious to see how you're going to get fighters up to really meaningful speeds.

2022-04-09 13:39 UTC, Zitchas requested changes
I'm fine with the nerf to the Remnant engines, but I do want to drop the Remnant afterburners from 11 outfit down to 9 as a result. (no change to mass or other stats) An appropriate boost to thrust would also be appreciated, but isn't required.

2022-04-10 19:26 UTC, Zitchas approved these changes
Let's get this merged.

2022-04-16 06:47 UTC, Amazinite commented
Things to note for the future:
* I didn't touch the Remnant Anvil-class hybrid engine (except for the 60% reverse thrust to 75% reverse thrust). Taking a look at it, the forward thrust seems pretty high for its size compared to other hybrid engines, but I'm fine with leaving it be, at least for now.
* I didn't look at Ka'het engines at all. If they become some sort of sleeper meta then I might visit them, but given that they're some of the few engines in the game that need plundered to use, it may be fine if they're a little on the strong side.
* Aside from the bump to the large steering module to make it better compete with atomics, Coalition engines are untouched by this, but it could be that they need a bump in the future to make them a more interesting choice.
* Korath engines are untouched, but that's because I was using them as a ceiling reference point.

2022-04-16 06:48 UTC, merged