Feature: Human culture - Post-conference at the pub
endless-sky/endless-sky pull request #6754
Opened 2022-04-23 17:28 UTC by dorbarker

## Summary
Adds a culture mission on urban human planets. The player can overhear snippets of conversation from a group of scientists who have gone to the pub following an academic conference.

Alternatively, instead of being implemented as a culture mission, it could be pared down and parts of it converted to a couple of `news` entries.

2022-04-24 00:54 UTC, Anarchist2 reviewed
Overall, the dialogue is good, but it's formatted messily. Make sure to indent paragraphs after the first one in a conversation.

2022-04-24 00:54 UTC, Anarchist2 commented on data/human/culture conversations.txt
> +			`The group takes their seats a long table near to where you are sitting.`
```suggestion
			`As you take a break after a long journey and a longer-feeling landing procedure, you notice a group of people enter the pub where you're sitting, streaming in from the conference complex across the street. They vary in age, dress, and accent, but most have an identical badge dangling from a lanyard around their necks. You notice one badge that's been dropped on the floor, reading  "Attendee - 35th Annual Pan-galactic Conference on Interstellar Microbial Genomics and Population Dynamics". The group takes their seats at a long table near to you.`
```

2022-04-24 00:54 UTC, Anarchist2 commented on data/human/culture conversations.txt
> +				`(Find somewhere quieter to spend your limited time planetside)`
```suggestion
				`	(Find somewhere quieter to relax.)`
```

2022-04-24 00:54 UTC, Anarchist2 commented on data/human/culture conversations.txt
> +				`(Order a meal and a drink for yourself.)`
```suggestion
				`	(Order a meal and listen in to their conversation.)`
```

2022-04-24 00:54 UTC, Anarchist2 commented on data/human/culture conversations.txt
> +			`"I don't think the nucleotide evidence supports their hypothesis at all! Like, I know the proteomic data could be used to support their conclusion, but they're ignoring synonymous mutations!"`
Avoid using border lines - they look bad in the ES engine. Instead use descriptions to mark the passage of time. Also avoid using bracketed text outside of action choices (or side comments).

2022-04-24 00:54 UTC, Anarchist2 commented on data/human/culture conversations.txt
> +				`(Order another beverage and continue listening.)`
```suggestion
				`	(Order another beverage and continue listening.)`
```

2022-04-24 00:54 UTC, Anarchist2 commented on data/human/culture conversations.txt
> +				`(Finish your meal and leave.)`
```suggestion
				`	(Finish your meal and leave.)`
```

2022-04-24 00:54 UTC, Anarchist2 commented on data/human/culture conversations.txt
> +			`The group's conversation grows louder by virtue of both passion for the subject of conversation as well as the effects of a few drinks.`
```suggestion
			`	The group's conversation grows louder by virtue of both passion for the subject as well as the influence of a few drinks.`
```

2022-04-24 00:54 UTC, Anarchist2 commented on data/human/culture conversations.txt
> +					decline
```suggestion
			`	You leave after finishing your meal, reflecting on having overheard a slice of a life very different from your own.`
				decline
```

2022-04-24 00:54 UTC, Anarchist2 commented on data/human/culture conversations.txt
> +				`(Finish up at your own pace.)`
```suggestion
				`	(Finish up at your own pace.)`
```

2022-04-24 00:54 UTC, Anarchist2 commented on data/human/culture conversations.txt
> +				`(Settle your bill as quickly as possible and leave.)`
```suggestion
				`	(Settle your bill as quickly as possible and leave.)`
```

2022-04-24 04:06 UTC, dorbarker commented
Thanks for the edits. I've accepted the changes for indentation and some rewording. 

Marking as draft for the moment while I rework some of the requested changes like removing the border lines. I'll re-request review once that's resolved.

2022-04-24 13:15 UTC, Zitchas reviewed
This is a fun little collection of bits of conversation from a conference. It looks like it fits fairly nicely. 

Anarchist2 does have a good point about replacing the `---` with descriptions to show the passage of time or breaks in the conversation. I'm not sure if doing so is strictly required, but it's definitely not something we have much of in ES so it does stand out a bit. As such, replacing it with descriptive text would help it mesh with the current game style.

2022-04-25 23:01 UTC, dorbarker commented
These latest changes should resolve problems with the earlier version. Indentation should now follow the style guide (which I overlooked before - apologies!), and border lines have been replaced with short scene descriptions.

I also did some miscellaneous editing and reorganized some of the conversations.

2022-04-26 11:59 UTC, Anarchist2 reviewed
I'm not sure that the line spaces look good in-game; compare with and without spaces:

![image](https://user-images.githubusercontent.com/60202690/165294487-a471a76f-acce-4385-9f67-f2a0cf88e8f4.png)

![image](https://user-images.githubusercontent.com/60202690/165294500-25a1fbe7-4714-431b-a832-feeafaa8d56b.png)

2022-04-26 11:59 UTC, Anarchist2 commented on data/human/culture conversations.txt
> +			`	"I'm so glad to have my presentation over with. I was so worried about having to present on the first day, but now I can finally just relax and actually listen to the other talks!"`
Moving the description and first lines of dialogue into a single line; line breaks are meant to be after changes in speaker.
```suggestion
			`	Two of the younger attendees are looking a bit nervous. "I'm so glad to have my presentation over with. I was so worried about having to present on the first day, but now I can finally just relax and actually listen to the other talks!"`
```

2022-04-26 11:59 UTC, Anarchist2 commented on data/human/culture conversations.txt
> +			`	"Is there some law I don't know about that requires every 'question' to start with 'I guess this isn't so much a question as a comment...'?"`
```suggestion
			`	Another scientist is rolling his eyes after a post-mortem of the day's events. "Is there some law I don't know about that requires every 'question' to start with 'I guess this isn't so much a question as a comment...'?"`
```

2022-04-26 11:59 UTC, Anarchist2 commented on data/human/culture conversations.txt
> +			`	"I don't think the nucleotide evidence supports their hypothesis at all! Like, I know the proteomic data could be used to support their conclusion, but they're ignoring synonymous mutations!"`
```suggestion
			`	An exasperated academic is speaking emphatically to her friend about what you infer to be a presentation they both heard earlier. "I don't think the nucleotide evidence supports their hypothesis at all! Like, I know the proteomic data could be used to support their conclusion, but they're ignoring synonymous mutations!"`
```

2022-04-26 11:59 UTC, Anarchist2 commented on data/human/culture conversations.txt
> +			`	"Can you believe my computer crashed right before I had to present? Good thing I had backups. Two is one and one is none."`
```suggestion
			`	One person is looking slightly shell-shocked after considering what might have been. "Can you believe my computer crashed right before I had to present? Good thing I had backups. Two is one and one is none."`
```

2022-04-26 11:59 UTC, Anarchist2 commented on data/human/culture conversations.txt
> +			`	"Singh and Esterhazy are such arrogant jerks. Their work is okay, I guess, but not enough to justify their wannabe rockstar personalities!"`
```suggestion
			`	A group seem to be discussing some other colleagues in the field who are, presumably, not present this evening. "Singh and Esterhazy are such arrogant jerks. Their work is okay, I guess, but not enough to justify their wannabe rockstar personalities!"`
```

2022-04-26 11:59 UTC, Anarchist2 commented on data/human/culture conversations.txt
> +			`	"The Republic Medical Research Agency said my work is too theoretical, but the University of Chiron Department of Microbiology says it's too applied!"`
```suggestion
			`	Grant applications seem to be a common subject. "The Republic Medical Research Agency said my work is too theoretical, but the University of Chiron Department of Microbiology says it's too applied!"`
```

2022-04-26 11:59 UTC, Anarchist2 commented on data/human/culture conversations.txt
> +			`	"Teaching sucks. Between class hours, office hours, and preparing lectures, there's hardly any time left for research."`
```suggestion
			`	Two attendees compare gripes about job demands. "Teaching sucks. Between class hours, office hours, and preparing lectures, there's hardly any time left for research."`
```

2022-04-26 11:59 UTC, Anarchist2 commented on data/human/culture conversations.txt
> +			`	"These conferences only last three or four days, but it always feels like it ages you a year."`
```suggestion
			`	A sociable, but exhausted-looking man is sitting back in his chair. "These conferences only last three or four days, but it always feels like it ages you a year."`
```

2022-05-17 00:02 UTC, W1zrad requested changes
Fun, funny, well-written! Very nice!

2022-05-18 01:57 UTC, W1zrad approved these changes
@Anarchist2 has a point about the extra line spacing being unusual, but I don't feel too strongly about it. If you plan to continue making missions (which I hope you do given the quality of this one), I'd say just try to refrain from the extra spaces in the future - but that's super minor. Thanks for the PR, enjoyed it!

2022-05-18 01:58 UTC, merged