refactor: Create EnergyLevels and EnergyHandler classes for dealing with Ship energies
endless-sky/endless-sky pull request #6804
Opened 2022-05-07 21:52 UTC by Amazinite

**Feature:** This PR implements the refactor detailed and in issue #6576.

## Feature Details
This PR refactors Ship as described in #6576 and partially in #6329 by adding two new classes:
* EnergyLevels: this class is nothing but a collection of doubles that represent various "energy levels" that a ship has. This includes hull, shields, heat, fuel, energy, and the DoT variables. Ship now contains an EnergyLevels object instead of a field for each of the levels. The name for this class comes from the following comment:
https://github.com/endless-sky/endless-sky/blob/3882d31009f52bce40e238db34a4a5970565f796/source/Ship.h#L512-L513
* EnergyHandler: this class is responsible for some (but not all) of the handling of a ship's EnergyLevels. EnergyHandler is currently responsible for repairs, taking damage, applying and resisting DoT status effects, and keeping track of movement costs (i.e. thrust, reverse thrust, turning, afterburners). The EnergyHandler does this by containing a set of EnergyLevels objects that each record the cost of these various actions. These EnergyLevels are updated whenever Ship::AddOutfit is called, meaning they are always up-to-date with the Ship's actual attributes. By storing costs in these EnergyLevels instead of recalling attributes.Get() every frame, EnergyHandler allows for cutting down on the number of string comparisons made each frame, as mentioned in #6329.

EnergyHandler could perhaps be expanded to have more responsibilities when it comes to handling a ship's EnergyLevels (e.g. EnergyHandler::CanExpend could be used in CanFire if we construct an EnergyLevels for the cost of firing a weapon), but the places where I've currently put it to use seemed to be the most obvious to me.

## Testing Done
Flew around with these changes. Observed how thrusting, reverse thrusting, turning, and afterburning all still work. Ships still take damage, repair, and bleed DoT.

## Performance Impact
This change cuts down on string comparisons by duplicating some attribute values from the attributes Outfit in Ship to various EnergyLevels in EnergyHandler, the tradeoff being memory usage from the duplicate doubles.

EnergyHandler updates its EnergyLevels whenever Ship::AddOutfit is called, meaning that adding an outfit now does many more string comparison than before, but I believe that AddOutfit is only ever called when in the outfitter or while boarding, which aren't performance intensive areas to begin with, so we should be good.

2022-05-08 19:40 UTC, Amazinite commented
Pretty sure this refactor also fixes a couple bugs/missing features:
* Weapons use to only check firing ion, disruption, and slowing. They now check all DoT costs.
* Weapons use to apply firing shields in full when fired. This caused ships to gain negative shields, which shouldn't be allowed to happen. Weapons now only apply the firing shield cost up to the amount of remaining shields.
* When thrusting or turning and applying fractional usage, if multiple costs were lacking but a later cost was closer to full than an earlier evaluated cost, the scale would be changed to match the later cost, therefore going over the budget of the earlier cost. Evaluating fractional thrust/turn now takes the rolling scale into account at each step, meaning that no costs should ever go over budget.
* Engines now check thrusting/turning DoT as a cost, whereas before they didn't. This matches their behavior to weapons, and prevents DoT counters from going negative. Question: should we allow engines to fire when they have a negative firing DoT, even if there's no DoT to remove? We'd them clamp any firing DoT to the remaining DoT counter, just as described above with weapon firing shields and the ship's remaining shields.

2022-05-17 04:12 UTC, waterhouse commented
Profiling this code, using the Mega Bucks pilotfile I put in https://github.com/endless-sky/endless-sky/issues/6329 , this looks to be a significant improvement.  In AI::AutoFire, now the "heaviest stack trace" is Mask::Collide (which looks like "real, necessary" computation), instead of the Dictionary::Get calls in Ship::IsDisabled.  Overall time spent in Dictionary::Get has dropped from about 30% to about 10%.

A breakdown of most of the remaining Dictionary::Get time, from a particular sample:
- 2.1% in IsStranded (1.2% JumpFuel, 0.7% JumpsRemaining)
- 1.3% in RequiredCrew
- 2% in Ship::Move (1.4% in DoGeneration)
- 1.3% in EnergyHandler::FiringCost

2022-05-17 04:41 UTC, Amazinite commented
A number of the remaining Gets in DoGeneration could probably be handled by EnergyHandler (e.g. energy generation, heat generation). The number of attributes that EnergyHandler wouldn't deal with are probably few and far enough between (e.g. required crew) that they could just get their own fields that are updated separately. The only doozy would be jump fuel and range, since those are dependent on individual outfits; perhaps ships could have a map of ranges and fuel consumptions for that range for each possible range given the ship's outfits. And FiringCost is going to need to stay how it is unless we store the FiringCost of each weapon when it's installed instead of generating it on the fly. Could probably have Armament keep track of FiringCosts.

2022-05-28 09:11 UTC, warp-core commented
Is this just waiting on a review from Tehhowch?

2022-06-05 22:05 UTC, warp-core approved these changes
Oh, I have to click this button for these comments to be visible to other people. Oops.
I'm not suggesting you make these changes here, this still seems a lot better than what we have now and I'm not entirely sure that my concept would work or be better.
Not sure my approval means much if you look at my PRs, but here you go.

2022-09-05 13:48 UTC, tibetiroka requested changes

2022-09-05 13:48 UTC, tibetiroka commented on source/EnergyHandler.cpp
> +PARTICULAR PURPOSE.  See the GNU General Public License for more details.
```suggestion
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
```
The standard copyright header was changed recently.

2022-09-05 13:48 UTC, tibetiroka commented on source/EnergyHandler.h
> +PARTICULAR PURPOSE.  See the GNU General Public License for more details.
```suggestion
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
```

2022-09-05 13:48 UTC, tibetiroka commented on source/EnergyLevels.h
> +PARTICULAR PURPOSE.  See the GNU General Public License for more details.
```suggestion
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
```

2022-10-21 03:07 UTC, Amazinite commented
This isn't a super important refactor so I'm gonna close this and revisit the idea later while there's less stuff on my plate.

2022-10-21 03:07 UTC, closed without merging