Add remodels of Wanderer Sunbeam weapons and Wanderer Anti-Missile hardpoint
endless-sky/endless-sky pull request #6821
Opened 2022-05-13 17:25 UTC by JanErikAhrens

## Summary
Adds remodels for the Wanderers' Sunbeam and related weapons. In addition, it adds a hardpoint sprite for the Wanderer Anti-Missile outfit.
![wanderer sunbeams](https://user-images.githubusercontent.com/72752000/168336075-c5c18dc9-113d-4515-99e4-9ce47c4fbd94.PNG)

## Save File
This save file can be used to view the new sprites in-game:
[Aaron Zuhl~Wanderer Tests.txt](https://github.com/endless-sky/endless-sky/files/8689732/Aaron.Zuhl.Wanderer.Tests.txt)

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/EndlessSkyCommunity/endless-sky-assets) with the necessary image, blend, and texture assets: https://github.com/EndlessSkyCommunity/endless-sky-assets/pull/30
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/241

2022-05-13 22:35 UTC, Amazinite requested changes
I prefer the style of the old single Sunbeam turret. Not every turret has to be in the same style with the gun sitting flat on top of the mount.

2022-05-14 10:48 UTC, TheMarksman-ES commented
Looking good. Any plans for the moonbeam?

2022-05-14 15:19 UTC, JanErikAhrens commented
Not until now, but I‘m inclined to give it a shot now you mention it.

2022-05-18 02:47 UTC, Amazinite approved these changes

2022-05-18 02:48 UTC, merged