feat(UI): Add panel to view and set defensive and opportunistic on hardpoints
endless-sky/endless-sky pull request #6822
Opened 2022-05-14 01:22 UTC by warp-core

Builds on #6730.

## Feature Details
Adds a new panel, accessible via a button on the ship info panel, that will allow the player to set defensive and opportunistic states on their weapons as well as displaying some relevant information.

It's not done yet, as you can see:

## UI Screenshots
![image](https://user-images.githubusercontent.com/20605679/168405562-1bb69f17-ddfd-43de-a625-e6770861f381.png)

## Testing Done
{{describe how you tested the new feature}}

## Performance Impact
{{describe any performance impact (positive or negative). "N/A" if no performance-critical code is changed. }}

2022-05-14 02:41 UTC, Zitchas commented
Oh, excellent! Thanks for working on this; I'm very much looking forward to being able to set different kinds of behavior to different turrets.

2022-05-14 12:38 UTC, warp-core commented
From #4714, @Zitchas suggested a slider that the game uses to automatically assign opportunistic to turrets based on  tracking speed, I think this can be added to this panel alongside the per hardpoint option already available (to make setting it on many turrets across many ships faster).
There were mentions of tooltips in the ship info panel on hovering over each weapon with icons to indicate opportunisticness, I also think it'd be good to add icons for defensiveness, always/frugal/never ammo expenditure and if the weapon is disabled, though that might be better for #6730 since it's not specific to the new panel.

2022-05-15 22:22 UTC, warp-core commented
What's the most commits a single PR has had made to its branch here?

2022-05-15 22:43 UTC, Zitchas commented
As MCO pointed out, PR #3761 had 188 commits and 1296 items in its conversation; and #4871 had 252 commits (but only 8 items of conversation). Can we tell which one I worked on the longest as a github branch? lol.

2022-05-16 00:13 UTC, warp-core commented
![image](https://user-images.githubusercontent.com/20605679/168500608-f67544ab-9f86-4bad-a88f-c5a78222e700.png)
![image](https://user-images.githubusercontent.com/20605679/168500619-0a71af8a-555c-4e11-9f0f-ce3bed8e9d42.png)

2022-05-16 18:54 UTC, warp-core commented
That was... interesting. Hope it didn't break anything too badly.

2022-05-23 17:11 UTC, warp-core commented
![image](https://user-images.githubusercontent.com/20605679/169872400-6a439c4e-f17a-4052-bf7f-c69d8127482e.png)

2022-05-24 01:41 UTC, samrocketman reviewed
I posted a video in discord https://discord.com/channels/251118043411775489/947227869036286033/978472385323880508

Here's my review so far:

> As a player, when I reorganize weapons I expect all of the things associated with said weapon to move with it.  In this case, I expected the settings set for that turret to transfer when I moved the weapon.  Instead, the hardpoint settings do not transfer.  Now arguably I understand these settings are for the hardpoint itself.  However, as a player (not thinking in code) to me intuitively I'm setting those settings for the weapon.  I would expect the settings to transfer when I reorganize the weapons.

2022-05-24 23:28 UTC, warp-core commented
@samrocketman swapping hardpoints should not take the fire control settings with the hardpoint.

2022-05-26 04:47 UTC, Saturnalia9 commented
Is it currently possible to turn a weapon off from manual fire? Such as how PD/AM turrets work, just with defensive turrets instead?

2022-05-26 10:16 UTC, warp-core commented
> Is it currently possible to turn a weapon off from manual fire? Such as how PD/AM turrets work, just with defensive turrets instead?

Not at the moment. I can add a 'manual control' option.

2022-05-28 22:47 UTC, warp-core commented
There's currently a bug in this where some (but not necessarily all) gun and turret hardpoint locations get set close to (but not exactly) (0,0). Not sure what's causing it.
Thanks to @Saturnalia9 for first telling me about this.

2022-09-05 13:47 UTC, tibetiroka requested changes

2022-09-05 13:47 UTC, tibetiroka commented on source/WeaponConfigPanel.cpp
> +PARTICULAR PURPOSE.  See the GNU General Public License for more details.
```suggestion
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
```
The standard copyright header was changed recently.

2022-09-05 13:47 UTC, tibetiroka commented on source/WeaponConfigPanel.h
> +PARTICULAR PURPOSE.  See the GNU General Public License for more details.
```suggestion
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
```

2022-11-09 19:12 UTC, Saturnalia9 commented
> There's currently a bug in this where some (but not necessarily all) gun and turret hardpoint locations get set close to (but not exactly) (0,0). Not sure what's causing it. Thanks to @Saturnalia9 for first telling me about this.

Did this ever get fixed?

2023-01-07 21:55 UTC, Amazinite commented
Closing this PR since it has been in the draft phase for some time. You can reopen it once you've finalized your changes and it's ready for review.

2023-01-07 21:55 UTC, closed without merging