DO NOT MERGE feat: government music
endless-sky/endless-sky pull request #6966
Opened 2022-06-24 00:28 UTC by Fzzr

Not done: literally any testing for what happens when things are not defined/edge cases. This is just a proof of concept for now!

**Feature:** This PR implements (a very small part of) the feature request detailed and discussed in: #233 and  #3594

## Feature Details

This is a proof of concept for making music more dynamic. So far it just applies the government music when a system has no music of its own. This would allow eg. changing the music for all "Republic" planets at once when the war begins instead of having to change them individually.

This will soon be extended to planets, then hopefully I'll be able to do dynamic changes to combat tracks with more new attributes. We may also want to use a different attribute name such as `playlist` to allow `music` to keep its current meaning of ambient sound (which is not quite the same thing) and leave open future feature extensions.

## UI Screenshots

N/A

## Usage Examples

Refer to #6965 but in the given plugin, add:
```
government "Republic"
	music "music/ByAnthrophantasmus/Republic Space"
```

Then launch from any system *other* than Rutilicus

## Testing Done

I did that thing above

## Performance Impact

Unknown

2022-06-24 00:49 UTC, Saugia commented
Merge Everything

2022-06-24 17:58 UTC, Fzzr commented
Just to manage expectations - the main initial purpose of this PR is to give the music plugin a build to work from so it can test without having to write hundreds of data file lines to add music to each planet and system. While something close to this may go in, it likely won't be until after a period of reaching consensus on the way music in general should work in ES. Separate lines of work include but are not limited to: music/sound effect balance, adaptive music for combat/possible other conditions, separate volume controls for music and effects, ways to have periods of silence between music tracks, multiple music tracks being able to be queued, etc.

2022-06-27 00:31 UTC, quyykk reviewed
Ok so thinking about this, I can understand the sentiment of not having to modify each and every system to add music, I don't think it's a good idea to give governments music, cause it doesn't really makes sense.

Additionally, if we have planet music default to system music, then we need to support a syntax to specify silence for silent planets in systems with music. So here too I don't think this change is a good idea either.

2022-06-27 07:05 UTC, Fzzr commented
Yeah it's not a slam dunk. Most discussions about music have revolved around giving different "regions" their own music and while there are attributes for that, they're not mutually exclusive with one another so deciding which one wins is not obvious.

2022-06-27 22:14 UTC, tehhowch requested changes

2022-08-24 19:54 UTC, Fzzr commented
Probably not the actual implementation, I'll reopen if it ends up relevant to the new data structure

2022-08-24 19:54 UTC, closed without merging