Allow NPCs to define cargo
endless-sky/endless-sky pull request #7113
Opened 2022-08-11 16:11 UTC by warp-core

**Feature:** This PR implements the feature request detailed and discussed in issue #7112 

## Feature Details
Moved the `cargo`, `commodities`, and `outfitters` members of `Fleet` to a new class, `FleetCargo`. `Fleet` and `NPC` each have a `FleetCargo` object. Also, moved `Fleet::SetCargo()` to `FleetCargo` along with a bunch of anonymous namespace methods in `Fleet.cpp` used by `SetCargo()`.
When an NPC calls `Place()` on a `Fleet`, it will additionally pass a boolean argument telling it not to add cargo to its ships (this is defaulted to true so anything else calling this method should not be affected).
The NPC will instead use its own `FleetCargo` object to add cargo to all of its ships at the end of instantiation.
A `fleet` being spawned by an `npc` will never use its own `FleetCargo` object to fill its ships' cargo holds.

## Usage Examples
`cargo`, `commodities`, and `outfitters` can be used as child nodes of `npc`, the same way they already could for `fleet`s.

## Testing Done
Very little so far. It built and launched and let me take off without crashing, though.

## Performance Impact
N/A, I hope.

2022-08-21 18:27 UTC, tibetiroka requested changes
Minor typo fix in a comment.

2022-08-21 18:27 UTC, tibetiroka commented on source/FleetCargo.cpp
> +// If neither or both were specified, choose commodities more often..
```suggestion
// If neither or both were specified, choose commodities more often.
```

2022-09-05 13:27 UTC, tibetiroka commented on source/FleetCargo.cpp
> +PARTICULAR PURPOSE.  See the GNU General Public License for more details.
```suggestion
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
```
The standard copyright header was changed recently.

2022-09-05 13:27 UTC, tibetiroka commented on source/FleetCargo.h
> +PARTICULAR PURPOSE.  See the GNU General Public License for more details.
```suggestion
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
```

2022-10-07 06:32 UTC, Hurleveur approved these changes
Looks very good (most of it is just moving code around, too)

2022-10-07 06:32 UTC, Hurleveur commented on source/NPC.cpp
> +		else if(child.Token(0) == "cargo" || child.Token(0) == "commodities" || child.Token(0) == "outfitters")
Isnt this line too long?

2022-10-07 12:01 UTC, warp-core commented
Rereading the summary, I'd actually like to make a change to this. Always overriding cargo defined by the fleet is bad.

2022-10-07 12:53 UTC, Hurleveur commented
Well maybe just add a warning that it will be ovewriten?

Some fleets that spawn in a system could have cargo that we'd want to remove or change for a specific mission, without redefining the whole fleet
Also what happens if you define multiple fleets with cargo within one npc; they all get that same cargo, right?
And multiple ships share it as a fleet?

2022-10-16 22:03 UTC, warp-core commented on source/NPC.cpp
> +		else if(child.Token(0) == "cargo" || child.Token(0) == "commodities" || child.Token(0) == "outfitters")
Over 80, but not quite 120.

2022-12-28 15:40 UTC, warp-core commented on source/Fleet.h
> +	void Place(const System &system, std::list<std::shared_ptr<Ship>> &ships, bool carried = true, bool addCargo = true) const;
```suggestion
	void Place(const System &system, std::list<std::shared_ptr<Ship>> &ships,
			bool carried = true, bool addCargo = true) const;
```

2023-03-30 23:53 UTC, merged