Skip using rendezvousTime with beam weapon turrets
endless-sky/endless-sky pull request #7168
Opened 2022-08-24 22:15 UTC by kaol

**Bugfix**

## Fix Details
`AimTurrets` uses `RendezvousTime` to calculate where the target would be when accounting for projectile velocity. This works as expected for projectile turrets but beam turrets don't actually have a velocity but the velocity they use is instead their range. This makes the turret's aim go wrong with small and fast targets, sometimes.

Instead they can use a `rendezvousTime` value of zero. There was a number of subsequent calculations that could be skipped if `rendezvousTime` was known to be zero.

Someone who knows better about weapons code could check this as well. Should this be using `Lifetime` instead of `TotalLifetime`? I looked at the code and there was something about submunitions and I don't know if this code should care about them if the goal is to just make an initial hit at a target.

## Testing Done
I flew around a bit and added a turreted projectile weapon and it seemed to aim well as well.

## Save File
Omitted, this can be tested anywhere where there are small ships and if you have turrets with beam weapons. The bug will occur when using 01196eb963a9b16161cac7cfff19c898eda8bc22, and will not occur when using this branch's build.

2022-08-25 04:40 UTC, Hurleveur commented
Nice! I noticed this bug but I was not sure if it came from code or just ship confusion.

2022-08-25 08:55 UTC, kaol commented
Right, that code is also using distance to penalize targets that are out of it. I changed the PR to make beam weapons to use to `rendezvousTime` also when the target is out of range. No need to use the `RendezvousTime` function for it since it's a simple distance check.

I think the `Weapon` class could use some `IsBeam` function that would return a boolean if it was meant to act as a one, but I'd leave that to some other refactoring PR.

2022-08-25 18:31 UTC, Amazinite commented on source/AI.cpp
> +					rendezvousTime = weapon->TotalLifetime() == 1 ? 0 : RendezvousTime(p, v, vp);
This bit will never run.
```suggestion
					rendezvousTime = RendezvousTime(p, v, vp);
```

2022-08-30 07:18 UTC, tibetiroka requested changes
Just to clarify: this is more of a grammar review, not a code review. The code patrol team will take care of that.

2022-08-30 07:18 UTC, tibetiroka commented on source/AI.cpp
> +				// Beam weapons hit instantenously if they are in range.
```suggestion
				// Beam weapons hit instantaneously if they are in range.
```

2022-08-30 07:18 UTC, tibetiroka commented on source/AI.cpp
> +
```suggestion
```

2022-08-31 05:35 UTC, Hurleveur requested changes
This only fixes turreted beam weapons, I don't see why we wouldn't fix gun beam weapons in the same PR, which I'm pretty sure have the same "bug". (the ship will angle at the wrong directing with its guns, its most visible when it only uses beam weapons I think)

2022-10-07 07:55 UTC, Hurleveur commented
If you need any help doing something never hesitate to ask, here or in the discord!

2022-10-27 05:49 UTC, Hurleveur commented
Nvm for the guns lets just fix it for turrets in this PR.

2022-10-27 05:51 UTC, Hurleveur approved these changes
Looks like a good fix.

2023-02-04 01:36 UTC, merged