(Content) Coalition Games News
endless-sky/endless-sky pull request #7257
Opened 2022-09-18 13:23 UTC by Arachi-Lover

----------------------
**Content (News)**

## Summary
Adds some new News entries to the Coalition, related to the Coalition Games, a massive yearly Olympics-like event taking place in July.

2022-09-18 13:44 UTC, tibetiroka requested changes

2022-09-18 13:44 UTC, tibetiroka commented on data/coalition/coalition news.txt
> +			"A Saryd game is playing on a monitor nearby. The athletes, separated into two teams, gallop around an uneven field, dotted with small mounds and holes, as they try to whack some balls into nets l
```suggestion
			"A Saryd game is playing on a monitor nearby. The athletes, separated into two teams, gallop around an uneven field, dotted with small mounds and holes, as they try to whack some balls into nets located around the arena's edges. Your best guess is that it's an awfully convoluted mix of cricket, football and pool."
```
I _think_ this is the correct one.

2022-09-18 13:44 UTC, tibetiroka commented on data/coalition/coalition news.txt
> +			"Some Arachi attentively wait for a game to start. The screen shows the competitors, who are also Arachi, putting on various layers of plate armor. They then all move to a metal cable, just thick
```suggestion
			"Some Arachi attentively wait for a game to start. The screen shows the competitors, who are also Arachi, putting on various layers of plate armor. They then all move to a metal cable, just thick enough for them to be gripped with all legs. They then stay there. For many minutes. Until they start falling one by one. Exhilarating."
```
Sounds better imo, but it was fine in terms of grammar.

2022-09-18 13:44 UTC, tibetiroka commented on data/coalition/coalition news.txt
> +			"You spot a few agents on their lunch break inside a local restaurant. They seem to be enjoying Coalition Games broadcast more than the meals themselves."
```suggestion
			"You spot a few agents on their lunch break inside a local restaurant. They seem to be enjoying the Coalition Games broadcast more than the meals themselves."
```

2022-09-18 13:44 UTC, tibetiroka commented on data/coalition/coalition news.txt
> +			`You arrive to a particularly crowded moment of the spaceport. The lines of people waiting for admission into the Games have now started looping around, heading inside some shops and restaurants,
```suggestion
			`You arrive to a particularly crowded moment of the spaceport. The lines of people waiting for admission into the Games have now started looping around, heading inside some shops and restaurants, and even a bit into the docking area. Battalions of Heliarch agents work as they can to bring everyone back into orderly lines.`
```
Also, maybe `hard as they can` or some variation of that might sound better there.

2022-09-19 17:33 UTC, tibetiroka requested changes

2022-09-19 17:33 UTC, tibetiroka commented on data/coalition/coalition news.txt
> +			"Entering the tremendously crowded spaceport, you notice a Saryd pastry shop opening up for business, and decided to head there for a snack. When you finally get to the door, however, they're just
```suggestion
			"Entering the tremendously crowded spaceport, you notice a Saryd pastry shop opening up for business, and decide to head there for a snack. When you finally get to the door, however, they're just done closing. It seems the masses heading to the Coalition Games bought all their products as the line was moving."
```
This is quite different from other news in its style; most news are about First Last observing or about people talking to them, while in this one First Last actually does something.

Also, I'm not sure if `notice` and `decide` should be present or past, but they should probably be in the same tense.

2022-09-19 17:33 UTC, tibetiroka commented on data/coalition/coalition news.txt
> +			"Several children of visitors coming to see the Coalition Games are running and playing simplified versions of the events, sporting different colors and assets for different games. Their parents s
```suggestion
			"Several children coming to see the Coalition Games are running and playing simplified versions of the events, sporting different colors and assets for different games. Their parents struggle between trying to get them to settle down, and keeping their spots in the waiting lines."
```
`Children of visitors` sound like the children aren't coming to see the games.

2022-09-20 00:04 UTC, roadrunner56 requested changes

2022-09-20 00:04 UTC, roadrunner56 commented on data/coalition/coalition news.txt
> +			"You arrive at a particularly crowded part of the spaceport. The lines of people waiting for admission into the Games have now started looping around, heading inside some shops and restaurants, an
```suggestion
			"You arrive at a particularly crowded part of the spaceport. The lines of people waiting for admission into the Games have now started looping around, heading inside some shops and restaurants, and even a bit into the docking area. Battalions of Heliarch agents work as hard as they can to bring everyone back into orderly lines."
```

2022-09-20 00:04 UTC, roadrunner56 commented on data/coalition/coalition news.txt
> +			"Several children coming to see the Coalition Games are running and playing simplified versions of the events, sporting different colors and assets for different games. Their parents struggle betw
```suggestion
			"Several children coming to see the Coalition Games are running and playing simplified versions of the events, sporting different colors and assets for different games. Their parents struggle between trying to get them to settle down and keeping their spots in the waiting lines."
```

2022-09-20 03:26 UTC, roadrunner56 approved these changes
Looks good!

2022-09-20 06:06 UTC, EjoThims requested changes

2022-09-20 06:06 UTC, EjoThims commented on data/coalition/coalition news.txt
> +			"You arrive at a particularly crowded part of the spaceport. The lines of people waiting for admission into the Games have now started looping around, heading inside some shops and restaurants, an
```suggestion
			"This is a particularly crowded part of the spaceport today. The lines of people waiting for admission into the Games have started crossing and looping in on themselves. Some even head inside shops and restaurants while others stretch into docking areas. Battalions of Heliarch agents work as hard as they can to bring everyone back into orderly lines."
```

2022-09-20 06:06 UTC, EjoThims commented on data/coalition/coalition news.txt
> +			"Several children coming to see the Coalition Games are running and playing simplified versions of the events, sporting different colors and assets for different games. Their parents struggle betw
```suggestion
			"Several children coming to see the Coalition Games are running and playing simplified versions of the events, sporting different colors and assets for different games. Their parents struggle  to get them to settle down while keeping their spots in the waiting lines."
```

2022-09-20 13:21 UTC, tibetiroka commented on data/coalition/coalition news.txt
> +			"Several children coming to see the Coalition Games are running and playing simplified versions of the events, sporting different colors and assets for different games. Their parents struggle betw
Look out for that extra space

2022-09-21 13:03 UTC, EjoThims approved these changes

2022-09-21 14:43 UTC, tibetiroka approved these changes

2022-10-02 22:22 UTC, Amazinite requested changes

2022-10-02 22:22 UTC, Amazinite commented on data/coalition/coalition news.txt
> +			"A Saryd game is playing on a monitor nearby. The athletes, separated into two teams, gallop around an uneven field, dotted with small mounds and holes, as they try to whack some balls into nets l
```suggestion
			"A Saryd game is playing on a monitor nearby. The athletes, separated into two teams, gallop around an uneven field, dotted with small mounds and holes, as they try to whack some balls into nets located around the arena's edges. Your best guess is that it's an awfully convoluted mix of cricket, football, and pool."
```

2022-10-02 22:22 UTC, Amazinite commented on data/coalition/coalition news.txt
> +			"During a break from the games, some analysts go over some spreadsheets with the statistics for the competitors of the past few games. You can't read any of it, but passerby workers and captains s
```suggestion
			"During a break from the games, some analysts go over spreadsheets with the statistics for the competitors of the past few games. You can't read any of it, but passerby workers and captains stay a while to glance at the results."
```

2022-10-02 22:22 UTC, Amazinite commented on data/coalition/coalition news.txt
> +			`"Just arrived from my first live viewing of the Coalition Games, I have. An incredible experience, it was. Go again next year, I for sure will!"`
```suggestion
		word
			`"`
		word
			`Going to see the Coalition Games, I am. Our biggest yearly event, it is.`
			`Competing in the Coalition Games this year, a friend of mine is. Cheering for them, my whole family is.`
			`Seen the latest transmission of the Coalition Games, have you? Throughout it all, on the edge I was!`
			`Checked the job board lately, have you? Eager to see the Coalition Games, tons of passengers are. A good season for business, this is.`
			`Watching the Coalition Games transmissions lately, I have been. Tried to become an athlete myself, I once did, but too rigorous, their training routine is! Made me appreciate the sports more, it has.`
			`Just arrived from my first live viewing of the Coalition Games, I have. An incredible experience, it was. Go again next year, I for sure will!`
		word
			`"`
```

2022-10-02 22:30 UTC, Amazinite approved these changes

2022-10-02 22:30 UTC, merged