Make the Leviathan and Falcon more distinct
endless-sky/endless-sky pull request #7318
Opened 2022-10-05 12:51 UTC by Anarchist2

## Summary
The Falcon and the Leviathan are very similar ships: both cost more than 9 million credits, have the highest health among civilian ships and have 240 weapon space. However, despite costing 1 million more, and having 10 more required crew, the Falcon tends to be inferior to the Leviathan, having less health and significantly less outfit space. This PR aims to both buff the Falcon and make the Falcon and Leviathan more distinct ships, with the Falcon being a balanced ship with the ability to specialise and the Leviathan being specifically combat-focused.

Changes:

- Increased the Leviathan from 480 mass and 7.6 drag to 580 mass and 8.1 drag, and decrease the Falcon from 510 to 490 mass. This makes the speed difference between the two vessels far more noticable and impactful.
- Increased the Falcon's bunks from 75 to 91, and cargo from 90 to 130. This makes the Falcon a better transport, as well as making it better at capturing and plundering.
- Increased the Falcon's outfit space from 540 to 560. This brings the Falcon from having the worst outfit space of all obtainable Heavy Warships to being on par with the Vanguard. Even when considering the use of outfit expansions, the Falcon still comes out 30 outfit space short compared to an outfit-expanded Leviathan.
- Increased the Falcon's weapon space from 240 to 250. This extra weapon space allows the Falcon to mount stronger weaponry than the Leviathan, but its lower outfit space means that it will have to choose between mobility, utility and offence (and it will still have less HP than the Leviathan).
- Changed the Marauder Falcon's crew requirement from being 9 less than the original to being 5 higher. Every other Marauder has more crew requirement than the original.

Changes to the original models are also carried over to the Marauder variants.

2022-10-05 21:30 UTC, Zitchas requested changes
Overall the changes look good for differentiating the two ships, however I don't think the falcon needs any reduction in mass. Better to just give the Leviathan and variants 20 additional mass than reduce the falcon by 20.

2022-10-05 21:30 UTC, Zitchas commented on data/human/marauders.txt
> +		"mass" 540
```suggestion
		"mass" 560
```

2022-10-05 21:30 UTC, Zitchas commented on data/human/marauders.txt
> +		"mass" 660
```suggestion
		"mass" 680
```

2022-10-05 21:30 UTC, Zitchas commented on data/human/ships.txt
> +		"mass" 490
```suggestion
		"mass" 510
```

2022-10-05 21:30 UTC, Zitchas commented on data/human/ships.txt
> +		"mass" 580
```suggestion
		"mass" 600
```

2022-10-08 17:23 UTC, williaji commented
I'm not really a maths guy so these comments are from a player perspective. First, I would ask that you not make the Leviathan any slower than it is. It already feels limited to me on engine space and I've tried many varieties and it must be well balanced because I'm not pleased with any of the trade offs. Second, there are two changes to the Falcon that I would like to see: 1) enough engine/outfit space to be able to fit Orca engines. It always seems weird to me that there are engine sets that no ship can use, as if the designers had no access to the parts catalog. 2) Consider adding 2 gun ports. The weapon load out on both ship is identical, 4 turrets, 4 guns. Adding two gun ports is a clear break with the Leviathan.  would let you field more energy weapons while retaining missiles. it would allow you to tweak your outfit space some as guns are more efficient. It would  let you build a fast gunboat that is far superior to a Vanguard in terms of flexibility and range.

2022-10-09 05:12 UTC, Anarchist2 commented
Even in its stock configuration, the Leviathan is plenty agile, able to outturn almost every medium warship. When customising it, it is able to match either the Falcon's speed or turning while only being slightly down in the other category.

As for increasing the Falcon's engine space/hardpoint count, I don't see either of those changes as necessary or helpful. The Falcon is already very fast; letting it use both Orca engines doesn't really help it (nor do I see the argument that a ship that can mount both Orca engines is inevitable). Giving the Falcon more guns would only serve to remove the Vanguard's niche; besides, it's not like having the exact same number of hardpoints makes two ships inconvertibly similar. The Firebird, Osprey, Corvette and Argosy all have two turrets and four guns, yet all four ships feel very distinct.

2022-10-20 02:04 UTC, merged