Documentation: Add Comments to all Functions in header files
endless-sky/endless-sky pull request #7371
Opened 2022-10-12 23:41 UTC by RisingLeaf

### Description
This PR's intention is to make editing ES code easier and more accessable by adding a comment in front of (nearly) every function in header files.
While some functions or group of functions already have some smaller or larger comments describing them, a lot are standing there without. The idea is to have a unfied comment format in front of them, that explains what they do and where they are accessed.

### Format
The format I thought of is best presented by this example:
```
// Disabled or stranded ships coordinate with other ships to get assistance. //
// Function to check if the ship is being helped, and if not, ask for help.
// Called during an AI step if the ship is stranded or disabled.
void AskForHelp(Ship &ship, bool &isStranded, const Ship *flagship);
// Function to check if the given ship can be helped by the helper ship.
// Called when asking for help and when checking if the ship has a helper.
static bool CanHelp(const Ship &ship, const Ship &helper, const bool needsFuel);
// Function to check if the given ship already has a helper ship.
// Called when asking for help.
bool HasHelper(const Ship &ship, const bool needsFuel);
```
Here I added a small heading for this group of functions and then a detailed description.

### Help Wanted
Of course I will be working on this, but it is a tiring process that takes a lot of time. Here is where you come in:
Want to write some descriptions? Do it and PR them to my fork of ES. I will be grateful for every help I get.

### Progress
For now I only added comments to the AI class, to give an example.

2022-10-13 12:21 UTC, tibetiroka requested changes
Quick grammar review. This review does not address the format itself.

2022-10-13 12:21 UTC, tibetiroka commented on source/AI.h
> +	// Called when the ENgine calculates a Step.
```suggestion
	// Called when the Engine calculates a Step.
```

2022-10-13 12:21 UTC, tibetiroka commented on source/AI.h
> +	// Called in all kind of movement functions.
```suggestion
	// Called in all kinds of movement functions.
```

2022-10-13 12:21 UTC, tibetiroka commented on source/AI.h
> +	// Called in an Ai step.
```suggestion
	// Called in an AI step.
```

2022-10-13 12:48 UTC, 1010todd commented on source/AI.h
> +	// If the trageted ship is an enemy the fleet will be given the
```suggestion
	// If the targeted ship is an enemy the fleet will be given the
```

2022-11-06 15:23 UTC, petervdmeer commented
Good initiative, but if we do this, then let's use a standardized parseble format, for example something like [Doxygen](https://doxygen.nl/). such a standard format allows us to automatically generate API documentation, and people outside of ES might also have seen it before (easier/quicker to read), and such a standard format might also integrate better into IDEs.

Comments can be added in small batches; so I feel it is more efficient to let everybody just PR new sets of comments directly to the main branch (after you give a good example :) ). Collecting them in your own branch first increases the risk on merge-conflicts, while it doesn't add much in the process.

The [Design by Contract](https://github.com/endless-sky/endless-sky/issues/7015) idea also seems somewhat relevant, but I suggest we mostly ignore that in relation to comments until somebody actually sets up some design by contract support.

2022-11-08 03:12 UTC, RisingLeaf commented
> Good initiative, but if we do this, then let's use a standardized parseble format, for example something like [Doxygen](https://doxygen.nl/). such a standard format allows us to automatically generate API documentation, and people outside of ES might also have seen it before (easier/quicker to read), and such a standard format might also integrate better into IDEs.

Hmmm... In this case I propose to use the following format:
```
/**
 * A brief history of JavaDoc-style (C-style) comments.
 *
 * This is the typical JavaDoc-style C-style comment. It starts with two
 * asterisks.
 *
 * @param theory Even if there is only one possible unified theory. it is just a
 *               set of rules and equations.
 */
void cstyle( int theory );
```

2023-01-01 01:18 UTC, RisingLeaf commented
Closing this, because we probably need a structure of how we want to do this before starting to add comments everywhere.

2023-01-01 01:18 UTC, closed without merging