Fix typo in ice crawler mission text
endless-sky/endless-sky pull request #7403
Opened 2022-10-17 02:04 UTC by aradapilot

NOTICE: Delete the sections that do not apply to your PR, and fill out the section that does.
(You can open a PR to add or improve a section, if you find them lacking!)

-----------------------
**Bugfix:** This PR addresses issue #{{insert number}}

## Fix Details
"frost-rimed" was spelled "frost-rimmed" in the recent release

## Testing Done
no functional change

2022-10-17 02:18 UTC, aradapilot commented
another in the same chain, "an usual" seemed contextually as it should be "an unusual"

2022-10-17 03:44 UTC, EjoThims requested changes

2022-10-17 03:44 UTC, EjoThims commented on data/human/deep missions.txt
> +			`	It is only a little warmer here than it was in the maintenance dock. To your left and right are wide, scratched, and frost-rimed windows.`
The original is correct, though awkward.

"Frost-rimed" is not correct in its own right, either.

2022-10-20 01:10 UTC, Amazinite commented on data/human/deep missions.txt
> +			`	It is only a little warmer here than it was in the maintenance dock. To your left and right are wide, scratched, and frost-rimed windows.`
```suggestion
			`	It is only a little warmer here than it was in the maintenance dock. To your left and right are wide, scratched, and frost-rimmed windows.`
```

2022-10-20 01:12 UTC, merged