Reorganization: Unfettered with their own files
endless-sky/endless-sky pull request #7420
Opened 2022-10-20 18:10 UTC by Hurleveur

This only moves content around, no changes were made. (same amount of lines)

With HR getting merged the hai files got bigger, and this will help clarify things for the Unfettered campaign PR (which does move  these missions around too). Currently it may not seem like there are many Unfettered jobs and missions but I will add many soon... I did not want to PR this before HR got merged to not make conflicts, but everything should be good now.

I'll be opening a PR to add new jobs for the Unfettered next, this will help make things clear. I'll also open a fix to the "it" used to refer to them, instead of "they".

2022-10-20 18:12 UTC, Hurleveur commented
Side note: I did not move the Hai fleets around since its such a small file and I'm not intending on making it bigger.
I was careful to just move things around by copy pasting.

I could separate other things, or even give them their own subfolder, do feel free to suggest changes.

2022-10-20 18:35 UTC, warp-core reviewed
I know all the new Jump Shield Beetle variants were used by the Unfettered, but they appeared in *Hai* Reveal (arguably, they should be defined in the Hai Reveal files, are they ever used outside of missions?)

2022-10-20 18:44 UTC, Hurleveur commented
They're not used outside of missions so I guess I'll move them in their respective missions?
Could also have a hai variants.txt file

2022-10-20 18:47 UTC, EjoThims commented
With Unfettered coming too, I'd think it's worth getting the Hai a variant file while we're moving things around anyway.

2022-10-20 19:01 UTC, Hurleveur commented
Thats a worthwile change but it can and should be in another PR, this one just aims to make UHai campaign easier to read, by not making it change so much for these jobs and missions.

~~I'll probably open that other variant PR myself if I cant sleep~~

2022-10-20 22:30 UTC, Amazinite commented
Splitting mission files makes sense to me (human missions of different factions/regions are in different files), but splitting ship files doesn't (all human or Coalition or Korath or Wanderer ships are in the same file; it's not like we split by government or subfaction within a species elsewhere).

2022-10-21 01:32 UTC, MasterOfGrey requested changes

2022-10-21 01:32 UTC, MasterOfGrey commented on data/hai/hai jobs.txt
> -		government "Hai"
This applies to all missions of this type.

Jobs/missions which offer in Hai space, should be in Hai files, even if they're related to the Unfettered.

Unfettered files should be for jobs or missions that offer in Unfettered space, or if such missions were to exist - potentially from Unfettered agents in Hai space. 

These aid missions are *Hai* missions.

2022-10-21 04:56 UTC, Hurleveur commented
> Splitting mission files makes sense to me (human missions of different factions/regions are in different files), but splitting ship files doesn't (all human or Coalition or Korath or Wanderer ships are in the same file; it's not like we split by government or subfaction within a species elsewhere).

I did it for clarity, not any other reason. The Korath ships.txt is a mess because everything is in it, and I'll add 5 ships in part 1 of the campaign alone, + at least 2 in part 2, so it'll get real messy.
I'll cancel those changes if you disagree with them, though.

2022-10-21 22:41 UTC, merged