Hai uhai ballet
endless-sky/endless-sky pull request #7471
Opened 2022-10-27 14:52 UTC by Hurleveur

This should resolve issue https://github.com/endless-sky/endless-sky/issues/5893

I made the Unfettered cowards, and Hai who had already disables were given merciful. This means that when damaged, the Unfettered try to escape, and the Hai let them.

In short, no more free Shield Beetles breaking the whole game balance, and bringing incoherence in the lore.

This does not affect any missions because they ignore the personality of the fleets used.

2022-10-27 17:26 UTC, Hurleveur commented
I stayed in Wah Ki for 10 minutes in x2 mode to try this out.
One beetle was disabled, on slivers of HP and got repaired and tried to flee shortly afterwards, as well as 2 lightning bugs

This does not mean one cannot get SB from the UHai anymore ofc, but you need to participate in it now that's all

2022-10-28 04:59 UTC, UnorderedSigh requested changes
The Unfettered fleets are used in the Wanderers campaign, so this will affect a lot more than you may think. You'll need to re-balance the Wanderers campaign battles, where the Unfettered probably shouldn't be cowards. Perhaps you could make new fleets for this instead?

2022-10-28 05:01 UTC, Hurleveur commented
As I stated in the description, any mission npc will not use these personalities, even if it only has one fleet and no personality defimed. I am 100% sure of that fact

2022-10-28 05:03 UTC, UnorderedSigh commented
What about the Unfettered fleets that defend their own systems?

2022-10-28 05:04 UTC, Hurleveur commented
That fact also means that the Hai reinforcements spawned by a mission will not be merciful,I could create a Patch mission for that

2022-10-28 05:24 UTC, UnorderedSigh commented
Okay. I'll test this soon, and let you know what I see. It seems the main test points are:

1. When I bully the Unfettered in their own systems, do they fight back effectively?
2. How do the random encounter fleets behave as they change throughout the Wanderer campaign?
3. How does this change the fight at Prakacha'a?
4. Can I easily capture a Lightning Bug with a Sparrow?
5. Can I quickly get rich by pillaging with a Sparrow or Star Barge?
6. Once I have a few escorts, is it easier or harder to grab Beetles en-masse?

It'll be interesting to see which way these changes take Beetle farming.  In the current version, with a proper build, I can get one beetle every 50 seconds in FF, and what slows me down is the Fettered trackers destroying them. Likewise, farming with your initial ship is hard because the Fettered destroy the delicious insects before you reach them. (Then they blow up and toast your Sparrow.)

2022-10-28 05:39 UTC, Hurleveur commented
I there are issues with the strength of the unfettered what should be done is increasing their amount, they need it

2022-10-29 17:43 UTC, UnorderedSigh requested changes
**Synopsis**: I've done a lot of testing: you've made farming more difficult (good) while creating many problems in the lore (bad). I think you can fix all of the problems by taking away the `coward` trait from Unfettered, but I haven't tested that. If you do that, I'll retest all of this for you.

### Good News

No detail needed on these:

1. It is nearly impossible to farm Shield Beetles without combat. It takes a long time, and a fast ship.
2. It is easier to farm Lightning Bugs, especially with a medium warship, so novice combat pilots will still visit, without breaking game balance.
3. Mass beetle farming now has a huge setup cost, so only the most dedicated farmers will attempt it in the early game. Others will farm Korath or pirates instead.
4. You can still get plenty of cash repairing damaged vessels and grabbing space trash in Wah Ki, which makes a lot of sense.
5. Unfettered are very effective at defending their home systems.

### Bad News

Mostly lore issues, since the non-stop suicide raids for 300 years seems to be an intentional part of the Endless Sky lore, not an oversight.

#### AI Glitch: Unfettered are Easy to Disable

You can easily disable an Unfettered Shield Beetle. Once it has taken a bit of damage, it'll stop fighting and try to retreat. Then, you come in from behind and paralyze it with four particle beams until it is disabled. It won't resist; it just waits to die. A Firebird can do this reliably in Wah Ki. A larger vessel could also pillage the Boulder Reactor or capture the Shield Beetle.  This is a fundamental flaw in the coward AI, so I'm not sure how you'll fix it.

#### Lore Trouble: Unfettered Planets Destroyed by Non-Stop Shipbuilding

Their planets are described as if they've destroyed their civilization by pouring all resources into shipbuilding and warfare for centuries. Endless suicide raids are a good explanation for that. I don't think that is a plot hole; I think it was the original intent of the Unfettered story.

You will need another justification for how and why they've destroyed their planets with centuries of endless shipbuilding.

#### Lore Trouble: Cloudfire Should be Intense, Non-Stop Warfare

With your changes, Cloudfire has minor skirmishes that last a minute or two. The descriptions of Cloudfire and Everhope make it clear there is a non-stop war over Cloudfire. According to the planet descriptions, the cities were abandoned, the normally peaceful Hai have a military base, there's a constant flow of weapons into Clodufire, and there are massive hangars dedicated to fleet repair. This is not consistent with Unfettered raids that last only a few minutes. It matches the description of what is in the master now: intense, non-stop, warfare.

#### Lore Trouble: Unfettered Random Encounters Should Press Their Attacks in the Wanderers War

Two problems.

1. After the Unfettered have a foothold in Wanderer space, the random encounter fleets are supposed to be invasion fleets, not raids. Every spare Shield Beetle and soldier the Unfettered have is fighting to take the Wanderer planets. They would not retreat; they would hold their ground. Coward AI makes them retreat more easily.
2. The Fettered help by increasing their presence in Wah Ki to draw out more Unfettered and increase their casualty rate. This won't happen if the Unfettered run away.

2022-10-29 18:45 UTC, Hurleveur commented
I disagree with any lore consequences, they still lose a lot of ships this way honestly, just not as absurdly as before, and I think many are lost wanderer side and resources are dedicated to other things, such as designing new ships and prototypes and trying them out, + throwing a thousand tracker per minute to the enemy.

As for the raids I could make them not coward but I think all of it would be solved by increased the UHai's presence by at least about 25% overall, justified by the fact they lose way less ships.

2022-10-29 19:12 UTC, UnorderedSigh commented
The Unfettered will still be easy to disable with a 25% increase. It is a flaw in the coward AI.

2022-10-29 19:19 UTC, UnorderedSigh commented
Also, the Unfettered are still losing a *lot* of ships, probably almost as many as before. It happens because there's still thousands of damage of Trackers in the air after ships stop firing. You still get the illusion of fewer casualties though, since none are disabled, which is probably enough to make your point.

2022-10-29 19:22 UTC, UnorderedSigh commented
Regardless of lore, you have to do something about the Unfettered being so easy to disable, or that part of the game will be too easy. You could either remove `coward` or improve the coward ai.

2022-10-29 19:32 UTC, Hurleveur commented
> Regardless of lore, you have to do something about the Unfettered being so easy to disable, or that part of the game will be too easy. You could either remove `coward` or improve the coward ai.

Or simply increase the amount of Unfettered arriving in the system enough that you can't 1v1 a beetle that easily.
I may fix coward as well though but not sure how honestly it could be tricky to determine when one can flee or not.

2022-10-29 19:49 UTC, UnorderedSigh commented
No, it's not a 1v1 thing. You wait until the Fettered damage it, and then you attack it. Once you capture it, bribe the Unfettered and then land. No matter how many Unfettered you add, the player just has to get to the edge of the fight, and there'll be viable targets. This tactic didn't work without `coward` since the Unfettered killed you if you tried.

2022-10-29 19:56 UTC, Hurleveur commented
What is the particle beam? I can't prevent an SB from jumping with 4 particle cannons if thats what you mean, just tried it twice, even with the hai (the temporary fleet that doesnt have merciful) helping me out with their pulses the beetle got away
So mb u refer to another weapon?

2022-10-29 20:01 UTC, UnorderedSigh commented
No, it is the Particle Cannon. I'll give you the Firebird that I use to farm Lightning Bugs in your PR. It can also disable damaged Shield Beetles. You have to wait until they're trying to run and hit them at an angle.

[Turboshuttler Shipeater~3014-02-16 reverse thrusters.txt](https://github.com/endless-sky/endless-sky/files/9894510/Turboshuttler.Shipeater.3014-02-16.reverse.thrusters.txt)

2022-10-29 20:03 UTC, UnorderedSigh commented
Actually, I just redid it a few times, and it appears to work best directly from the front or back.

2022-10-29 20:06 UTC, Hurleveur commented
Feels more like a small exploit than a gamebreaking bug if you ask me, especially considering the risks involved (especially just now that I increased the fleet to 550 from 800) but I'll try it for sure.
If it only works from the front or back maybe its just a problem with those beetles needing a bit of reverse thrust to handle it, easy to fix.

2022-10-29 20:13 UTC, UnorderedSigh commented
Your "Wah Ki" ballet PR is already rebalancing Unfettered fleets all over the galaxy. Should you really also change the Shield Beetle designs too?

I think you should limit this PR to *just* the stated purpose: Wah Ki balancing. If you want to make all of the other Unfettered systems different, and re-tune the Shield Beetle designs, that belongs in another PR. Otherwise you'll have to keep debugging unrelated issues. You can simplify the PR easily: add coward variations of the fleets and have those only appear at Wah Ki.

2022-10-29 20:18 UTC, Hurleveur commented
I already changed the fleets out of hai space to not be affected, my point mostly was it isnt as big of a balance issue
I kept the starting uhai systems with coward fleets too

2022-10-29 20:32 UTC, UnorderedSigh commented
Ah, I see the commit now. Could you please also merge master?

Once you're at a good stopping point for testing, you can let me know and I'll retest.

2022-10-29 20:43 UTC, Hurleveur commented
I think now is pretty much good for a quick test? I dont want to remove coward as it'll prevent uhai escaping and not depict the picture I'd like.

I'd like @MasterOfGrey 's opinion on this and once we have that taken into account it'll probably be the final version-ish.

What is most debatable is how much the Unfettered should attack this system.
I made it 550(from 800) to be slightly less than the Hai (500 + other fleets) without being completely overwhelmed either, as they used to be, especially since they run away now.
An alternative would be to make them come say by 600-650 and give the Hai frugal so they dont overkill uhai until there are too many and you cant really farm them.

2022-10-29 20:59 UTC, UnorderedSigh commented
I'll retest now and let you know what easily-found balance-breaking troubles remain. 

I suppose paralyzing ships by hitting them at a specific angle with particle cannons is an "expert farming technique" that shouldn't count towards balance.

2022-10-30 00:43 UTC, UnorderedSigh approved these changes
I see no more problems in this PR. There are no lore troubles, and Wah Ki farming is less profitable. Farmers visiting the system will baffled by the lack of disabled Shield Beetles.

Here's the effects:

1. It is nearly impossible to farm Shield Beetles without fighting them.
2. Lightning Bugs are disabled more often than before. This will attract novice combat pilots to Hai space without breaking balance.
3. Mass-farming of Shield Beetles takes much longer to set up, so casual farmers will probably farm pirates and Korath instead. 
4. A Sparrow can capture a Lightning Bug pretty quickly.
5. Human medium warships with particle cannons can farm Lightning Bugs really fast.
6. You can still get money by collecting space junk or repairing ships. This is as it should be.

Earlier problems are gone:

1. Wah Ki doesn't look any different unless you study it closely.
2. Changes to other systems are gone.
3. People are unlikely to realize the Unfettered are `coward`s unless they read the code.

2022-10-30 08:19 UTC, MasterOfGrey commented
> What is most debatable is how much the Unfettered should attack this system. I made it 550(from 800) to be slightly less than the Hai (500 + other fleets) without being completely overwhelmed either, as they used to be, especially since they run away now. An alternative would be to make them come say by 600-650 and give the Hai frugal so they dont overkill uhai until there are too many and you cant really farm them.

It should be a decent amount of attacking. They're trying to make a point that is only really made by sustained, effective, pressure. And on the flip side, if the Hai started being frugal it would be evidence that the UHai weren't making their point emphatically enough. So no I don't think the Hai should be frugal.

> Here's the effects:
> 
> 1. It is nearly impossible to farm Shield Beetles without fighting them.
> 2. Lightning Bugs are disabled more often than before. This will attract novice combat pilots to Hai space without breaking balance.
> 3. Mass-farming of Shield Beetles takes much longer to set up, so casual farmers will probably farm pirates and Korath instead.
> 4. A Sparrow can capture a Lightning Bug pretty quickly.
> 5. Human medium warships with particle cannons can farm Lightning Bugs really fast.
> 6. You can still get money by collecting space junk or repairing ships. This is as it should be.
> 
> Earlier problems are gone:
> 
> 1. Wah Ki doesn't look any different unless you study it closely.
> 2. Changes to other systems are gone.
> 3. People are unlikely to realize the Unfettered are `coward`s unless they read the code.

Sounds like the objectives have been achieved pretty effectively.

2022-10-30 08:20 UTC, MasterOfGrey approved these changes

2022-11-01 02:30 UTC, Zitchas approved these changes
This is a good change to the Wah Ki battle zone. Fits the lore much better than the current devastation. Reducing the amount of ships to be captured is icing on the cake.

2022-11-06 01:29 UTC, UnorderedSigh commented
@Hurleveur You should do this to the Korath raiding fleets too, as they have suicide raids, which make no sense given their limited resources. Without the "merciful" attackers, it may not be as effective as Wah Ki, but it should be better than it is now.  (That should be in a different PR though.)

2022-11-06 05:48 UTC, Hurleveur commented
Koraths already can leave pretty reliably as they have a jump drive and big mass + good engines
I'll let raven worry about such a change honestly (for the mining ship she said no so...)

2022-12-16 21:38 UTC, merged