feat(mechanics): Missions can use systems as sources and destinations
endless-sky/endless-sky pull request #7546
Opened 2022-11-07 19:47 UTC by warp-core

**Feature:**

## Feature Details
A mission can use `entering` as a location (like `landing`, `job`, `boarding`, `assisting`, and the implicit `spaceport`) to specify that it should offer when the player enters a system.
A `source` system can then be given (note that it is imperative that the `entering` tag appear in the mission definition before you attempt to provide a system as a source, otherwise, it will use the system name to look up a planet, which will either fail or find a planet that happens to have the same name as the system you wanted to use.)
A destination system is given using the token `"destination system"` (don't try giving both a destination planet and system, things will probably break, I'll add a warning soon).
Location filter syntax is unchanged (using a location filter to select a destination system won't currently work, whether or not the source filter selects a system is based on whether or not the system is `entering`).

This probably doesn't work right now. Good luck!

## Usage Examples
{{if this feature is used in the data files, provide examples!}}

## Testing Done
{{describe how you tested the new feature}}

### Automated Tests Added
{{describe the automated tests you added (using the unit-test framework, integration-test framework or otherwise) to reduce the risk of regressions in the future. "N/A" if this PR is not for an in-game feature that needs to remain functional in the future. }}

## Performance Impact
{{describe any performance impact (positive or negative). "N/A" if no performance-critical code is changed. }}

2022-11-10 01:42 UTC, warp-core commented
So, it doesn't seem to crash anymore, but missions do not properly complete if they destination is a system.

2022-11-10 01:57 UTC, warp-core commented
Completion works! Here's a very simple mission I used to test:
```
mission "In Flight Offering Test 1"
	entering
	repeat
	source
		attributes "near earth"
	"destination system" Sol
	to offer
		not "In Flight Offering Test 1: active"
	on offer
		conversation
			`Hello!`
				accept
	on complete
		conversation
			`Done!`
```
There are many more things that need testing, but it should now be possible to test them. NPCs in particular are going to be interesting, also, cargo, and similar. I strongly recommend you backup any save files before trying to run this.

2022-11-10 16:54 UTC, warp-core commented on source/Mission.cpp
> +
```suggestion

```

2022-11-18 07:24 UTC, Hurleveur commented
Could you fix the conflicts please?

2022-12-19 01:54 UTC, warp-core commented
Oh dear, that didn't take long to fail.

2022-12-19 07:07 UTC, Hurleveur requested changes
Fixing up my tests

2022-12-19 07:07 UTC, Hurleveur commented on tests/integration/config/plugins/integration-tests/data/tests/tests_on_enter_mission.txt
> +			"%TEST%: ON ENTER MISSION COMPLETION: completed" == 1
```suggestion
			"%TEST%: ON ENTER MISSION COMPLETION: done" == 1
```

2022-12-19 07:07 UTC, Hurleveur commented on tests/integration/config/plugins/integration-tests/data/tests/tests_on_enter_mission.txt
> +			"test: %TEST%: ON ENTER MISSION COMPLETION: completed" = "%TEST%: ON ENTER MISSION COMPLETION: completed"
```suggestion
			"test: %TEST%: ON ENTER MISSION COMPLETION: done" = "%TEST%: ON ENTER MISSION COMPLETION: done"
```

2022-12-19 07:07 UTC, Hurleveur commented on tests/integration/config/plugins/integration-tests/data/tests/tests_on_enter_mission.txt
> +			"%TEST%: ON ENTER MISSION: completed" == 1
```suggestion
			"%TEST%: ON ENTER MISSION: done" == 1
```

2022-12-19 07:07 UTC, Hurleveur commented on tests/integration/config/plugins/integration-tests/data/tests/tests_on_enter_mission.txt
> +			"test: %TEST%: ON ENTER MISSION: completed" = "%TEST%: ON ENTER MISSION: completed"
```suggestion
			"test: %TEST%: ON ENTER MISSION: done" = "%TEST%: ON ENTER MISSION: done"
```

2022-12-19 07:07 UTC, Hurleveur commented on tests/integration/config/plugins/integration-tests/data/tests/tests_on_enter_mission.txt
> +test "Land On Ruin helper"
As stated above this whole partial test is a duplicate

2022-12-19 07:07 UTC, Hurleveur commented on tests/integration/config/plugins/integration-tests/data/tests/tests_on_enter_mission.txt
> +		"finish in flight" = not "flagship planet: Ruin"
Either this always equals true or the mission completes in flight when it shouldnt, I'll test it locally

2022-12-19 07:33 UTC, Hurleveur requested changes
Seems to be weird things happening with conditions but whatever at least I'm sure this works.

2022-12-19 07:33 UTC, Hurleveur commented on tests/integration/config/plugins/integration-tests/data/tests/tests_on_enter_mission.txt
> +			"finish in flight" == 1
```suggestion
			"finish grounded" == 0
```

2022-12-19 07:33 UTC, Hurleveur commented on tests/integration/config/plugins/integration-tests/data/tests/tests_on_enter_mission.txt
> +			"finish in flight" == 0
```suggestion
			"finish grounded" == 1
```

2022-12-19 07:33 UTC, Hurleveur commented on tests/integration/config/plugins/integration-tests/data/tests/tests_on_enter_mission.txt
> +		"finish in flight" = not "flagship planet: Ruin"
```suggestion
		"finish grounded" = "flagship planet: Ruin"
```

2022-12-19 07:33 UTC, Hurleveur commented on tests/integration/config/plugins/integration-tests/data/tests/tests_on_enter_mission.txt
> +		"finish in flight" = not "flagship planet: Ruin"
```suggestion
		"finish grounded" = "flagship planet: Ruin"
```

2022-12-19 13:46 UTC, warp-core commented on tests/integration/config/plugins/integration-tests/data/tests/tests_on_enter_mission.txt
> +
```suggestion
```

2023-02-09 17:45 UTC, Hurleveur commented
Does this allow ships to spawn with these missions the same way it works for boarding misssions?

2024-07-26 16:22 UTC, tibetiroka commented
@warp-core Can you fix the merge conflicts?

2024-12-15 08:12 UTC, TheGiraffe3 commented
What's the status here?

2025-03-05 08:22 UTC, TheGiraffe3 commented
@warp-core could you resolve conflicts?

2025-03-08 04:51 UTC, TheGiraffe3 commented
Is there a reason this is still a draft?

2025-05-08 04:10 UTC, Amazinite commented
Closing in favor of #11388.

2025-05-08 04:11 UTC, closed without merging