Hai reveal tweaks
endless-sky/endless-sky pull request #7604
Opened 2022-11-14 21:23 UTC by McloughlinGuy

## Summary
I fixed typos, added a word in a certain place so it made sense, added some quotation marks in a few places, made it so the pincer beasts were mute (they would talk to you if you asked for help) and deleted the human alliance government, since it didn't need to exist anymore now that it's been replaced by just the regular republic ships. There's a weird thing that happens with the text when the pincer beasts blow up where the quotation marks spawn to the right of the text they should contain, but I couldn't find the data where the self destruct mechanism for them was contained, or anything on the predators that apparently exist. Anyways yeah, just a few tweaks.

2022-11-14 21:35 UTC, McloughlinGuy commented
It's clear to me now: I don't know how to remove a government.

2022-11-14 21:40 UTC, quyykk commented
All of mentions of the Human Alliance government:

![image](https://user-images.githubusercontent.com/85879619/201771145-150bb6c7-caad-493d-ac23-2ee2a5e9dbbb.png)

You forgot to remove the last two entries that set the reputation for those governments.

2022-11-14 21:45 UTC, McloughlinGuy commented
> All mentions of the Human Alliance government:
> 
> ![image](https://user-images.githubusercontent.com/85879619/201771145-150bb6c7-caad-493d-ac23-2ee2a5e9dbbb.png)
> 
> You forgot to remove the last two entries that set the reputation for those governments.

Thank you!

2022-11-16 02:03 UTC, MasterOfGrey requested changes
Thankyou so much for doing this. I hadn't cleared it out only because I hadn't had the confidence in amongst all the other changes at the time to be sure I would safely remove it and not break anything. You've saved me a good bit of time.

Re the tweaks, just a couple small adjustments, but otherwise this is fantastic! :)

2022-11-16 02:03 UTC, MasterOfGrey commented on data/hai/hai reveal 4 middle.txt
> +			`	She pays you for the trip and explains, "These blades are not ceremonial. Bring your gun with you, but put it behind when we reach the chambers, or the Unfettered may think you're an assassin. T
This should probably just match what you do later.
```suggestion
			`	She pays you for the trip and explains, "These blades are not ceremonial. Bring your gun with you, but hand it to them when we reach the chambers, or the Unfettered may think you're an assassin. Trust me, we'll be fine.`
```

2022-11-16 02:30 UTC, McloughlinGuy commented
> Thankyou so much for doing this. I hadn't cleared it out only because I hadn't had the confidence in amongst all the other changes at the time to be sure I would safely remove it and not break anything. You've saved me a good bit of time.
> 
> Re the tweaks, just a couple small adjustments, but otherwise this is fantastic! :)

Your welcome! Thanks to quyykk for helping me successfully remove the human alliance too. Glad I could help :)

2022-11-16 17:36 UTC, roadrunner56 approved these changes

2022-11-17 22:49 UTC, MasterOfGrey approved these changes

2022-11-17 23:55 UTC, merged