System invisible fence radius
endless-sky/endless-sky pull request #7704
Opened 2022-11-24 20:57 UTC by a-random-lemurian

## Summary
System-specific invisible fences can now be set. This will allow plugins to have bigger systems that truly feel big, without having to worry about NPCs going in circles the moment they reach the invisible fence.

This is something I bodged together and it is possible that this is nonfunctional, so please help me spot the errors in my code.

## Testing Done
I haven't done any testing yet.

## Usage Examples
None yet

## Performance Impact
Unsure

2022-11-24 21:03 UTC, warp-core reviewed
I don't think AI is used statically, but that variable in the namespace is going to be static. That's not good.

2022-11-24 21:03 UTC, warp-core commented on source/System.h
> +	double invisibleFenceRadius = 10000;
```suggestion
	double invisibleFenceRadius = 10000.;
```

2022-11-25 01:41 UTC, Koranir commented
The variable MAX_DISTANCE_FROM_CENTER should be changed to something like centerMaxDistance and moved to the header as it is no longer a constant.

2022-11-25 02:21 UTC, Zitchas commented
Being able to override the system fence on a per-system basis could be very useful even in vanilla. Thanks for working on this!

2022-11-25 02:37 UTC, a-random-lemurian commented
> @Zitchas said:
> Being able to override the system fence on a per-system basis could be very useful even in vanilla. Thanks for working on this!

You're welcome. Now my plugin (and vanilla, and all other plugins) can have bigger systems without the need to worry about the ships going around in circles.

However, I'm not ready for this to be merged yet. I still have some things I'd like to discuss.

- Should we use `"invisible fence"` as the keyword to override the system fence or should we use a different word like `"fence"`?

2022-11-26 20:20 UTC, RisingLeaf commented
The AI gas access to the system class, no need to store the radius in the AI class

2022-11-26 20:21 UTC, a-random-lemurian commented
> The AI gas access to the system class, no need to store the radius in the AI class

refactor time

2022-11-26 20:25 UTC, RisingLeaf commented on source/AI.cpp
> +	return this->invisibleFenceRadius;
```suggestion
	return invisibleFenceRadius;
```

I mean this function will be uneccessary if you look at my last comment, but for the future, class members do not need to be accessed with this->

2022-11-26 20:41 UTC, RisingLeaf commented on source/AI.cpp
> +		if(it->Position().Length() >= GetInvisibleFenceRadius())
```suggestion
		if(it->Position().Length() >= ship.GetSystem()->InvisibleFenceRadius())
```

2022-11-26 23:01 UTC, a-random-lemurian commented
Weird. This PR is segfaulting when I enter a system with a wormhole.

2022-11-27 17:40 UTC, wjp commented
One potential source of segfaults here is when looping through the list of ships in `AI::Step()` some ships might have a null System (for carried drones/fighters).

2022-11-28 01:10 UTC, a-random-lemurian commented
> @wjp said:
> One potential source of segfaults here is when looping through the list of ships in `AI::Step()` some ships might have a null System (for carried drones/fighters).

That was it all along! It works now. Let's make sure the tests succeed.

2022-12-11 20:57 UTC, RisingLeaf requested changes

2022-12-11 20:57 UTC, RisingLeaf commented on source/System.cpp
> +		}
```suggestion
		else if(key == "invisible fence" && child.Size() >= 2)
			invisibleFenceRadius = child.Value(1);
```

2022-12-11 20:59 UTC, RisingLeaf approved these changes

2022-12-11 22:51 UTC, Amazinite requested changes

2022-12-11 22:51 UTC, Amazinite commented on source/AI.cpp
> +			}
```suggestion
		const System *system = it->GetActualSystem()
		if(system && it->Position().Length() >= system ->InvisibleFenceRadius())
		{
			int &value = fenceCount[&*it];
			value = min(FENCE_MAX, value + FENCE_DECAY + 1);
		}
```

2022-12-11 22:51 UTC, Amazinite commented on source/System.cpp
> +	return this->invisibleFenceRadius;
```suggestion
	return invisibleFenceRadius;
```

2022-12-11 22:51 UTC, Amazinite commented on source/System.cpp
> +double System::InvisibleFenceRadius() const
Functions should be defined in the same order as they are defined in the header file, which means this function shouldn't be below the price functions.

2022-12-11 22:51 UTC, Amazinite commented on source/System.h
> +	double InvisibleFenceRadius() const;
I would move this up to above the jump range/below the asteroid belts functions.

2022-12-11 22:51 UTC, Amazinite commented on source/System.cpp
> +			invisibleFenceRadius = child.Value(1);
```suggestion
			invisibleFenceRadius = max(0., child.Value(1));
```

2022-12-11 22:51 UTC, Amazinite commented on source/System.h
> +	double invisibleFenceRadius = 10000.;
Same for the variable. Move it to between belts and jump range.

2022-12-11 23:12 UTC, Amazinite commented on source/System.h
> +
```suggestion
```

2022-12-11 23:12 UTC, Amazinite commented on source/System.h
> +	double InvisibleFenceRadius() const;
It's not moved; :| :| :| :|

2022-12-16 19:15 UTC, Amazinite approved these changes

2022-12-16 19:15 UTC, Amazinite commented on source/System.h
> +
```suggestion
	WeightedList<double> belts;
	// The "invisible fence" radius for this system.
	double invisibleFenceRadius = 10000.;
```

2022-12-16 19:16 UTC, Amazinite commented on source/System.h
> +	// The "invisible fence" radius for this system.
```suggestion
```

2022-12-16 19:16 UTC, Amazinite commented on source/System.cpp
> +double System::InvisibleFenceRadius() const
```suggestion
// Get the system's invisible fence radius.
double System::InvisibleFenceRadius() const
```

2022-12-16 19:22 UTC, merged