[Enhancement] Starfield Parallax Layers
endless-sky/endless-sky pull request #7765
Opened 2022-12-03 09:39 UTC by Azure3141

Once again, Azure works on a feature that absolutely no one asked for instead of working on the stuff he actually said he'd do ~~a~~ ~~two~~ three weeks ago

----------------------

## Summary
This adds multiple parallax layers to the background starfield, adding a sense of depth and distance to flight.

-----------------------
**Feature:** This PR implements the feature request detailed and discussed in issue #[Nobody asked for this]

## Feature Details
Pretty much what it says on the tin. Space looks deeper, flight looks a bit cooler.

I have also added a system attribute, "starfield density," that can be used to change the number of stars drawn in the starfield. This can be used to make the galactic core denser, for example, or make the edges of the galaxy more sparse.

You can now also toggle the "Background parallax" setting between three options: off, Fast, and Fancy. Off is off, of course, Fast is the current vanilla behavior, and Fancy uses multiple parallax layers.

## UI Screenshots

https://user-images.githubusercontent.com/42621251/205434383-14138d96-2ae7-42f0-8b79-fa544f1c0d6d.mp4

## Testing Done
I flew around and saw stars doing star things.

## Performance Impact
The starfield is being drawn an additional three times. This doesn't seem to have any performance impact on my laptop, but the implementation is probably very messy and I'd welcome any advice on how to improve it.

2022-12-03 10:38 UTC, Hurleveur requested changes
some things to change, I'm surprised this can be done with so little things modified

2022-12-03 10:38 UTC, Hurleveur commented on source/StarField.cpp
> +		j = 4;
```suggestion
	int passes = Preferences::Has("Parallax background") ? 4 : 1;
```
an alternate way to do the same thing
plz name variables in an explicit manner too, i and j doesnt tell much

2022-12-03 10:38 UTC, Hurleveur commented on source/StarField.cpp
> -
god forbid you touch thy holy whitelines thou dont have to

2022-12-03 10:38 UTC, Hurleveur commented on source/StarField.cpp
> +				glDrawArrays(GL_TRIANGLES, first, count / pow(j, 2.));
```suggestion
				glDrawArrays(GL_TRIANGLES, first, count / pow(passes, 2.));
```
what does pow even do?

2022-12-03 10:38 UTC, Hurleveur commented on source/StarField.cpp
> +	for(float i = 0; i < j; i++)
```suggestion
	for(float i = 0; i < passes; i++)
```
i could have a better name too, and it doesnt have to be `passes` for j just not `j`

2022-12-03 13:08 UTC, Zitchas commented
For some reason I thought we already had parallax? I mean, we don't, really. Just the stars and the haze on different layers. But when I started doing a serious amount of just playing I was actually surprised by the fact that we *didn't* have star parallax. For some reason I was convinced that we did. I know Revamp had it.

Anyway, very much a welcome change. It adds a lot to the game.

2022-12-03 14:10 UTC, McloughlinGuy commented
This looks absolutely amazing. You’re great Azure!

2022-12-03 18:30 UTC, Saugia commented
>For some reason I thought we already had parallax?

We do have parallax with planets, hazes, and ships compared to the starfield. It's one huge split. Maybe you're just used to it. But no, we didn't have layers of *star* parallax - just the stars in parallax with everything else.

That said, this looks pretty good so far. Much better than not having it. 

~It would be cool to someday have every individual star have random speeds of parallax so that it doesn't look like the universe is in sheets, but that's probably way out of our scope.~

2022-12-03 19:33 UTC, Zitchas commented
Revamp had it, and I did a lot of playing in Revamp, so I think that's where my misconception came from. I think one version of the Parallax PR that actually got merged had it too, but that got simplified down to a single layer of stars for some reason.

2022-12-03 20:02 UTC, McloughlinGuy reviewed
I don't know how to code CPP, but I did playtest this, so I'll give my thoughts on its performance. Keep in mind I have an old cruddy laptop. It runs perfectly except for when I'm fully zoomed out or one level below full zoom, then it slows down a lot. So overall, it does relatively good. If it could be optimized a little more that'd be great, but otherwise I like this change a lot.

2022-12-03 22:09 UTC, quyykk commented on source/StarField.cpp
> +	glUseProgram(shader.Object());
Please indent this correctly :)

2022-12-03 22:09 UTC, quyykk commented on source/StarField.cpp
> +				glDrawArrays(GL_TRIANGLES, first, count / pow(layers, 2.));
Use `layers * layers` instead for *performance*.

2022-12-03 22:37 UTC, quyykk commented on source/StarField.cpp
> +		for(float pass = 0; pass <= layers; pass++)
```suggestion
		for(int pass = 0; pass < layers; ++pass)
```

2022-12-03 23:48 UTC, Koranir commented on source/StarField.cpp
> +			for(int gy = minY; gy < maxY; gy += TILE_SIZE)
```suggestion
			for(int gy = minY; gy < maxY; gy += TILE_SIZE)
			{
```

2022-12-03 23:48 UTC, Koranir commented on source/StarField.cpp
> +				}
```suggestion
				}
			}
```

2022-12-03 23:48 UTC, Koranir commented on source/StarField.cpp
> +			}
```suggestion
		}
```

2022-12-03 23:48 UTC, Koranir commented on source/StarField.cpp
> +			glBindVertexArray(0);
```suggestion
		glBindVertexArray(0);
```

2022-12-03 23:48 UTC, Koranir commented on source/StarField.cpp
> +			glUseProgram(0);
```suggestion
		glUseProgram(0);
```

2022-12-04 06:10 UTC, Hurleveur approved these changes
Those perf improvements are impressive
Code looks good to me

2022-12-04 23:29 UTC, Zitchas commented
Those stars almost look like they're on *top* of the "planets". Either way, very cool. When you say that is specified in the map file, is that on a per-system basis? I could see it being really useful to have, say, systems way out on the edge of the galaxy have a low density of stars; while systems in the galactic core might have a high density.

2022-12-09 01:49 UTC, McloughlinGuy approved these changes
Just playtested again, the GPU usage is down to a third of what it was when I first tried it fully zoomed out. Seriously impressive optimization, great job Azure!

2022-12-11 23:21 UTC, quyykk commented
Since the new layers introduce a bit of a performance hit, let's add a "fancy" option to the preference (and turn the existing "on" into "fast")/

2022-12-18 15:18 UTC, McloughlinGuy commented
> Since the new layers introduce a bit of a performance hit, let's add a "fancy" option to the preference (and turn the existing "on" into "fast")/

That sounds like an amazing idea, having the original one be the fancy and having the current be the fast.

2022-12-27 20:23 UTC, Zitchas commented
> [Nobody asked for this]

I've been wanting multiple starfield parallax layers ever since we had a rough sort of implementation of them in Revamp. I just never made a formal feature request anywhere.

2022-12-28 19:28 UTC, quyykk commented on source/PreferencesPanel.cpp
> +			isOn = true;
This will make the preference always on, which it shouldn't be if it's on "off".

2022-12-28 19:28 UTC, quyykk commented on source/StarField.h
> +#include "System.h"
Use a forward declaration (`class System;`) here and #include system in the cpp file.

2022-12-28 19:28 UTC, quyykk commented on source/StarField.cpp
> +		for(int pass = 1; pass <= layers; pass++)
If the density is zero we can skip all this

2022-12-28 19:28 UTC, quyykk commented on source/Preferences.h
> +	static Preferences::BackgroundParallax GetBackgroundParallax();
```suggestion
	static BackgroundParallax GetBackgroundParallax();
```

2022-12-28 20:03 UTC, quyykk commented on source/PreferencesPanel.cpp
> +			isOn = true;
The default is the value you assigned to `parallaxIndex` at the top. This is to control whether the preference entry is highlighted or not.

2022-12-28 21:39 UTC, quyykk commented on source/Preferences.h
> +	static Preferences::BackgroundParallax GetBackgroundParallax();
Oh yeah lol why do they all have the unnecessary prefix lmao

2022-12-28 22:00 UTC, quyykk commented on source/Preferences.h
> +	static Preferences::BackgroundParallax GetBackgroundParallax();
dewit

2022-12-28 22:16 UTC, quyykk commented on source/Preferences.cpp
> +	int parallaxIndex = 0;
Should the default preference for parallax be "fast"?

2022-12-28 22:16 UTC, quyykk commented on source/Preferences.cpp
> +	out.Write("parallax background", parallaxIndex);
```suggestion
	out.Write("Parallax background", parallaxIndex);
```

2022-12-28 22:16 UTC, quyykk commented on source/StarField.cpp
> +	double density = (system == nullptr) ? 1. : system->StarfieldDensity();
```suggestion
	double density = system ? system->StarfieldDensity() : 1.;
```

2022-12-29 05:49 UTC, quyykk commented on source/Preferences.cpp
> +	out.Write("parallax background", parallaxIndex);
The old setting name is capitalized, so let's just keep it like that.

2022-12-29 05:49 UTC, quyykk commented on source/Preferences.cpp
> +	int parallaxIndex = 0;
Ah k. Can you set this here to 1 and then delete the line in Load that sets the value to true?

2022-12-29 07:26 UTC, quyykk approved these changes

2022-12-29 07:28 UTC, merged