"accompany" npcs are allowed to have disabled fighters that are docked in carriers
endless-sky/endless-sky pull request #7845
Opened 2022-12-11 22:05 UTC by UnorderedSigh

**Bugfix:** Addresses #7662

## Fix Details
People have reported that the stormhold battle in Hai Reveal often doesn't complete. In one instance, I found it was because a fighter was disabled, but docked in a carrier. Presently, the logic requires the fighter to not be disabled, so the mission didn't succeed. Of course, since the fighter is already docked, you can't board it to repair it.

The fix I came up with is to consider a docked ship to be accompanied, even if it is disabled. This makes sense because the ship will land inside its carrier, when the carrier lands.

This is co-authored by @Hurleveur 

## Testing Done
Tested a failed attempt at storming stormhold that should have succeeded.

I don't know if there are ways this fix could break things.

## Save File

[Friction Diction~3026-01-21  should work but does not.txt](https://github.com/endless-sky/endless-sky/files/10203381/Friction.Diction.3026-01-21.should.work.but.does.not.txt)

## Performance Impact
One "if" with a bizarre xor became three "if" statements. May lose you a few nanoseconds.

2022-12-11 22:13 UTC, UnorderedSigh commented
There is another half of this bug, for which I don't have a fix. If the fighter is in the carrier, it shouldn't be disabled since the carrier has already "boarded" it.

2022-12-12 07:20 UTC, Hurleveur requested changes
We talked about it already, I think that this way makes a lot of sense.
We shouldnt use a xor anyway since that makes the code harder to read.

That said maybe the last two ifs could be grouped into one but its fine this way.

2022-12-12 07:20 UTC, Hurleveur commented on source/NPC.cpp
> +			bool isCarried = ship->CanBeCarried() && ship->GetParent();
Shouldnt iscarried also check that the ship has no system, meaning that it is in facr in a carrier?
Right now this is more canBeCarried than actually isCarried, I think

2022-12-12 12:37 UTC, UnorderedSigh commented
> That said maybe the last two ifs could be grouped into one but its fine this way.

It is easier to mentally parse if they are split up since the two "else ifs" check different problems.

2022-12-13 17:50 UTC, UnorderedSigh commented
Closing due to merge of #7866

2022-12-13 17:50 UTC, closed without merging