feat(content): New human hails for Free Worlds and Republic
endless-sky/endless-sky pull request #7897
Opened 2022-12-18 01:08 UTC by bene-dictator

**Content (Hails)**

## Summary
Adds 4 new friendly hails for the Free Worlds and 1 new friendly hail for the Republic (inspired by one of the hails by greatkek, and Australian airport announcements). There are also a couple of additions to other hail sets. Some Free Worlds hails are now shared by the Militia, which should give a better idea to the player that the Militia were the precursor to the Free Worlds. If there is a better way to have these hails be shared, please tell me. 

Stand United is a motto on the Militia License. 

## Examples
* Join the Navy, the most rewarding humanitarian organization of Humanity!
* Join the Navy, the most honorable defense force of all mankind!
* By Republic law, civilian warships within Parliament's mandate must comply with indiscriminate structural sweeps by planetary officials upon landing. Please do not attempt to resist. 
* Be warned that all private escorts will undergo random cargo examinations by our Gunboats. We appreciate your compliance. 
* By the decree of Parliament, all merchant vessels in the Republic must perform regular outfit scans by Navy forces. 
* We are Free forces, defenders of liberty.
* We are the Free Worlds, destroyers of evil!
* If you want to strengthen the Free Worlds' struggle for democracy, become a member of the Free forces!
* If you have seen the corruption of Parliament, stand united with us!
* If you have suffered from the loss of our representation, do not hesitate to join the Free Worlds!
* Threats to our Free Worlds beware! The might of the Free Worlds is here!
* We live in a struggle for freedom!
* We rally behind justice! Join the Free Worlds!
* Stand United! Join us!
* Fight for freedom! Fight for the Free Worlds!
* Fight for your rights! Fight for equality!
* Fight against corruption! Fight for equality!

2022-12-18 09:31 UTC, Zireael07 commented
Nitpick: "By the decree of Parliament, all merchant vessels in the Republic must perform regular outfit scans by Navy forces. All unlicensed ships will be fined." sounds like _merchants_ will be scanning _the Navy_, while I think you intended the opposite?

2022-12-18 09:35 UTC, bene-dictator commented
Yes, changing this now.

2022-12-24 21:09 UTC, roadrunner56 requested changes

2022-12-24 21:09 UTC, roadrunner56 commented on data/human/hails.txt
> +		"a spirit"
This doesn't really fit in well with the possible sentence formations here.

2022-12-25 05:08 UTC, bene-dictator commented on data/human/hails.txt
> +		"destroyers of criminals"
I couldn't find a good replacement for "destroyer" unfortunately.

2022-12-25 05:09 UTC, bene-dictator commented on data/human/hails.txt
> +		"freedom"
I noticed this but I decided to ignore it, but I suppose it might be better to get rid of it.

2022-12-25 05:53 UTC, roadrunner56 commented on data/human/hails.txt
> +		"destroyers of criminals"
I'd recommend just removing the lines entirely.

2022-12-25 05:55 UTC, bene-dictator commented on data/human/hails.txt
> +		"destroyers of criminals"
Ended up doing that. Haven't committed the changes yet, just doing some other edits.

2022-12-28 21:11 UTC, Amazinite commented
Still going? :)

2022-12-28 21:12 UTC, bene-dictator commented
Yes, I love writing these, but it's gotta stop at some point...

2022-12-29 21:57 UTC, bene-dictator commented
I don't think I will add any more to this for now. It'd be great if someone else could look over this, and if there's nothing wrong, it's good to go.

2022-12-30 23:14 UTC, a-random-lemurian commented on data/human/hails.txt
>  		"honourable"
```suggestion
		"honorable"
```

ES uses American English. Fix this Bri'ish spelling.

2022-12-30 23:35 UTC, Amazinite requested changes

2022-12-30 23:35 UTC, Amazinite commented on data/human/hails.txt
> +		"I'm convinced there Alphas are running the Republic from there"
```suggestion
		"I'm convinced that Alphas are running the Republic from there"
```

2022-12-30 23:35 UTC, Amazinite commented on data/human/hails.txt
>  		" "
```suggestion
		"Join"
		"Enlist in"
	word
		" the Navy. "
```

2022-12-30 23:35 UTC, Amazinite commented on data/human/hails.txt
>  		"honourable"
```suggestion
		"honorable"
```

2022-12-30 23:35 UTC, Amazinite commented on data/human/hails.txt
> +		"travelling in "
```suggestion
		"traveling in "
```

2022-12-30 23:35 UTC, Amazinite commented on data/human/hails.txt
> +		"Pirate"
```suggestion
		"pirate"
```

2022-12-30 23:35 UTC, Amazinite commented on data/human/hails.txt
> +		"deal with"
```suggestion
		"clear out "
		"deal with "
```

2022-12-30 23:35 UTC, Amazinite commented on data/human/hails.txt
> +		"the long arms of the Law"
```suggestion
		"the long arm of the Law"
```

2022-12-30 23:35 UTC, Amazinite commented on data/human/hails.txt
> +		"Syndicated Security appreciates the voluntary donation of your ship to their training programmes!"
```suggestion
		"Syndicated Security appreciates the voluntary donation of your ship to their training programs!"
```

2022-12-30 23:44 UTC, Amazinite approved these changes

2022-12-30 23:44 UTC, merged