Replace 'on offer' with 'to accept' in jobs requiring outfits
endless-sky/endless-sky pull request #7939
Opened 2022-12-27 01:33 UTC by bene-dictator

## Summary
Changes all 'on offer' for 'to accept' in jobs that require Brigs or Luxury Accommodations. They will now show up in the jobs screen even if you don't have those outfits installed. 

## Testing Done
I haven't yet. I'll get around to it.

2022-12-27 01:37 UTC, warp-core commented
None of these mention the need for these outfits in the description.
Appropriate adjustments should be made to the descriptions or `to offer` should be used instead of `to accept`.

2022-12-27 01:41 UTC, bene-dictator commented
> None of these mention the need for these outfits in the description. Appropriate adjustments should be made to the descriptions or `to offer` should be used instead of `to accept`.
> (Al;so, the tests fail because you need to do `has <condition>`.)

Fair enough... I will do that. Before I had used "blocked" but I didn't think that would work on a job.

2022-12-28 00:32 UTC, Amazinite requested changes

2022-12-28 00:32 UTC, Amazinite commented on data/human/paradise world jobs.txt
> +	description `These <bunks> poor souls have bankrupted themselves attempting to live beyond their means. Due to media scrutiny on the issue, the local government will pay you <payment> to transport t
This is too long (and was probably already too long before).
![image](https://user-images.githubusercontent.com/17688683/209738433-745f338f-4cf2-4e73-bbeb-547c4c96bf28.png)
![image](https://user-images.githubusercontent.com/17688683/209738479-d67e329e-2e0c-4020-8ed0-12c6c76dd182.png)

2022-12-28 00:32 UTC, Amazinite commented on data/human/paradise world jobs.txt
> +	description `These <bunks> non-violent repeat offenders have accepted longer community service sentences that better use their skills in return for serving their time on the Paradise World of <desti
Ditto.
![image](https://user-images.githubusercontent.com/17688683/209738730-b42d8b49-ea80-4e36-aa53-f7de9b50f753.png)

2022-12-28 00:32 UTC, Amazinite commented on data/human/pirate jobs.txt
> +	description "A pirate on <planet> has bought slaves from a local warlord. Transfer these <bunks> slaves to <destination> for <payment>. To keep them from making any trouble, you'll need suitable fac
![image](https://user-images.githubusercontent.com/17688683/209739527-a75c0521-bd61-4522-ab88-7fe96796e682.png)

2022-12-28 01:30 UTC, bene-dictator commented
Thanks for testing those! Some of them might just need changing from `<destination>` to `<planet>`, but I'll try to change the text first because `<destination>` seems to be used more here than `<planet>` for mission summaries.

2022-12-28 03:45 UTC, bene-dictator commented
![Screenshot_20221228_164107](https://user-images.githubusercontent.com/115441627/209753960-ac622b52-a342-48fb-8278-6372b2a0f353.png)
Just had this mission... Farpoint is a notoriously exotic planet.

2022-12-30 04:08 UTC, Amazinite approved these changes

2022-12-30 04:11 UTC, merged