feat(graphics): Add a brown haze to systems that are in the center of the dust nebula
endless-sky/endless-sky pull request #7960
Opened 2022-12-28 05:02 UTC by RisingLeaf

**Content (Artwork)**

## Summary
With the new map sprite ( at least I think it comes with the new one), there is some sort of nebula that extends in a curve from talita and ends somewhere in front of gegno space.
<img width="604" alt="Screenshot 2022-12-27 at 8 55 34 PM" src="https://user-images.githubusercontent.com/85687254/209759776-36ab1402-6620-4f9a-a7a6-782e383f938c.png">

This PR adds a brown haze to all systems that are in the center of this nebula, just to add some spice to the game (I always have great fun finding a system that is different.

Because I do want to keep it something that is not very common, only the following systems have this haze:

- Almaaz
- Chirr'ay'akai
- "Ehma Ti"
- Kiru'kichi
- Mebsuta
- Mirzam
- Unagi

## Save File
Just go to the systems.

## Artwork Checklist
 - [ ] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [ ] The Image I added is the asset as it just a hue adapted version of the red haze
 - [ ] I do not know if haze is included in the 2x?

2022-12-28 05:14 UTC, RisingLeaf commented
screenshot added

2022-12-28 07:13 UTC, MasterOfGrey commented
Nice.

You'll also want to add it to the "Al Hurr" system which is in `Hai Reveal 6.txt` which is also put smack in that Nebula.

2022-12-28 08:00 UTC, EjoThims approved these changes

2022-12-28 10:53 UTC, Saugia commented
Agree with Azure. If we want to add new bg haze because of the sprite, use the same method for regular haze. EW, etc. haze is unique and only intended for their respective areas.

2022-12-28 11:28 UTC, Quantumshark commented
I agree that this needs to be more distinct from the Ember Waste haze.
I am red-green colourblind, and to me this looks almost identical to the red haze in the Ember Waste.

2022-12-28 12:09 UTC, beccabunny commented
An option could the the one of using multiple hazes - for instance, both the standard blue haze and this new one - together for a less EW-like effect, by putting them as frames of the same animation but without specifying anything else in the data. E.g. haze-brown+0 being this and haze-brown+1 being the standard blue haze

2022-12-28 21:07 UTC, RisingLeaf commented
Using multiple hazes now

2022-12-28 21:08 UTC, RisingLeaf commented
> Nice.
> 
> You'll also want to add it to the "Al Hurr" system which is in `Hai Reveal 6.txt` which is also put smack in that Nebula.

is in

2022-12-28 21:09 UTC, RisingLeaf commented
also it is adpated from the standard haze now

2022-12-29 01:19 UTC, Saugia requested changes

2022-12-29 01:19 UTC, Saugia commented on copyright
> +Comment: Created on base of haze-133 (no copyright given).
Just making it a bit cleaner.

```suggestion
Comment: Derived from _menu/haze-133 (no copyright given).
```

2022-12-30 16:27 UTC, Saugia approved these changes

2022-12-30 16:28 UTC, merged