Use CMake for building on Linux in CI
endless-sky/endless-sky pull request #8094
Opened 2023-01-10 19:22 UTC by quyykk

## Feature Details

This replaces scons with CMake when building on Linux in the CI environment.

## Testing Done

CI will test everything.

2023-01-10 21:16 UTC, quyykk commented
Release is here: https://github.com/quyykk/endless-sky/releases/tag/v16linux2

I tested it and it works!

2023-01-12 13:28 UTC, MCOfficer requested changes
What's the reason for yeeting entire test jobs?

2023-01-12 13:28 UTC, MCOfficer commented on .github/workflows/cd.yaml
> +          sudo apt install -y --no-install-recommends libxmu-dev libxi-dev libgl-dev libglu1-mesa-dev libgles2-mesa-dev libwayland-dev libxkbcommon-dev libegl1-mesa-dev
```suggestion
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libxmu-dev libxi-dev libgl-dev libglu1-mesa-dev libgles2-mesa-dev libwayland-dev libxkbcommon-dev libegl1-mesa-dev
```
Should still be `apt-get` for automated invocations

2023-01-12 13:28 UTC, MCOfficer commented on .github/workflows/cd_release.yaml
> +          sudo apt install -y --no-install-recommends libxmu-dev libxi-dev libgl-dev libglu1-mesa-dev libgles2-mesa-dev libwayland-dev libxkbcommon-dev libegl1-mesa-dev
```suggestion
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libxmu-dev libxi-dev libgl-dev libglu1-mesa-dev libgles2-mesa-dev libwayland-dev libxkbcommon-dev libegl1-mesa-dev
```
dito

2023-01-12 13:28 UTC, MCOfficer commented on .github/workflows/ci.yml
> +        sudo apt install -y --no-install-recommends libxmu-dev libxi-dev libgl-dev libglu1-mesa-dev libgles2-mesa-dev libwayland-dev libxkbcommon-dev libegl1-mesa-dev libosmesa6 mesa-utils libglvnd-d
```suggestion
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libxmu-dev libxi-dev libgl-dev libglu1-mesa-dev libgles2-mesa-dev libwayland-dev libxkbcommon-dev libegl1-mesa-dev libosmesa6 mesa-utils libglvnd-dev
```

2023-01-12 14:09 UTC, quyykk commented
> What's the reason for yeeting entire test jobs?

Oh yeah I forgot to add a comment. The only one I removed is the memory leak test, because it's not really useful, it only checks memory errors and leaks during parsing. I'd rather add sanitizers to the integration tests than run valgrind during parsing.

2023-01-21 13:22 UTC, petervdmeer commented
When I run the unit-tests through scons, then I get a nice overview of the amount of assertions and test-cases:
```
$ scons test
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
Running tests...
===============================================================================
All tests passed (75921 assertions in 60 test cases)

scons: done building targets.
```



While [running the unit-tests through CMake](https://github.com/quyykk/endless-sky/blob/use-cmake-on-linux/readme-cmake.md) does not seem to tell me this:
```
$ ctest --preset linux-test
Test project /home/peter/[...]/endless-sky/build/linux
1/1 Test #71: unit
100% tests passed, 0 tests failed out of 1

Label Time Summary:
unit    =   0.07 sec*proc (1 test)

Total Test time (real) =   0.30 sec
```

Is it possible to also list the amount of assertions and test-cases as is done with Scons?

2023-01-21 13:32 UTC, petervdmeer commented
And can we extend the instructions at https://github.com/quyykk/endless-sky/blob/use-cmake-on-linux/readme-cmake.md with a method to run the integration tests on linux without xvfb? (Just directly on the running X-server?)

2023-01-21 13:39 UTC, petervdmeer commented
> And can we extend the instructions at https://github.com/quyykk/endless-sky/blob/use-cmake-on-linux/readme-cmake.md with a method to run the integration tests on linux without xvfb? (Just directly on the running X-server?)

Probably best that we describe that in https://github.com/quyykk/endless-sky/blob/use-cmake-on-linux/tests/integration/README.md, and just link to the higher level test-directory from the CMake list of tests. (For more tests, see ../tests/README.md .)

2023-01-21 14:17 UTC, quyykk commented
> Is it possible to also list the amount of assertions and test-cases as is done with Scons?

Amount of test cases yes, it would look like this:

```
$ ctest --preset linux-test
Test project /home/user/projects/endless-sky/build/linux
58/58 Test #58: Truncate enum
100% tests passed, 0 tests failed out of 58

Label Time Summary:
unit    =   0.53 sec*proc (58 tests)

Total Test time (real) =   0.57 sec
```

(58 test cases instead of 60 because this is from an older build). But this can only be done once we drop SCons .Alternatively, you can pass `--verbose`. I could enable that by default, but it produces a lot of unnecessary output:

```
$ ctest --preset linux-test --verbose
UpdateCTestConfiguration  from :/home/user/projects/endless-sky/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/user/projects/endless-sky/build/linux/DartConfiguration.tcl
Parse Config file:/home/user/projects/endless-sky/build/linux/DartConfiguration.tcl
Test project /home/user/projects/endless-sky/build/linux
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 71
    Start 71: unit

71: Test command: /home/user/projects/endless-sky/build/linux/tests/Debug/endless-sky-tests
71: Working Directory: /home/user/projects/endless-sky/tests
71: Test timeout computed to be: 1500
71: ===============================================================================
71: All tests passed (75924 assertions in 60 test cases)
71: 
1/1 Test #71: unit .............................   Passed    0.05 sec

100% tests passed, 0 tests failed out of 1

Label Time Summary:
unit    =   0.05 sec*proc (1 test)

Total Test time (real) =   0.14 sec
``` 

If you run the benchmarks, you'll notice that it uses verbose as well. Unfortunately it's the only way to see the output :frowning: 

> And can we extend the instructions at [quyykk/endless-sky@use-cmake-on-linux/readme-cmake.md](https://github.com/quyykk/endless-sky/blob/use-cmake-on-linux/readme-cmake.md?rgh-link-date=2023-01-21T13%3A32%3A44Z) with a method to run the integration tests on linux without xvfb? (Just directly on the running X-server?)

That's what the debug version of the integration tests is for. I don't think it's useful to see the non-debug integration tests running because it is way too fast.

2023-01-21 15:47 UTC, petervdmeer approved these changes

2023-01-21 15:49 UTC, petervdmeer commented
> (58 test cases instead of 60 because this is from an older build). But this can only be done once we drop SCons

I would like to see this done in a follow-up.

2023-01-21 20:55 UTC, MCOfficer approved these changes

2023-01-21 21:33 UTC, merged