Fix(content): Restricting "Local Politics" mission from triggering on Albatross and Bloodsea after joining the FW.
endless-sky/endless-sky pull request #8114
Opened 2023-01-13 17:29 UTC by Zitchas

**Bugfix:** This PR addresses an issue I ran into while playing the game

## Problem

While playing through the FW campaign I eventually managed to peacefully convince Albatross to join the FW by building them a spaceport. Shortly thereafter when visiting the planet I got the "Local Politics" mission, where I arrive to find a deserted spaceport and nothing but a note letting their overlord know where to find the yearly tribute.

> As you land on the pad, you note a general lack of presence around the spaceport. No one has scrambled to hook up your ship, nor has anybody else acknowledged your arrival. Instead, when you leave your ship, all you find is a note within the spaceport detailing where their "overlords" can find their yearly tribute.
> You decide against finding out where the inhabitants went.

This seemed really jarring to me, because suposedly they were under the control of warlords and pirates up until they joined the FW and were freed from pirate domination. So this mission shouldn't be happening.

I checked the offer conditions, and discovered that it *only* offers on Free Worlds planets. 

This doesn't make sense, as the tone and description of this mission sound like something that should be encountered while the planet is under Pirate dominion. (or, perhaps, if the FW forcibly invaded and occupied it). It is completely counter to the tone and text of the missions convincing it to join the FW.

I see two possibilities here:
1. This is intentional, and is meant to convey that either the locals consider the FW to be overlords and the FW is treating them as such. (hence accepting taxes via tribute-style handovers), or
2. This is unintentional, and is meant to be something the player runs into before the FW have become effective in combating and reducing piracy, and helps set the tone for why the FW is needed in the first place.

From my experience playing the game, having peacefully convinced them to join the FW by *not* invading and instead providing the resources and expertise to build a spaceport; having them turn around and offer tribute in this manner that very clearly indicates that they do not want to see or even risk being seen by the person collecting it... That either indicates that the FW failed and this planet is still effectively a pirate planet, or that the FW is no better than a pirate. 

## Fix Details
Changes this mission to only show up on:
- Republic or Pirate worlds that have the "Frontier" attribute and are not stations.
- Albatross or Bloodsea *before* joining the FW

## Testing Done
Played the game.

## Save File
This is the closest save I have to before the conquer or spaceport decision. The Local Politics mission itself can be tested by any pilot, on any Pirate or Republic planet that has the Frontier attribute, at any time. It just takes a lot of iteration to hit that random < 1 chance.

[Rebbia Rampart~3026-04-01 Dreadnought Reveal.txt](https://github.com/endless-sky/endless-sky/files/10413767/Rebbia.Rampart.3026-04-01.Dreadnought.Reveal.txt)

Note: I originally was trying to enable this to also show up if the FW invades and occupies bloodsea, but that adds a lot of extra complexity that frankly I don't think is worth the time and effort for a one-off <1 chance encounter. It'd be a lot easier if we could check the government inside the to offer conditions, but it doesn't even look like we can use flagship system attributes, only flagship planet attributes, so we'd need to add government tags to all these eligible planets, and then modify the events to change them all when appropriate.

2023-01-17 09:11 UTC, Hurleveur requested changes
fixes

2023-01-17 09:11 UTC, Hurleveur commented on data/human/culture conversations.txt
> +				not planet Bloodsea
```suggestion
				not "flagship planet: Albatross"
				not "flagship planet: Bloodsea"
```

2023-01-17 09:11 UTC, Hurleveur commented on data/human/culture conversations.txt
> +				planet Albatross
```suggestion
				has "flagship planet: Albatross"
```

2023-01-17 09:11 UTC, Hurleveur commented on data/human/culture conversations.txt
> +				planet Bloodsea
```suggestion
				has "flagship planet: Bloodsea"
```

2023-01-17 10:52 UTC, Hurleveur approved these changes
it should work data wise, though I am a bit confused by whats going on here

like I'd expect it to trigger on any world that has both pirate and frontier attributes but content side isnt my jam I just made sure it works as you want it to (this triggering on frontier republic worlds could be weird)

2023-01-24 21:44 UTC, warp-core commented
https://github.com/endless-sky/endless-sky/pull/6494#issue-1110245333

Grey wrote:
> For implementation including the mission structure, source locations or miscellaneous grammar fixes that'll be me.

2023-01-25 01:32 UTC, MasterOfGrey commented
The idea here was that it would show up on lightly inhabited/defended FW planets who might reasonably have a tribute arrangement with individual pirate lords who show up occasionally to collect.

You're right in that it absolutely shouldn't show up on Albatross or Bloodsea after they've joined - they're not lightly defended and wouldn't be bowing to any pirate lords, since their leadership almost certainly contains at least some pirate-adjacent power-brokers who likely still have leverage and connections.

It should be frontier FW, not Republic or Pirate, planets though. Or arguably you could include the Dirt Belt if you were feeling fancy but I'd prefer an alternative variant on those.

Perhaps some planets could be selectively excluded after those worlds join, but I'd want to do a check on all FW frontier planets to confirm where they all are before ruling out the event entirely once those two join.

2023-01-25 02:44 UTC, Zitchas commented
Why shouldn't it show up on frontier Republic worlds? The Republic not providing adequate naval presence was *precisely* the reason for the whole FW situation to begin with. I'd more likely expect to see this on a Republic frontier world than on a FW one.

2023-01-25 06:08 UTC, MasterOfGrey commented
Having done a quick skim through the map files, actually it occurs to me it should be: 
```
		government
			not "Pirate"
		attributes "frontier"
		attributes "south"
```
Then possible relevant checks for if the FW have dealt with the pirate worlds in some way.
It is intentionally geographically bound to the potential domain of the southern pirates.

Side Note: Solace probably shouldn't have the `frontier` tag.

2023-01-25 19:57 UTC, Zitchas commented
Why "not pirate" ? All our pirate worlds sound like the sorts of places where tribute is probably being paid to someone or other.

"not FW" is probably more accurate.

2023-01-31 00:02 UTC, MasterOfGrey commented
> Why "not pirate" ? All our pirate worlds sound like the sorts of places where tribute is probably being paid to someone or other.

On "pirate" worlds the spaceport is controlled by pirates - that's what makes them "pirate" worlds. You'd hardly have a spaceport abandoned and full of tribute to a pirate on a world where they control the spaceport.

> My current thought is that there shouldn't be any such arrangements in FW space, because they formed the FW specifically to get out of such arrangements.

These things take time to take effect. At the start of the game they're only just starting to take effective action, and then they end up in a war...
Prior to the FW dealing with the pirate worlds in the plot - they've formed up to get out of those arrangements, but they haven't *actually* carried out the actions necessary to do so. Until they actually commit the resources to doing something about it, forming up as the FW to fight piracy is just putting up a sign that says, "Hey, we're gonna try and stop you."
... but it's not like those worlds haven't presumably tried other things to stop them beforehand. 
You can slap a new label on a bunch of planets - it means nothing to plunderers. 

The plot even makes mention of the fact that pirate depredations haven't been dealt with - that's the whole reason why you have to do something about it during the FW plot in the first place.

2023-01-31 00:19 UTC, Zitchas commented
> On "pirate" worlds the spaceport is controlled by pirates - that's what makes them "pirate" worlds. You'd hardly have a spaceport abandoned and full of tribute to a pirate on a world where they control the spaceport.

From my perspective, we have pirates, and we have Pirates. Just because the locals owe tribute to a Pirate doesn't mean that every pirate in the place (much less the local workers, shopkeepers, etc) is part of the dominant group, nor even particularly friendly to them. Pirates are kind of notoriously not unified forces, and are mostly independent people who just happen to stay out of each other's way and shoot merchants.

Likewise, just like the player doesn't actually *own* the spaceport of a planet they have dominated, they just have unfettered access to it, I'd expect that the pirates that are owed tribute are *not* owners and regular inhabitants, but rather warlords that show up now and then to collect payment. Based on the descriptions we have, I'd expect this just as much from "pirate" worlds (which tend to be mostly independent, anarchist, or just poor worlds that have had a long enough run of pirate domination that people just write it off as being the place where pirates are) as any other world.

2023-02-05 16:24 UTC, warp-core reviewed
I agree with Zitchas. If worlds that have joined the Free Worlds still need to pay tribute to pirates, the Free Worlds has failed before it began, and it should be rapidly losing support.

Regarding the pirate worlds, it comes up frequently that not everyone on these worlds is a pirate, they may not even all support piracy. Certainly, the spaceports aren't controlled directly by actual pirates, this is evidenced by the fact that we are not attacked from the ground when we are conducting outreach to the pirates during the FW story. The one time we are attacked, on Thule, it comes from above. On Albatross, the pirate currently receiving tribute from the locals is not even there. The arrangement that is described there is exactly the sort of thing this mission seems to be about, and it absolutely does not make sense for this to continue after they join the Free Worlds, not if we are to believe that their continued membership of the FW is voluntary.

There may be exceptions, however. New Tortuga, for example, but that one doesn't have the `frontier` attribute so this mission won't occur there anyway.

2023-02-05 16:24 UTC, warp-core commented on data/human/culture conversations.txt
> +				has "flagship planet: Bloodsea"
These events change change the governments to Free Worlds, so by not including that government in the source filter, you've already prevented the mission from offering on these planets after these events occur.

2023-02-07 03:18 UTC, MasterOfGrey commented
> The plot even makes mention of the fact that pirate depredations haven't been dealt with - that's the whole reason why you have to do something about it during the FW plot in the first place.

> If worlds that have joined the Free Worlds still need to pay tribute to pirates, the Free Worlds has failed before it began, and it should be rapidly losing support.

I'm gonna repeat this because I feel it bears repeating. Last time I checked: The *current* plot, *specifies*, that it *hasn't worked **yet***.

2023-02-20 05:44 UTC, MasterOfGrey commented
> > On "pirate" worlds the spaceport is controlled by pirates - that's what makes them "pirate" worlds. You'd hardly have a spaceport abandoned and full of tribute to a pirate on a world where they control the spaceport.

Z
> Just because the locals owe tribute to a Pirate doesn't mean that every pirate in the place (much less the local workers, shopkeepers, etc) is part of the dominant group, nor even particularly friendly to them. Pirates are kind of notoriously not unified forces, and are mostly independent people who just happen to stay out of each other's way and shoot merchants.
> 
> Likewise, just like the player doesn't actually _own_ the spaceport of a planet they have dominated, they just have unfettered access to it, I'd expect that the pirates that are owed tribute are _not_ owners and regular inhabitants, but rather warlords that show up now and then to collect payment.

Warp
> Regarding the pirate worlds, it comes up frequently that not everyone on these worlds is a pirate, they may not even all support piracy. Certainly, the spaceports aren't controlled directly by actual pirates, this is evidenced by the fact that we are not attacked from the ground when we are conducting outreach to the pirates during the FW story. The one time we are attacked, on Thule, it comes from above.

Since Z compulsively updates and it's prompted me again (note, my above point still stands and has not been addressed), I thought I should properly address some comments here.

The simple fact is that on most worlds designated "pirate" worlds. Whoever the authorities are that are running those spaceports, are willing to deny you landing permissions based on your reputation with the actual pirates.
That means, whether those people are pirates or not, those worlds are fundamentally pirate-aligned authorities. Authorities who allow you to land only by other means such as:
- When you land there by domination: effectively identifying yourself as competing interest of comparable or superior strength to whichever pirates they normally deal with. (overpowering the authorities)
- When you bribe your way into landing: having greased the palms of those authorities adequately that they've decided it's worth their while to allow you access/whatever in spite of whatever disgruntlement it may cause their other pirates, possibly because you've bribed them enough to bribe the pirate lords to not worry about it. (leveraging the authorities)
- When you've gone there for reasons pertaining to the plot: having worked with larger governments and people of more significant resources to convince the authorities of a superior outcome for choosing your side. (negotiating the authorities)

These are not worlds that are"just poor worlds that have had a long enough run of pirate domination that people just write it off as being the place where pirates are" - worlds such as those would have no power or inclination to prevent you from landing normally.

Nor does this necessarily mean that the world *supports* piracy. However, it does mean that the authorities governing it have found it prudent to exert their authority in alignment with the interests of those pirates, even if only for self-preservation.
This is what you're seeing on Albatross. 

> If worlds that have joined the Free Worlds still need to pay tribute to pirates, the Free Worlds has failed before it began, and it should be rapidly losing support.
> [...]
> it absolutely does not make sense for this to continue after they join the Free Worlds, not if we are to believe that their continued membership of the FW is voluntary

To return to this point in the context of my previous response.
The order of events is fairly basic:
1. You join up together to tackle a problem.
2. You actually tackle the problem.
3. You succeed or fail at tackling the problem.

The FW plot explicitly deals with the handling of the pirate problem. Which means that until the plot deals with Greenrock, **they're still at step 1**.
The actions you take during the plot *are* Step 2. 
*Right up until that point*, there are worlds in the FW that are suffering pirate depredations.
If there weren't, *then you wouldn't have to deal with Greenrock...*

Hence, this should occur:
- in the south
- on frontier worlds
(Ergo what I said before:)
```
		government
			not "Pirate"
		attributes "frontier"
		attributes "south"
```
Any time prior to the pirate issue being dealt with by the plot:
```
	to offer
		not "event: fw suppressed Greenrock"
```

2023-02-20 16:28 UTC, Zitchas commented
Thanks for suggesting some new ideas. I've revised the conditions, and while not being able to test for the flagship planet government makes it less satisfactory, I think it should get a bit of what you're talking about.

That being said, I disagree about the pirate worlds. Not anything that you've said about them, just the final interpretation of how that impacts this event. No matter how much the local authorities may be forced to align with pirates in terms of their enforcement of landing privledges and the like, nothing says that they like or want to actually come face to face with the pirates coming to collect the tribute. An overlord is likely to take what they want, and while press gangs haven't been explicitly mentioned, I'd say it's fairly likely that said overlords may well forcibly recruit people onto their ships to fill gaps. Best way to avoid having your stuff taken or be recruited is to not be present. So having people not be present when the pirates arrive for their tribute is just as applicable to pirate worlds as anywhere else.

I also somewhat disagree with your assessment of the situation on Free Worlds. Step 2 isn't a binary "you have or you haven't" thing, it's a long progression. The Greenrock suppression is definitely the most stand-out big step in that process, but it's far from the only one. They start taking steps to tackle piracy right from day 1. Just the simple act of having militias forming (most of which are fairly independent and are enthusiastically stomping on pirates whenever they find them) is going to have a significant impact right there.

So, the new conditions on this now target three situations: (the "frontier" and "not station" part remain unchanged and universal)
- South pirate planets
- Pre-war any south planet
- During the war but pre-Greenrock south planets.

The first two have been given boosted incidence rates (up from <1 to <5), and the last has the normal <1.

This means that, assuming the player is even in this area before the war starts, they are more likely to run into this mission and get a hint of the problems of piracy.

Once the war starts, they retain a higher chance of running into this on a Pirate world, but the normal lower chance to run into it on a non-pirate world. And by "lower", I mean the current 1% chance.

Once the Greenrock suppression happens, the only place this mission can be encountered is on pirate planets.

Ideally, this would differentiate between FW and Republic worlds, but with increased Navy presence from the war, I suppose it's reasonable to think that the Greenrock suppression probably benefits the whole area, not just the FW.

2023-02-20 23:10 UTC, MasterOfGrey commented
I'm not sure that it would make sense for this to be encountered on a pirate planet under the circumstance where you've done any of either overpowering, leveraging, or negotiating the authorities though...

So if it appears on a pirate planet, maybe it needs to have positive rep for that landing? 
That way your landing would've been unobstructed to encounter this. 

It should also exclude Greenrock from the source in this case, since that world actually is explicitly governed by pirate interests and it has the attributes that would allow it to trigger there.


P.S. Can we remove the frontier tag from Solace while we're here? It would be wildly inappropriate for this to trigger there, and I don't think anything else which targets `frontier` worlds makes a lot of sense to go there either.

2023-02-23 21:23 UTC, Zitchas commented
I think changing solace should be a different PR, I don't have the energy to check every job or use of the frontier tag to see if it fits or not.

I think I'm pretty much done with this PR. I appreciate your efforts at an explanation, but I still don't see any reason that the general population would stick around to give the warlord who takes the tribute a chance to pressgang them, no matter who the people are in charge. (also, they may well have all left between when I bribed the control tower and when I actually reach the ground. It's most likely at least a few minutes, and people can make themselves scarce in seconds). 

I'm not changing anything more at this point. If people want this in, then do so, otherwise this is being deleted in about a week.

2023-02-24 00:14 UTC, MasterOfGrey commented
At a minimum this needs to not trigger on Greenrock. Period.

2023-02-24 00:38 UTC, Zitchas commented
Pirate worlds can be paying tribute to other pirates just as surely as any other planet. Otherwise the player (many of whom are effectively pirates) couldn't demand tribute from pirate worlds. And they are just as likely to not want to meet their oppressor.

2023-02-24 00:55 UTC, Zitchas commented
Just rereading the description again, and I'll point out a relevant thing: There is absolutely nothing that identifies who they're paying tribute to, just a mysterious "overlord." It could be a pirate, it could be a merchant-captain with a warfleet, it could be a corrupt Navy admiral (although this seems very unlikely given the way the Navy is portrayed, but it is possible.), it could be a mafia enforcer from some criminal organization on virtually any planet... We don't know.

We *assume* that it is pirates based on the range of planets it can occur on, but that's just an assumption.

2023-03-18 21:22 UTC, Amazinite commented on data/human/culture conversations.txt
>  		not attributes "station"
To prevent this from offering on Solace.
```suggestion
		not attributes "station" "urban"
```

2023-03-18 21:33 UTC, Amazinite commented on data/human/culture conversations.txt
>  		attributes "frontier"
Any planet with "south pirate" also has the "south" attribute. Therefore, we can simplify the offer conditions a bit.
```suggestion
		attributes "frontier"
		attributes "south"
```

2023-03-18 21:33 UTC, Amazinite commented on data/human/culture conversations.txt
> +				has "flagship planet attribute: south"
Removing redundant attribute checks.
```suggestion
			and
				random < 5
				or
					has "flagship planet attribute: south pirate"
					not "event: war begins"
			and
				random < 1
				has "event: war begins"
				not "event: fw suppressed Greenrock"
```
"Any southern frontier non-station, non-urban world (from the source filter) where either the war hasn't begun, the world has the south pirate attribute, or the war has begun but the FW haven't handled piracy." Is that the intended offer location? Note that we do not remove the "south pirate" attribute from pirate planets after they change their government, so this actually still allows pirate worlds that have changed sides to the FW to get this mission to offer. I imagine that if we don't want this to offer, then we should be removing those attributes where appropriate from events.txt.

2023-03-28 23:35 UTC, merged