feat(ui): Hide storage on planets without outfitters
endless-sky/endless-sky pull request #8215
Opened 2023-01-26 23:02 UTC by TomGoodIdea

## Feature Details
If there are outfits stored on a planet that doesn't have an outfitter, it makes storage on such planet unusable. This may happen, for example, if outfitters are removed by some events (like in Wanderer storyline).

This PR hides any in-game information about storage on planets without outfitters. The storage itself is left untouched in the pilots's save, so it'll be available again if the outfitter is reinstated.

## Testing Done
Checked how it works: there's no storage indicator on the map; tooltip on hover doesn't show storage data, the same for the side panel.

## Performance Impact
No performance impact.

2023-01-26 23:18 UTC, RisingLeaf requested changes

2023-01-26 23:18 UTC, RisingLeaf commented on source/MapPanel.cpp
> +			if(!system || !planet->HasOutfitter())
if your changes are right, there should be no outfits stored on planets without outfiter

2023-01-26 23:18 UTC, RisingLeaf commented on source/MapOutfitterPanel.cpp
> +					if(planet.HasOutfitter())
```suggestion
					// You can only store outfits if the planet has an outfitter
					if(planet.HasOutfitter())
```

2023-01-27 17:12 UTC, daggs1 commented
question, what will happen in the case the outfitter will never get reinstated?
theoretically, the player will never regain access to the outfits.
I'd agree that these outfits cannot be installed as there is no outfitter, but why the player cannot at least attempt to access it in order to load it into his cargo hold?

2023-01-28 13:36 UTC, TomGoodIdea commented
@RisingLeaf this PR only changes the map UI, not the storage mechanics.

2023-01-29 17:25 UTC, daggs1 commented
> @RisingLeaf this PR only changes the map UI, not the storage mechanics.

can they be extracted in anyway in such case?

2023-02-03 22:58 UTC, quyykk approved these changes
Thanks!

2023-02-03 22:58 UTC, merged