bugfix: Fix fighters choosing boarding targets
endless-sky/endless-sky pull request #8305
Opened 2023-02-06 00:03 UTC by tibetiroka

**Bugfix:** This PR fixes a subset of #8228

## Fix Details
Some remnant fighters and drones spawn with 'disables' and 'plunders', which causes them to choose disabled 'olofez az targets - but they cannot actually shoot at them or board them, so they just stay there.

This PR makes it so any ship that cannot board and cannot attack disabled ships will not target them.

## Testing Done
It seems to stop remnant fighters and drones from grouping up on the korath drones.

## Save File
[Test Pilot.txt](https://github.com/endless-sky/endless-sky/files/10615157/Test.Pilot.txt)

2023-02-06 00:21 UTC, RisingLeaf requested changes

2023-02-06 00:21 UTC, RisingLeaf commented on source/AI.cpp
> +		// Ships that cannot board or shoot at disabled enemies should not pick them as targets.
```suggestion
		// Fighters or Drones that cannot board or shoot at disabled enemies should not pick them as targets.
```

2023-02-06 00:32 UTC, RisingLeaf approved these changes

2023-02-06 00:37 UTC, warp-core commented
What if you add ` && !ship.CanBeCarried()` to line 1217?

2023-02-06 23:11 UTC, merged

2023-02-10 15:26 UTC, Zitchas commented
Question: Why couldn't petrels or terns board the targeted ships?