Add content box to bank/planet/spaceport/trading panels
endless-sky/endless-sky pull request #8535
Opened 2023-03-11 17:27 UTC by thewierdnut

Defaults to the old values, but allows users to move the rendered text via plugin.

-----------------------
**Bugfix:** This PR addresses issue #6750

## Fix Details
Support a "content" box for the bank, panel, spaceport, and trading panels, which defines where the text should be rendered. 

## Testing Done
Verified that the text for all four panels is in the correct position with the default content, and verified that they can be moved with a plugin. 

## Plugin
This is the plugin I bundle with endless mobile to reduce the vertical space used by the default dialogs. It moves the text closer to the center of the screen.

[compact_layout.zip](https://github.com/endless-sky/endless-sky/files/10949060/compact_layout.zip)

2023-03-14 23:04 UTC, warp-core requested changes
Do we usually define defaults in the C++ code for parameters provided by the interface file like this?
I think you should remove the defaults and define the default boxes in the interface definitions, so the game actually makes use of them. This will also make it clearer to anyone looking at hte interface definitions that this box can be modified there.

2023-03-15 01:15 UTC, thewierdnut commented
> I think you should remove the defaults and define the default boxes in the interface definitions

I'm ok with this plan (its how I have it implemented on my fork), but my hesitation was that if somebody already has a plugin that overrides the interfaces.txt, then requiring the new content field would break them.

2023-03-15 23:16 UTC, warp-core commented on data/interfaces.txt
Is there a clear reason why some panels used 78 and others use 80 for their FIRST_Y?
If not, I think we should just use 80 for all of them, and just define this box in the `planet` interface, from which each of the other panels should get it, since that's where the buttons are defined and the content is supposed to go in-between them all; it doesn't really make sense to reposition that between the different panels but not moe around the buttons.

2023-03-15 23:37 UTC, thewierdnut commented on data/interfaces.txt
I don't know where the FIRST_Y numbers came from. 

I'm not sure it makes sense to use the `planet` interface for all of them since most of the panels have their own interfaces defined. I would have to load both interfaces to get the relevant information to render it, which would make the code more cluttered. 

If you still want me to do it that way, I will, I just don't agree with you.

2023-03-15 23:45 UTC, thewierdnut commented on data/interfaces.txt
FYI using 80 pixels looks ok on the trade and planet panels, but the bank panel is slightly out of alignment with its header line. I can probably fix that too, but I wonder if that is out of scope for this change.

2023-03-15 23:54 UTC, warp-core commented on data/interfaces.txt
You only need to retrieve the interface when getting the box:
`const Rectangle box = GameData::Interfaces().Get("planet")->GetBox("content");`

Though, I can see other reasons not to do it that way. It can stay if you prefer.

Looking at the 78 vs 80 thing in game, I suppose we can do it another time.

2023-03-15 23:55 UTC, warp-core commented on data/interfaces.txt
> +		from -300 78 to 180 355
This one *should* be 80, though.

2023-03-16 20:19 UTC, warp-core commented on data/interfaces.txt
> +		from -310 78 to 190 355
The existing `FIRST_Y` in the trade panel seems to be 80.
```suggestion
		from -310 80 to 190 355
```

2023-03-16 20:19 UTC, warp-core commented on source/TradingPanel.cpp
> +		FillShader::Fill(Point(MIN_X + 250., FIRST_Y + 20 * selectedRow + 33), Point(480., 20.), back);
The `Point` being created with literal values should use the content box width minus some border (the default is 20 but that should perhaps be a value stored in a const) as its x value.

2023-03-16 20:32 UTC, thewierdnut commented on source/SpaceportPanel.cpp
> +	, ui(*GameData::Interfaces().Get("spaceport"))
What do you mean by "this"?

2023-03-16 21:32 UTC, warp-core commented on source/TradingPanel.cpp
> +		FillShader::Fill(Point(MIN_X + box.Width()/2, FIRST_Y + 20 * selectedRow + 33), Point(480., 20.), back);
```suggestion
	{
		const Point center(MIN_X + box.Width() / 2, FIRST_Y + 20 * selectedRow + 33);
		const Point dimension(box.Width() - 20., 20.);
		FillShader::Fill(center, dimensions, back);
	}
```

2023-03-17 18:24 UTC, warp-core approved these changes

2023-03-17 18:26 UTC, merged