Move all indigenous creatures to one folder and clean up
endless-sky/endless-sky pull request #8616
Opened 2023-04-01 11:01 UTC by TomGoodIdea

**Data Refactor**: This PR addresses an issue discussed on Discord: https://discord.com/channels/251118043411775489/1057102509656768563/1076951940333846549
## Details
Created a `zoo/` folder with the indigenous lifeforms of the Ember Waste, the Acheron (pinging @Saugia), and the Deep Space (pinging @MasterOfGrey).

Also moved the Elenchus data to the `hai/` folder and deleted the unused "Forest (Predator)" government.

2023-04-01 12:33 UTC, Zitchas requested changes
Overall this is probably a good idea. However, I would recommend using a better name than "zoo." Perhaps "space wildlife" or just merely "wildlife."

That being said, there are reasons for the indigenous wildlife of the Ember Waste to be stored where they are, and it would be best to leave them there.

2023-04-01 12:33 UTC, Zitchas commented on data/zoo/indigenous.txt
The indigenous creatures of the Ember Waste have reasons for being where they are. Please do not move this file.

2023-04-01 12:55 UTC, TomGoodIdea commented on data/zoo/indigenous.txt
Could you please explain the reasons?

2023-04-01 13:08 UTC, warp-core commented on data/governments.txt
> -government "Forest (Predator)"
This government is still referred to in the `"Pirate (Devil-Run Gang)"` definition, you'll need to remove that line as well.
https://github.com/endless-sky/endless-sky/blob/a45fb00b7f03f22844b81452546eaecd03fddae5/data/governments.txt#L953

2023-04-19 23:19 UTC, Amazinite commented
I don't think that it makes sense to throw all the space life stuff into the same folder. As Zitchas has noted, the void sprites aren't just window dressing, they have story importance. The other space life groups only lack story importance insofar as they're much newer groups.

I'd say strip this down to just the removal of the unused government, leaving everything else where it is.

2023-04-20 13:21 UTC, TomGoodIdea commented
Alright, I'll close this PR and open a new one for the unused government removal.

2023-04-20 13:32 UTC, closed without merging