Don't disable steering keys while mouse turning is on
endless-sky/endless-sky pull request #8650
Opened 2023-04-09 18:07 UTC by warp-core

**Feature:**

## Feature Details
Mouse turning no longer disables the steering keys.
Hopefully, this makes it clearer to anyone who has unintentionally turned mouse turning on what is going on, since they'll see the ship turning towards the cursor when they release the steering keys.

2023-04-10 14:50 UTC, samrocketman requested changes
I am not in favor of this. This will interfere with alternate control schemes such as steam deck where turning would occur on the joy pad.  It still makes sense to have thrust and keep steering disabled.

I think the best and most obvious fix is https://github.com/endless-sky/endless-sky/pull/8620

This should be a preference and have a tutorial to be the most obvious.  In this case, it wouldn't be possible for players to enable by mistake because it is a preference.  Let's priorities the permanent fix.

2023-04-10 23:49 UTC, Saugia commented
As I mentioned in #8620, the issue is Left Alt being used as a bind for this. A majority of PC users alt-tab all the time, so this can get incredibly frustrating. Either it should be disabled by default, or (preferably) we use a key different than Left Alt.

2023-04-11 01:02 UTC, samrocketman commented
Alt tab no longer affects this @Saugia .  Your concern was already addressed with https://github.com/endless-sky/endless-sky/pull/8519

2023-04-11 01:26 UTC, Saugia commented
My mistake. I see now. On another note, I do think this is also a good idea, to keep steering keys enabled.

2023-04-14 04:39 UTC, Amazinite commented
I don't think it makes sense to make changes that make it more obvious to players that they've accidentally enabled something they didn't want to. We should instead simply make it difficult to accidentally enable mouse turning in the first place, which making it a preference would do.

2023-04-14 04:39 UTC, closed without merging