feat(content): Alternate Gegno intro ending if hostile with Quarg
endless-sky/endless-sky pull request #8684
Opened 2023-04-23 18:17 UTC by Saugia

**Content (Artwork / Missions / Jobs)**

## Summary
It was brought up that being hostile with the Quarg essentially blocks the rest of the Gegno intro, as you won't be allowed to land on their ringworld to complete it. Instead of allowing the player to land with clearance, I've written an alternate path in such a case.

I've made the original mission require a positive reputation with the Quag, and added a new one that offers if you are negative with them. If you have discovered the Quarg Ringworld system, the intro mission will simply end on Dueyu Eitch. If you have not, you will receive a conversation upon entering the ringworld's system where you will have a brief chat with the Quarg and why a bad noodle doesn't get help from them.

This doesn't mean Gegno content will be locked if the player has a hostile Quarg relation - just that the Quarg won't be involved at all. 

## Save File
Working on it.

2023-04-23 18:35 UTC, Arachi-Lover approved these changes
Seems alright, though with the whole effort to show it's hard to find a Quarg that speaks human in Giaru Gegno, maybe the Quarg that speaks with you could be a bit less eloquent. Though, maybe one could argue that with a human becoming an enemy they'd have some Quarg around everywhere to tell folks to be wary, and so would be present.

Other than that though, only thing I'd change is add a "now get off our lawn" kind of last message from the Quarg, at the end of the convo.

2023-04-24 19:14 UTC, Saugia commented
Yeah, I'd leave it to the idea that the Quarg on this ring were notified through some means by other human-speaking Quarg that the [hostile] player is near their area, or human-speaking Quarg moved there before the player entered the area. It'd be weird to have a "wait for translator" session with hostile Quarg, and it would be in character that they already prepared it.

2023-04-24 22:06 UTC, roadrunner56 requested changes

2023-04-24 22:06 UTC, roadrunner56 commented on data/gegno/gegno intro missions.txt
> +			`	You begin prepping your ship for depature, and the <alien> leaves your ship. They walk towards the others, have a brief discussion, and another smaller group of <aliens> arrive with what looks t
```suggestion
			`	You begin preparing your ship for departure, and the <alien> leaves your ship. They walk towards the others, have a brief discussion, and another smaller group of <aliens> arrive with what looks to be some type of fueling device. After a minute or so of fidgeting with it, they manage to hook it up to your ship. These <aliens> look shorter and thinner than the others, and wear more leather-like garments than heavy metal ones - but their demeanor is just as rigid. Once your ship's fuel has been filled, the <alien> that has been guiding you points towards the sky. Visiting the Quarg isn't an option, so it seems associating with these <aliens> is unlikely for the foreseeable future.`
```

2023-04-25 01:40 UTC, roadrunner56 approved these changes

2023-04-26 13:32 UTC, LorenzoBolla approved these changes

2023-04-29 17:40 UTC, tibetiroka approved these changes
Grammar looks OK.

2023-04-30 00:50 UTC, W1zrad approved these changes

2023-04-30 00:50 UTC, merged