Even more typo fixes
endless-sky/endless-sky pull request #8755
Opened 2023-05-13 06:43 UTC by tibetiroka

Fixes typos related to repeated words, inspired by #8754.

I believe this PR only contains typo fixes that are not in that PR.

2023-05-13 07:21 UTC, EjoThims approved these changes

2023-05-13 08:41 UTC, MasterOfGrey commented on data/hai/hai reveal 2 start.txt
> +			`	The two women put on clothing that thoroughly covers their person. They lead you through a series of ducts and alleys back to the pad where your ship is parked. Just as your airlock opens there'
This is not a repeated word error, both words are correct.
It may need some form of additional punctuation though.

2023-05-13 11:12 UTC, EjoThims requested changes
Proposed punctuation changes, both with and without repeating the back to back "you."

2023-05-13 12:03 UTC, tibetiroka commented on data/hai/hai reveal 2 start.txt
> +			`	The two women put on clothing that thoroughly covers their person. They lead you through a series of ducts and alleys back to the pad where your ship is parked. Just as your airlock opens there'
I prefer this one, but I'll wait for @MasterOfGrey's opinion before resolving it.

2023-05-14 00:03 UTC, mOctave commented on data/hai/hai reveal 2 start.txt
> +			`	The two women put on clothing that thoroughly covers their person. They lead you through a series of ducts and alleys back to the pad where your ship is parked. Just as your airlock opens there'
This one is definitely much nicer than the other three versions, in my opinion.

2023-05-14 13:55 UTC, MasterOfGrey commented on data/hai/hai reveal 2 start.txt
> +			`	The two women put on clothing that thoroughly covers their person. They lead you through a series of ducts and alleys back to the pad where your ship is parked. Just as your airlock opens there'
I'll back this one as it has the least clustering of additional commas.

2023-05-14 20:20 UTC, W1zrad approved these changes

2023-05-14 20:20 UTC, W1zrad commented on data/hai/hai reveal 2 start.txt
> +			`	The two women put on clothing that thoroughly covers their person. They lead you through a series of ducts and alleys back to the pad where your ship is parked. Just as your airlock opens there'
Re: the conversation about this sentence. @tibetiroka 's first edit was actually grammatically correct (as best I can tell), and the original was grammatically incorrect (oops, I reviewed this myself when HR was PRed). Regardless, this new version that y'all workshopped is definitely an improvement for readability.

2023-05-14 21:04 UTC, merged