feat(enhancment): More Motion Blur While Hyperspacing
endless-sky/endless-sky pull request #9008
Opened 2023-07-07 03:51 UTC by Koranir

## Feature Details
Makes the motion blur more intense while hyperspacing.

## UI Screenshots
[Screencast from 2023-07-07 13-49-13 (trimmed).webm](https://github.com/endless-sky/endless-sky/assets/101683475/4f599d42-0a01-40ef-94dc-1dfbbf48953b)

## Performance Impact
N/A

2023-07-07 06:45 UTC, OcelotWalrus commented
It's extremely cool I think but it would be better to add a setting like 'hyperspace blur' that you can set to 'off', 'low', 'medium', 'high'. And medium would be the current blur.

2023-07-07 12:39 UTC, Hurleveur commented
I think we can already turn it on and off? Not sure but if so it'd make sense to add it to that, and I agree with OcelotWalrus

2023-07-07 13:17 UTC, RisingLeaf requested changes

2023-07-07 13:17 UTC, RisingLeaf commented on source/Ship.cpp
> +int Ship::IsHyperspacing() const
should probablz be renamed to GetHyperspaceCount() as the is implies a bool return

2023-07-08 06:28 UTC, Koranir commented
Apparently, the starfield does not have motion blur disabled when motion blur should be disabled.

*why*

2023-07-08 08:14 UTC, RisingLeaf approved these changes

2023-07-08 15:42 UTC, Zitchas commented
So long as this motion blur can be made to be disabled by the motion blur setting, then I'm ambivalent. Until then, however, I'm strongly against having more motion blur anywhere.

2023-07-09 20:46 UTC, warp-core reviewed
What's the reason for removing the existing method?

2023-07-09 22:50 UTC, Koranir commented
> What's the reason for removing the existing method?

If you're talking about the IsHyperspacing() method, `int` implements the `operator bool` operator and has the exact same functionality if used with `logical and`s. I don't see a need to have two methaods that do the exact same things in the end.

2023-07-09 22:53 UTC, warp-core commented
> > What's the reason for removing the existing method?
> 
> If you're talking about the IsHyperspacing() method, `int` implements the `operator bool` operator and has the exact same functionality if used with `logical and`s. I don't see a need to have two methaods that do the exact same things in the end.

I think calling a method named `IsHyperspacing` is a lot more meaningful when you want to know, well, if the ship is hyperspacing, than what's going on in this PR now. There's no reason to remove that. That method could even just call the new one and do the boolean conversion itself.

2023-07-30 19:08 UTC, Amazinite commented on source/Engine.cpp
> +		// The starfield always has motion blur, so avoid increasing the blur if the player doesn't want it.
Isn't this comment no longer the case as of #9011?

2023-07-31 03:25 UTC, Koranir commented
> > > What's the reason for removing the existing method?
> > 
> > 
> > If you're talking about the IsHyperspacing() method, `int` implements the `operator bool` operator and has the exact same functionality if used with `logical and`s. I don't see a need to have two methaods that do the exact same things in the end.
> 
> I think calling a method named `IsHyperspacing` is a lot more meaningful when you want to know, well, if the ship is hyperspacing, than what's going on in this PR now. There's no reason to remove that. That method could even just call the new one and do the boolean conversion itself.

Chaged to have two methods now.

2023-07-31 15:57 UTC, warp-core commented
This also seems to add some motion blur to the starfield when using a jump drive, is that intentional?

2023-08-01 20:44 UTC, Koranir commented
> This also seems to add some motion blur to the starfield when using a jump drive, is that intentional?

Yes

2023-08-01 21:48 UTC, merged