Prevent random Pug fleets from leaving Pug systems
endless-sky/endless-sky pull request #9422
Opened 2023-10-07 17:19 UTC by Amazinite

**Content (Artwork / Missions / Jobs)**

## Summary
Prevent random Pug fleets from leaving Pug systems and jumping into human or Wanderer space by giving the two Pug governments travel restrictions to not travel to any location that isn't one of their own. In order to not have Pug fleets stack up in single systems and still appear to jump in and out, added three hidden "pocket dimension" systems that share a position with the main systems and act as viable jump destinations for Pug fleets.

No changes made to campaign Pug fleets because NPCs don't follow travel restrictions by default.

Resolves #8876.

## Testing done

Observed that Pug fleets still spawn in Pug systems. They sometimes jump out, but they never jumped out to an accessible system, meaning they're jumping to the hidden pocket dimension systems.

2023-10-07 22:14 UTC, Anarchist2 commented
What about using a new government for the pocket dimensions, and restricting the Pug to only be able to travel to those systems (i.e., not their home systems)? That way, you only need to make one system to stop the Pug from jumping in and out.

2023-10-07 22:25 UTC, Amazinite commented
There only needs to be one system anyway. I added three systems so that the Pug that jump out aren't constantly jumping in and out of the same system; they might be bouncing between the hidden systems.

2023-10-07 22:29 UTC, Amazinite commented
That way they only ever jump into the system to spawn and out of the system to leave. This way they sometimes land on or take off from the planet in the system.

2023-10-08 03:33 UTC, Amazinite commented
That method also means that during the FW campaign, the Pug would never travel between any of the systems in their expanded territory.

2023-10-08 04:01 UTC, mOctave commented on data/map systems.txt
> +
Is this extra newline intentional?

2023-10-08 04:13 UTC, Amazinite commented on data/map systems.txt
> +
Nope.
```suggestion
```

2023-10-08 06:36 UTC, Hurleveur approved these changes
just tested it, looks like it works well

2023-10-08 18:04 UTC, ziproot requested changes
From what I can tell, it is impossible to check for whether or not a system is hidden inside missions, and hidden systems can be chosen by missions. The remnant research mission at the moment would be able to pick these systems. These changes make it so the remnant research mission is unable to pick these systems.

2023-10-08 18:04 UTC, ziproot commented on data/map systems.txt
> +	government "Pug (Wanderer)"
```suggestion
	government "Pug (Wanderer)"
	attributes "inaccessible"
```

2023-10-08 18:04 UTC, ziproot commented on data/map systems.txt
> +	government "Pug (Wanderer)"
```suggestion
	government "Pug (Wanderer)"
	attributes "inaccessible"
```

2023-10-08 18:04 UTC, ziproot commented on data/map systems.txt
> +	government "Pug (Wanderer)"
```suggestion
	government "Pug (Wanderer)"
	attributes "inaccessible"
```

2023-10-08 18:04 UTC, ziproot commented on data/map systems.txt
> +	government Pug
```suggestion
	government Pug
	attributes "inaccessible"
```

2023-10-08 18:04 UTC, ziproot commented on data/map systems.txt
> +	government Pug
```suggestion
	government Pug
	attributes "inaccessible"
```

2023-10-08 18:04 UTC, ziproot commented on data/map systems.txt
> +	government Pug
```suggestion
	government Pug
	attributes "inaccessible"
```

2023-10-08 18:08 UTC, Hurleveur commented
It'd be fun if the remnant point you to these systems actually but you're right that they'd have to be more developped first

2023-10-10 12:54 UTC, ziproot approved these changes
This looks good now.

2023-10-11 00:10 UTC, mOctave commented
Just to make sure, they can be `inaccessible` and still be accessed by NPCs, right?

2023-10-14 21:15 UTC, Amazinite commented
Inaccessible is just an attribute that only influences the locations that missions/jobs can choose from.

2023-10-14 21:17 UTC, merged