Improve the linux CMake instructions a bit
endless-sky/endless-sky pull request #9468
Opened 2023-10-16 12:01 UTC by quyykk

**Bugfix:** This PR fixes #9450 

## Fix Details

Improves the CMake docs for Linux a bit:

- Mention the minimum version needed for Debian/Ubuntu
- Add gles preset mention
- Mention `cmake --list-presets`
- Add a short sentence about needing to install additional dependencies when building from source.

2023-10-20 01:07 UTC, shitwolfymakes commented
I'll spin up a VM and reply when I've had time to confirm

2023-10-20 18:00 UTC, shitwolfymakes commented
These worked, but it still needs curl added to the dependencies so it doesn't break during configuration

2023-11-12 00:38 UTC, shitwolfymakes commented
Perfect, this is ready to be merged

2023-11-24 21:37 UTC, warp-core requested changes
It might also be useful to include some indication of what versions of the dependencies are necessary, or are we saying you have to have the latest version or build from source?

2023-11-24 21:37 UTC, warp-core commented on docs/readme-cmake.md
> +You can use your favorite package manager to install the needed dependencies. If you're using a slower moving distro like Ubuntu or Debian (or any derivatives thereof), make sure to use at least Ubun
```suggestion
You can use your favorite package manager to install the needed dependencies. If you're using a slower moving distro like Ubuntu or Debian (or any derivatives thereof), make sure to use at least Ubuntu 22.04 LTS or Debian 12.
If your distro does not provide up-to-date version of these libraries, you will need to tell CMake to build the libraries from source by passing `-DES_USE_SYSTEM_LIBRARIES=OFF` while configuring. Older versions of Ubuntu and Debian, for example, will need this. Additional dependencies will likely need to be installed to build the libraries from source as well.

In addition to the below dependencies, you will also need CMake 3.21 or newer. You can get the latest version from the [offical website](https://cmake.org/download/).
```

2023-11-24 21:37 UTC, warp-core commented on docs/readme-cmake.md
> +**Note**: If your distro does not provide up-to-date version of the needed libraries, you will need to tell CMake to build the libraries from source by passing `-DES_USE_SYSTEM_LIBRARIES=OFF` while c
```suggestion
```

2023-11-24 22:13 UTC, warp-core approved these changes

2023-11-24 22:14 UTC, merged