Update version numbers, credits, and changelog for 0.10.4
endless-sky/endless-sky pull request #9480
Opened 2023-10-20 00:14 UTC by warp-core

**Docs and stuff:**

## Details:
- Update version numbers from "0.10.4-alpha" to "0.10.4";
- Update credits (one new contributor);
- Update changelog.

2023-10-20 00:36 UTC, bene-dictator requested changes

2023-10-20 00:36 UTC, bene-dictator commented on changelog
> +      * Outfits can be given the "unique" attribute which will cause hte player to be warned when they are about to be lost. (@TomGoodIdea)
```suggestion
      * Outfits can be given the "unique" attribute which will cause the player to be warned when they are about to be lost. (@TomGoodIdea)
```

2023-10-20 00:36 UTC, bene-dictator commented on changelog
> +      * Fix scrolling up with the keyboard from the top of a short list int he load panel causing all the items to snap to the bottom. (@warp-core)
```suggestion
      * Fix scrolling up with the keyboard from the top of a short list in the load panel causing all the items to snap to the bottom. (@warp-core)
```

2023-10-20 00:36 UTC, bene-dictator commented on changelog
> +    * The "extended jump effects" setting is now off by default, and has an additional intermediate level of motino blur. (@RisingLeaf, @TomGoodIdea)
```suggestion
    * The "extended jump effects" setting is now off by default and has an additional intermediate level of motion blur. (@RisingLeaf, @TomGoodIdea)
```

2023-10-20 05:48 UTC, bene-dictator commented
Just wondering, aren't you missing from the developer list, and me, EjoThims, Terin, and Tibetiroka missing from the proofreaders list?

2023-10-20 19:07 UTC, warp-core commented
> Just wondering, aren't you missing from the developer list, and me, EjoThims, Terin, and Tibetiroka missing from the proofreaders list?

I haven't reviewed the criteria used for adding to those lists in the past so I haven't been updating them myself.

2023-10-21 19:18 UTC, TomGoodIdea commented on changelog
> +version 0.10.4
```suggestion
Version 0.10.4
```

2023-10-21 19:40 UTC, merged