fix(content): Earth day jobs no longer offer if you cannot land on Earth without bribing authorities
endless-sky/endless-sky pull request #9715
Opened 2024-01-23 16:05 UTC by ziproot

**Bug fix**

This PR addresses the bug described in issue #7663 

## Summary
This replaces the directly specified destination with a location filter that can only choose that destination. This way, if you do not have clearance the job will not offer.

## Screenshots
What am I going to do, show Earth Day jobs not offering?

## Testing Done
Tested to make sure no Earth Day jobs offered.

## Save File
This save file can be used to test these changes:
TBD because the issue opener didn't provide one

2024-01-23 16:50 UTC, ziproot commented
This should work. I have finally outsmarted the game.

2024-01-23 21:40 UTC, alexrovw requested changes
I agree with changing this behavior, but I think there's a better way to implement it.

**Concerns with the proposed solution**:
1. Hacky: Tricking the filter is a bit hacky, and it isn't self-documenting. Someone in the future would need to know why you instituted this workaround, or they might think it's bad code and change it.
2. Fragile: If there is ever a change that either removes/replaces `urban` from Earth or adds a new landable to Sol that has `urban`, this change would result in a bug.

**Alternative proposal**:

I suggest that this would be better resolved with the `to offer` block.
Something like
```
to offer
	"reputation: Republic" > 0
```
was brought up in #7663, but @ThrawnCA correctly pointed out that this would prevent players whom have tributed Earth from seeing the jobs.
So why don't we just add that as a condition?

```
to offer
	or
		"reputation: Republic" > 0
		has "tribute: Earth"
```
The above is what I propose. It would be more resilient and self-documenting than the filter hack. Would you consider implementing that instead?

2024-01-23 23:38 UTC, ziproot commented
I have given earth a special attribute instead. This way in all cases, if you can land on Earth, you will be offered the mission. If you cannot land on Earth, you will not be offered the mission.

If Earth has required reputation -10, then you will not be offered Earth Day jobs to Earth if your reputation is between -10 and 0 even though all other jobs would offer to Earth.

If you can get required reputation as an autocondition I will switch to a `to offer` condition. If the location filter doesn't turn planet X into a fixed destination (my preferred option) I will switch to that. For now, this is the best way to ensure consistency with other missions and jobs. Yes, it's a bit confusing, but it's the fact that fixed destinations and some location filters work one way, and every other location filter works a different way, that's confusing.

2024-01-24 00:34 UTC, Amazinite commented
This seems more hacky to me.

2024-01-24 00:41 UTC, alexrovw requested changes
I've proposed some changes to the comments to improve readability, but I'm not 100% sold on using this as a workaround. It's still reliant on the location filter behavior, but at least there are comments to explain the situation.

Personally, I think it would be valid for Earth Day jobs to disappear from the job board _in any scenario when your Republic reputation is < 0; nobody's going to want to fly to Earth in a ship that's going to be shot at by the Republic. I'm somewhat comfortable with allowing these jobs to reappear if you dominate Earth, though.

I think your point about the required reputation is true, but the situation in which Earth's required reputation would be modified to be negative is pretty unlikely. My ideal fix would be to have some kind of `"can land on: <planet>"` attribute for situations like this, but that's outside the scope of this PR.

2024-01-24 00:41 UTC, alexrovw commented on data/map planets.txt
> +	attributes factory "near earth" research tourism urban earth
```suggestion
	attributes earth factory "near earth" research tourism urban
```
Attributes need to be in alphabetical order

2024-01-24 00:41 UTC, alexrovw commented on data/map planets.txt
> +	# Earth attribute is required for earth day job location filters to filter out planets that you cannot land on. A better option is for "planet Earth" to not be replaced with a fixed destination.
```suggestion
	# "earth" attribute is used for "Earth Day" jobs as a workaround to fail the location filter when Earth is hostile.
```
Less wordy

2024-01-24 00:41 UTC, alexrovw commented on data/human/near earth jobs.txt
> +		# Replace with planet Earth and remove attribute from Earth when doing so would not result in the game turning it into a fixed destination. This way Earth is filtered out if you cannot land there.
```suggestion
		# "earth" attribute is used for "Earth Day" jobs as a workaround to fail the location filter when Earth is hostile.
```

2024-01-24 00:41 UTC, alexrovw commented on data/human/near earth jobs.txt
> +		# Replace with planet Earth and remove attribute from Earth when doing so would not result in the game turning it into a fixed destination. This way Earth is filtered out if you cannot land there.
```suggestion
		# "earth" attribute is used for "Earth Day" jobs as a workaround to fail the location filter when Earth is hostile.
```

2024-01-24 00:41 UTC, alexrovw commented on data/human/near earth jobs.txt
> +		# Replace with planet Earth and remove attribute from Earth when doing so would not result in the game turning it into a fixed destination. This way Earth is filtered out if you cannot land there.
```suggestion
		# "earth" attribute is used for "Earth Day" jobs as a workaround to fail the location filter when Earth is hostile.
```

2024-01-24 00:48 UTC, ziproot commented
Alright, I have changed it. I wouldn't have to resort to hacks or half measures (if Earth isn't controlled by the Republic this breaks) if the location filter of planet "Earth" didn't turn into a fixed destination.

2024-01-24 01:09 UTC, Amazinite commented
Give #9716 a spin.

2024-01-24 01:45 UTC, ziproot commented
I gave it a spin. It works!

2024-02-17 22:28 UTC, merged

2024-02-18 04:17 UTC, ziproot commented
~~dev abuse~~
![image](https://github.com/endless-sky/endless-sky/assets/109186806/e4cb647a-03f7-4cab-9c0d-33222861ba99)