feat(content): Some new human hails about dumping cargo for pirates
endless-sky/endless-sky pull request #9758
Opened 2024-02-04 15:13 UTC by tibetiroka

**Content (Artwork / Missions / Jobs)**

This PR adds some new hails as mentioned in the campfire chat.

## Summary
Adds some pirate hails requesting you to drop your cargo, and some merchant hails recommending this strategy.

## Testing Done
None.

## Save File
N/A

2024-02-04 18:12 UTC, bene-dictator approved these changes

2024-02-04 18:59 UTC, roadrunner56 approved these changes

2024-02-04 23:04 UTC, mOctave approved these changes

2024-02-04 23:04 UTC, mOctave commented on data/human/hails.txt
> +		"If ye provide me yer coffer, ye may set sail."
I feel like there's a missed opportunity for a coffin pun here.

2024-02-05 06:19 UTC, EjoThims requested changes

2024-02-05 06:19 UTC, EjoThims commented on data/human/hails.txt
> +		"Drop your cargo and I may spare your miserable life."
```suggestion
		"Drop your cargo, and I may spare your miserable life."
```

Pretty sure this is still needed with the imperative first clause.

2024-02-05 11:40 UTC, EjoThims approved these changes

2024-02-11 20:01 UTC, W1zrad approved these changes

2024-02-11 20:01 UTC, merged