feat(content): Conspiracy theorist spaceport news
endless-sky/endless-sky pull request #9937
Opened 2024-03-21 18:20 UTC by tibetiroka

**Content (Artwork / Missions / Jobs)**

This PR adds more spaceport news in topics requested on discord.

## Summary
More conspiracy theorist news about:
 - the Rigellian Plague
 - the Quarg
 - flat planets
 - diseases
 - hyperdrive tech
 - birds
 - drag

## Testing Done
I tested that the news show up and don't generate errors.

## Save File
N/A, pretty much any human planet is valid

2024-03-21 23:48 UTC, bene-dictator commented on data/human/news.txt
> +			"If the Rigellian Plague really happened, how come we have so little quarantine facilities now?"
```suggestion
			"If the Rigellian Plague really happened, how come we have so few spaceport quarantine facilities now?"
```
Maybe they don't know the difference. It'd be funnier.

2024-03-21 23:48 UTC, bene-dictator commented on data/human/news.txt
> +			"If spaceships have drag, there must be air in the 'vacuum of space'..."
~~Unrealistic.~~

2024-03-22 03:19 UTC, roadrunner56 requested changes
Mostly just adding contractions to make some news lines sound more conversational.

2024-03-22 03:19 UTC, roadrunner56 commented on data/human/news.txt
> +			"Republic Intelligence has bird-like surveillance drones in every city. There is one in front of my window every morning."
```suggestion
			"Republic Intelligence has bird-like surveillance drones in every city. There's one in front of my window every morning."
```

2024-03-22 03:19 UTC, roadrunner56 commented on data/human/news.txt
> +			"The Quarg are running the government. There is no way such a powerful species wouldn't be able to control us."
```suggestion
			"The Quarg are running the government. There's no way such a powerful species wouldn't be able to control us."
```

2024-03-22 14:22 UTC, tibetiroka commented on data/human/news.txt
> +			"The Quarg built the pyramids of Earth. There is simply no way that humans could have constructed something so massive back then."
~~But then I'd have to lock it behind FW, you see~~

2024-03-22 16:39 UTC, Hurleveur commented on data/human/news.txt
> +			"The Quarg built the pyramids of Earth. There is simply no way that humans could have constructed something so massive back then."
If anything I'd expect an actual alien invasion to bring way more conspiracy theories, yes :james:

2024-03-22 16:41 UTC, tibetiroka commented on data/human/news.txt
> +			"The Quarg built the pyramids of Earth. There is simply no way that humans could have constructed something so massive back then."
There are news for that in `pug news.txt`.

2024-03-22 18:44 UTC, Hurleveur commented on data/human/news.txt
> +			"The Quarg built the pyramids of Earth. There is simply no way that humans could have constructed something so massive back then."
honestly conspiracy theorists knowing about the Pugs would be cool?
the deep know about them, aint hard to get those stories, and the name surely can be found if you dig a bit

2024-03-22 23:09 UTC, roadrunner56 approved these changes

2024-03-24 01:45 UTC, warp-core commented on data/human/news.txt
> +			"Truth Seeker"
News names only capitalise the first letter of the first word.
```suggestion
			"Conspiracy theorist"
			"Free thinker"
			"Truth seeker"
```

2024-03-24 05:17 UTC, Amazinite commented on data/human/news.txt
> +			" You are being lied to!"
```suggestion
			" You are being lied to!"
			" Break the conditioning!"
```

2024-03-24 08:09 UTC, merged